### ISSUE TITLE
mtDNA issues after Scout update

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1062]
1.	After last update in Scout all the fields for “Transcript overview” are empty for mtDNA variants. If you under “HGVS Description” want to present both c. and p. it is ok, but as I said in #793 it is not relevant with c. for the report.
 
![bild](https://user-images.githubusercontent.com/15033593/48204724-cff86080-e36a-11e8-929b-694659997f26.png)

2.	We have run Case 17121 before and after last update. They are called 17121 (Analysis date 2017-08-18) and 17121-muscle (Analysis date 2018-10-26). The first one is DNA from blood and the second from muscle. I have been worried that not all variants have been presented in Scout and I think my worries are justified. When I compare the two cases the number of variants displayed in Scout are not the same. There are a lot more variants presented for the last Case. There are 34 variants for the last one and only 11 variants for the first one. In the first one only variants with rank score down to 7 are presented. This means more variants are loaded after update, which is good. The problem is however that we have missed a lot of variants during the last year without being aware of it. 

But we still miss other variants as discussed in #793. Even if 34 variants now are presented, I am sure there are more missing from the non-coding parts.

3.	The reference sequence for mtDNA should be NC_012920.1. This reference sequence has been changed and has a N in position 3107. This has not been shown in Scout before the update. Now there are probably false variants presented in Scout in different ways because of this. Is there a way to correct this? The numbering of the variants after this position must not be affected?
For example:
https://scout.scilifelab.se/cust003/17121-muscle/67e00236ae5fd5cbea960555af4170ab
https://scout.scilifelab.se/cust003/18217/58c9d6af739dd446b1d85fd427a5492c
https://scout.scilifelab.se/cust003/18219/4b5cee8afbaf5c3cb29ddf1937242fc1
https://scout.scilifelab.se/cust003/18219/e86fd37d0d63e9f5b545644a09d2e09b

4.	The GT calls (Allele depth for reference and alternative allele) are presented in a strange way in some regions. Something must be wrong here? 

Example 1 in Case 17121-muscle:
https://scout.scilifelab.se/cust003/17121-muscle/874869be57cdfc681b4060614b5fe643
m.10397AACC>GGCT		Allele depth=14/78713
https://scout.scilifelab.se/cust003/17121-muscle/81cdc84394d0008dea108cebb108c578
m.10397A>G		Allele depth=2/2430
https://scout.scilifelab.se/cust003/17121-muscle/28b66703c0e225aacc8b8939632a5dd2
m.10398A>G   		Allele depth=2/2430
https://scout.scilifelab.se/cust003/17121-muscle/b984b330e016bd2d03e58c2231070e72
m.10400C>T		Allele depth=2/2474

How is it possible that the first annotation which present “the same” variants as the other ones has an allele depth of 78713 on the alternative allele?

Example 2 in Case 17121-muscle:
https://scout.scilifelab.se/cust003/17121-muscle/53b6c5e737a909b5d986c39d89afca0b
m.750AAC>GAT		Allele depth=2/82056
https://scout.scilifelab.se/cust003/17121-muscle/20d95eb47a487ad3f72fc05f9a326d5c
m.752C>T		Allele depth=0/538
https://scout.scilifelab.se/cust003/17121-muscle/ef4642af4880311df0124399dfbf3749
m.750A>G		Allele depth=0/544

5.	In some earlier update of Scout all variants suddenly were reported in both the affected gene and in a lot of other genes as upstream or downstream. This problem you fixed. There are however a few variants still presented to be connected to two genes. For example variants in MT-ND3 that also get annotated as upstream to MT-TR, or variants in MT-CYB that also get annotated as upstream MT-TT.
Examples:
https://scout.scilifelab.se/cust003/17121-muscle/81cdc84394d0008dea108cebb108c578
https://scout.scilifelab.se/cust003/18214/ef443208152601b93fbd5c7a1f81a574

It would be better that variants only show up connected to the affected gene in mtDNA. It is not a big problem when you go through data in Scout but there is a bigger problem when it comes to the exporting of the report, where it gets a bit tricky to follow the presented data.

6.	We have started to use the NGS data presented in Scout to quantify the heteroplasmic level of a mutation in mtDNA. We have used the ratio, of the allele depth, of the reference and the alternative allele. 

One example in Case 18100:
https://scout.scilifelab.se/cust003/18100/221082fd993e1a42cd8e1c4f2ec66b5f
![bild](https://user-images.githubusercontent.com/15033593/48204960-76446600-e36b-11e8-8585-7703d760061f.png)

 In this case we would say the mother in this family has this mutation at a heteroplasmic level of 92% and both children have it in homoplasmy, that is 100% of their mtDNA, in this tissue. Is this the right conclusion or is there more information in the raw data, reads of less good quality and so on, that is sorted away before the data is presented in Scout? It makes me more worried when I see things as the example above, where the allele depth for alternative allele, suddenly is over 80000 for a variant. This cannot be true.

7.	How is it going with the problem that variants with low (<10%) heteroplasmic level were not presented in Scout?  One example is Case 18089 where the mutation m.3243A>G is not loaded in Scout, even if it is there in 9% heteroplasmic level when you check manually. I have today requested a rerun in Scout of this Case to see if there is a difference after last update. I have done an export of variants before to compare.

8.	I have noticed that it now is possible to use IGV wiever for looking at mtDNA which is really good. It is possible to see all 16 kB in one view. Fantastic! This would maybe make it possible for us to search manually after deletions and duplications in mtDNA? I have now requested rerun of two Cases where we know there are deletions in mtDNA in different heteroplasmic levels to see how they look in IGV. 

9.	My feeling is that there is big risk something is happening with mtDNA data in Scout everytime you do an update. This makes me worried and I am afraid we will not notice if we suddenly miss variants in mtDNA of different reasons. Would it be possible to choose a good example Case in Scout that you rerun as a control every time you have done an update, do be sure everything is presented the same way and that all expected variants still are present?

**Comment by 1ctw** [comment]
Please notice that I also made comments in the closed issue #793. Could you please open this issue again.

**Comment by henrikstranneheim** [comment]
Thx for the feedback it is greatly appreciated!
1. The transcript overview is for refseq transcript and as far as I know there are no refseq transcripts identifiers for the MT genes. Therefore the transcript overview will be empty. We could use the ensembl transcript IDS for MT, but it will have to be a custom solution. Perhaps we could use the ensembl ID as the identifier in the map and display that if there are no refseq info (I will discuss with @moonso and @northwestwitch ).
2. After the update all MT variants in the vcf files will be loaded (without any other critera filtering the data i.e. panel or rank score). However, it will only affect samples loaded into Scout after the update and hence, not affect older analysis. That would require a reupload. We have communicated this several times and it should not come as a suprise to you. What is confusing the matter is that we might have not been entirely clear in what we mean when we say we have fixed this issue. It was solved long ago, but in is not in effect until the actual production code was updated which occured long after. We have now switched to a rolling release cycle meaning that the production code is updated much more frequently. That has taken a lot of effort, but is now thankfully in place. You can now be confident that all new analysis MT variants **PRESENT** in the vcf files will be loaded. But please rembember that the critera for the clinical test requires that the variant belongs to a gene panel and that in turn requires a gene or transcript IDs. Something which is lacking in the D-loop for instance and the D-loop at least to my knowledge is not present in the mtDNA panel and hence not present in the clinical vcf and therefore no variants for the D-loop is uploaded to Scout. One way of solving this is to make a special rule to populate the clinical view from the research vcf as all variants called are present there (again I have to discuss with @moonso and @northwestwitch if this is a good approach)
3. It has always been an N in the analysis (actualy it is in lots of places), it has not been evident since those variants usually have a low rank score and hence have not been loaded previously. I do not think anything needs correcting, but these should be down prioritized if we include a new loqus dump as is planned for mip v 7.0.
4. I do not have a good answer to that. But it seems like this is likely dependent on the caller that called the variant in this case freebayes. It looks like freebayes is mishandling the call, I would deem these as unreliable and considered them as false positives. We will post an issue on freebayes github and notify you what they say.  
5. This is due to the --distance option in VEP. We have previously together decide to use 10 bp for the MT contig. We can reduce it even more if you would like.
6. The low quality reads are usually not very many since the MT contig is quite easy to sequence and map. Therefore, in this case the AD is approximately always equal to the total depth at the variant site. Hence, you should be able to use the ration as a good proxy for calculating heteroplasmy levels.
7. The update is only on Scout and not MIP, these calls will not be affected. However, for MIP v7.0 we have switched to GATK v4 and it seems to to a better job at determing ploidy. We are currently testing it on the cases you have sent us previously. It would also be good to have cases with levels to test below 10%. Perhaps a synthetic dataset would suffice in a first pass. We will let you know when we have the results. 
8. Great!
9. A very good idea! Please suggest a case and we will include it in the standard validation set.

**Comment by moonso** [comment]
I do not really know what to do with this issue. Could you @henrikstranneheim and @1ctw close this and create smaller issues that defines what needs to be changed?

**Comment by henrikstranneheim** [comment]
1. See https://github.com/Clinical-Genomics/scout/issues/641
2. See https://github.com/Clinical-Genomics/scout/issues/1070
3. Solved in MIP/Cg https://github.com/Clinical-Genomics/cg/issues/234
4. Not Scout related
5. Done. https://github.com/Clinical-Genomics/MIP/issues/639 and https://github.com/Ensembl/ensembl-vep/issues/321
6. Not an issue.
7. See https://github.com/Clinical-Genomics/MIP/issues/507
8. Not an issue
9. Action needed by @1ctw  and include in validation using Mutacc/MIP. Not a Scout issue.

Only 2 Scout related issues, that already have cards. Closing this one.
