### ISSUE TITLE
Clinvar filter does not seem to work

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1079]
Tried filtering for Benign in this case:

https://scout.scilifelab.se/cust003/18232/371c47ef74b1ff6f9b77262aba7cb482

**Comment by dnil** [comment]
Yep, broken, specifically for searches where no other criteria are added. Presumably means the test is also not complete.

**Comment by dnil** [comment]
Looks like it works as intended for older cases: 2017 ok, 2018 aug ok, but not 2018 oct. Something that changed in MIP 6 that we haven't covered for in Scout?

**Comment by northwestwitch** [comment]
It looks like that at a certain point the clnsig.value of the variant was saved as a string, instead of a number, as for old variants and the ones in the demo data. For the variant mentioned above this value is "Benign, Likely benign" instead of 2,3. I can fix it tomorrow. But why did we change these values?

**Comment by dnil** [comment]
Well found! Looks like it was changed a bit en passant in "Adds one more way to parse CLINVAR. Fix #695". Ask @moonso if there was any particular reason, or if it was just more straight-forward? The filter could probably live with either; the integer representation has no particular meaning and is used in a one-to-one fashion with the string anyway.
