### ISSUE TITLE
GT call: genotype and read do not fits toegether

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1098]
https://scout.scilifelab.se/cust003/14006/68c935a1f2956a19ed3633b625e19c95
A variant in SMC1A , gene on X chromosome.

I can not understand how a 14006-II-1U (male) can have genotype 0/1 but reads are 10 for the Reference and 0 for Alternative..... I can not see any reads in IGV with the alternative nt so why the  genotype is 0/1?
this wrong genotype leads to a "NO" in the window for matching inheritance, the mutation looks instead de novo.

Michela

**Comment by 1ctw** [comment]
Another example of the same problem with another variant on X chromosome:

https://scout.scilifelab.se/cust003/139/93651fbf1b8f368c67f8a411425f84ae

**Comment by 1ctw** [comment]
And another example:

https://scout.scilifelab.se/cust003/18239/28b8e5b0836c688cf24bd721060a2f51

**Comment by moonso** [comment]
This looks weird, something for @henrikstranneheim to check in MIP

**Comment by henrikstranneheim** [comment]
I think it is the genotype refinement that introduce this error. The goal of the Genotype Refinement workflow is to use additional data to improve the accuracy of genotype calls and to filter genotype calls that are not reliable enough for downstream analysis.
This genotype refinement process is only done for trios. This mis-assignement of GT type seems to occur more frequently on chr X (pure specualtion so far).
Here is the raw data for 18239:
```
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=PP,Number=G,Type=Integer,Description="Phred-scaled Posterior Genotype Probabilities">
#CHROM	POS	ID	REF	ALT	FORMAT	ACC5147A3	ACC5147A4	ACC5147A5
X	77258665	210395	C	T	GT:AD:DP:GQ:JL:JP:PL:PP	0/0:38,0:38:50:0:6:0,104,1495:0,50,1441	0/1:15,0:15:15:0:6:0,45,561:15,0,516	0/1:0,18:18:6:0:6:736,54,0:637,0,6
```
Look at the PL and PP for ACC5147A4:
- The GT call is 0/1, however according to the PLs (0,45,561) it should be: 0/0.
- PPs (15,0,516), overrides the original PL and gives: 0/1, albeit with a low GQ (=15, anything lower and around 20 tells you the caller is really uncertain of the GT assignment).

I would suggest looking at the reads and making a manual call when the GQ is this low (actually most pipelines would probably filter this out). As long as the GT follows any inheritance model we should not miss any variants.

We will switch the 1000G file we have been using so far to gnomad and use GATK 4 instead of 3.8 and maybe that will help some but again I am speculating here.

**Comment by moonso** [comment]
I'm going to close this since there is nothing we can do in scout. Please continue discussion in https://github.com/Clinical-Genomics/MIP/issues/681
