### ISSUE TITLE
Conservation values have gone bye-bye?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1125]
It appears we have lost touch with evolutionary conservation. We wonder where and when?

**Comment by northwestwitch** [comment]
I'll take a look at it!

**Comment by henrikstranneheim** [comment]
Here is what MIP 6.0 produces:
``
##INFO=<ID=dbNSFP_GERP___NR,Number=A,Type=Float,Description="Field 'GERP++_NR' from dbNSFP">
##INFO=<ID=dbNSFP_GERP___RS,Number=A,Type=Float,Description="Field 'GERP++_RS' from dbNSFP">
##INFO=<ID=dbNSFP_phastCons100way_vertebrate,Number=A,Type=Float,Description="Field 'phastCons100way_vertebrate' from dbNSFP">
##INFO=<ID=dbNSFP_phastCons46way_primate,Number=A,Type=Float,Description="Field 'phastCons46way_primate' from dbNSFP">
##INFO=<ID=dbNSFP_phyloP100way_vertebrate,Number=A,Type=Float,Description="Field 'phyloP100way_vertebrate' from dbNSFP">
##INFO=<ID=dbNSFP_phyloP46way_primate,Number=A,Type=Float,Description="Field 'phyloP46way_primate' from dbNSFP">
``

And then in a record:
``
dbNSFP_GERP___NR=4.58;dbNSFP_GERP___RS=4.58;dbNSFP_phastCons100way_vertebrate=1.000000;dbNSFP_phastCons46way_primate=0.122000;dbNSFP_phyloP100way_vertebrate=5.688000;dbNSFP_phyloP46way_primate=0.533000;
``

MIP 7.0 will only produce this:
``
##INFO=<ID=dbNSFP_GERP___NR,Number=A,Type=Float,Description="Field 'GERP++_NR' from dbNSFP">
##INFO=<ID=dbNSFP_GERP___RS,Number=A,Type=Float,Description="Field 'GERP++_RS' from dbNSFP">
##INFO=<ID=dbNSFP_phastCons100way_vertebrate,Number=A,Type=Float,Description="Field 'phastCons100way_vertebrate' from dbNSFP">
##INFO=<ID=dbNSFP_phyloP100way_vertebrate,Number=A,Type=Float,Description="Field 'phyloP100way_vertebrate' from dbNSFP">
``

**Comment by northwestwitch** [comment]
So far I understood when this happened. The last case with variants having conservation data I found was uploaded on date: 2017-10-05.

**Comment by northwestwitch** [comment]
Ok then 2 fields (phastCons46way_primate and phyloP46way_primate) are gone, but the other fields should still be there, right?

**Comment by northwestwitch** [comment]
The problem might not be in scout.
I'm comparing two analyses:

- https://scout.scilifelab.se/cust002/F0009924 (family decenttick), has conservation values.

- https://scout.scilifelab.se/cust002/F0004049-2 (family sharppiglet), doesn't have conservation values.

I dont have yet a full understanding of which VCF file get uploaded to scout, but checking in the bundles at files tagged as "vcf-snv-clinical" I see that the one showing conservation values has the relative annotations, namely **ID=GERP++_RS_prediction_term, ID=phyloP100way_vertebrate_prediction_term, ID=phastCons100way_vertebrate_prediction_term**. The other doesn't. 

These terms (correct me if I'm wrong) are added by genmod. Could it be that the issue is in genmod instead @moonso ??

**Comment by northwestwitch** [comment]
Or some MIP parameter for the execution of genmod that changed when upgrading to MIP 5?

**Comment by moonso** [comment]
Hi, those are not annotated by genmod

**Comment by henrikstranneheim** [comment]
The keys are all present in the snv/indel and SV for both research and clinical (sharppiglet). Something goes wrong when loading would be my guess. Most probably that the key names have changes and we have forget to update the scout dict handling this.

**Comment by henrikstranneheim** [comment]
Here: https://github.com/Clinical-Genomics/scout/blob/master/scout/parse/variant/conservation.py
Keys expected in VCF are: 
- GERP++_RS_prediction_term
- phastCons100way_vertebrate_prediction_term
- phyloP100way_vertebrate_prediction_term

and they are not any more. I think this was probably removed from vcfparer (in MIP) some time ago that produced a term instead of raw number for these keys. I will look into what happened.

**Comment by northwestwitch** [comment]
Are you sure that exactly these keys are present in sharppiglet ?

ID=GERP++_RS_prediction_term
ID=phyloP100way_vertebrate_prediction_term
ID=phastCons100way_vertebrate_prediction_term

Because these are the keys used by scout, see this file:
https://github.com/Clinical-Genomics/scout/blob/master/scout/parse/variant/conservation.py

By looking in the VCF file that I mentioned above I've seen the fields that you mentioned before (dbNSFP_GERP___NR, dbNSFP_GERP___RS, dbNSFP_phastCons100way_vertebrate, dbNSFP_phastCons46way_primate, dbNSFP_phyloP100way_vertebrate, dbNSFP_phyloP46way_primate) but not those named with the suffix _term

**Comment by henrikstranneheim** [comment]
One second ahead of you , YES!

**Comment by northwestwitch** [comment]
Exactly! :)
