### ISSUE TITLE
Odd amino acid level variants

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#113]
2015-03740fam 

SGCA stopgain c.675C>T(p.%3D)

Verkar vara en stopgain i ett NMD transkript; synonymous i alla användbara transkript. Vore bättre klassad i översikten som synonymous, vilket också är allt man ser i "transcript view". Men, hur eller hur så blev det lite fel på hur (p.=) visas. Gäller åtminstone Safari.

**Comment by henrikstranneheim** [comment]
This is because “=“ is not allowed in the vcf except for key value pairs. VEP recodes the “=" as the corresponding html symbol “%3D“. Scout was supposed to translate this back to “=“. @Robin: do you ono why this particular case was missed?
 
On 21 May 2015, at 09:35, Daniel Nilsson <notifications@github.com> wrote:

> 2015-03740fam
> 
> SGCA stopgain c.675C>T(p.%3D)
> 
> Verkar vara en stopgain i ett NMD transkript; synonymous i alla användbara transkript. Vore bättre klassad i översikten som synonymous, vilket också är allt man ser i "transcript view". Men, hur eller hur så blev det lite fel på hur (p.=) visas. Gäller åtminstone Safari.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by robinandeer** [comment]
That is some kind of coding (hex?) that I don't know is part of HTML...

Equal sign in HTML looks like: ``&#61;``

I'll look into how this can be handled in Python

**Comment by robinandeer** [comment]
@henrikstranneheim: can you point me to the relevant VEP documentation?

**Comment by henrikstranneheim** [comment]
http://dev.ensembl.narkive.com/NJ3n0U5g/ensembl-dev-invalid-vcf-output

On 21 May 2015, at 10:49, Robin Andeer <notifications@github.com> wrote:

> @henrikstranneheim: can you point me to the relevant VEP documentation?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by ingkebil** [comment]
For reference: %3D is URL encoding,  not HTML encoding. http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by henrikstranneheim** [comment]
True that!

On 21 May 2015, at 11:07, Kenny Billiau <notifications@github.com> wrote:

> For reference: %3D is URL encoding, not HTML encoding. http://www.w3schools.com/tags/ref_urlencode.asp
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna
