### ISSUE TITLE
weasyprint warnings when running scout

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/scout#1207]
Hi guys,

everytime we are running scout, we get following warnings:

```
/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/weasyprint/fonts.py:44: UserWarning: @font-face support needs Pango >= 1.38 warnings.warn('@font-face support needs Pango >= 1.38')

```

and 

```
/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/weasyprint/document.py:34: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html 'There are known rendering problems and missing features with '```

**Comment by northwestwitch** [comment]
Hi, I know. It's complaining a lot but it works as it should. I'll take a look at it as soon as I have some time!

**Comment by northwestwitch** [comment]
I've looked into this. It probably has to do to an outdated version of  Pango installed on the server.  I can't recreate this on my local computer so I assume my lib is updated enough. I'll check which one it is so we can open an issue on servers repo.

**Comment by northwestwitch** [comment]
I'm closing this as there is not way to fix this problem unless we update the version of weasyprint in use, which we can't because otherwise we get a visualization problem (conflict with Bootstrap). What we should do is rewriting completely the general report to remove all bootstrap elements and the wither update weasyprint or (better) use a completely different pdf rendering library.
