### ISSUE TITLE
BAM files missing

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1216]
https://scout.scilifelab.se/cust002/F0029506/bed9168bd03586552d2311bcd6557b4b

Also seen this an another case I analyzed before this one...

**Comment by dnil** [comment]
Hm, I thought these were resolved; ping @ingkebil?

**Comment by ingkebil** [comment]
Hi guys,

sorry about this. Our new analysis cluster was down for maintenance this afternoon. Bringing it back up did not bring back the mount to the webserver. I've relayed the question to IT.

Furthermore, I'm drafting a document with steps to take when servers are rebooted so that we can be more proactive when it comes to these problems.

If all goes well, the BAM files should be back by tomorrow morning,

wkr,
Kenny

**Comment by dnil** [comment]
Looks all good now; thanks @ingkebil and IT!
