### ISSUE TITLE
Adapt dismiss options to cancer variants

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1244]
Hi @hassanfa , this one is easy as long as you can provide what alternatives to keep/remove/add. Please update in this issue

**Comment by moonso** [comment]
See #1245 regarding variant templates

**Comment by northwestwitch** [comment]
@hassanfa is superbusy at the moment, so you could take this one @mayabrandi !

**Comment by hassanfa** [comment]
@mayabrandi The following can be added to cancer variants:

- Possible Germline. Description: Variant is possibly a germline event. Note: Evidence for this is based on the reviewer's/clinician's call. There is no tag for this in VCF INFO field.
- Low count normal. Description: If normal sample exists, variant has too few reads in normal sample 'AD'
- Low count tumor. Description: Variant has too few reads in tumor sample. 'AD'

@dnil Any more suggestion from your side or changes to above?

**Comment by dnil** [comment]
- Its good to be able to flag "Possible germline". The GT fields would give decent support for that and is what I would put on the general report with that. I'm not sure I agree its a "dismiss", as that usually is the start of an investigation on the hereditary side, but lets have it as such for now.

Otherwise I think I would be fine with the present ones, possibly tweaking the descriptions a bit for cancer. E.g. if I were to dismiss cancer variants, I might want say the aberration doesn't fit the expected mode of action of the gene, like an early stop gain in an oncogene. With the current options I would probably go with "Unstudied variation type". The label and description don't fit perfectly but it gets the gist.

**Comment by hassanfa** [comment]
Of course we should aim for keeping current tags. Reason: Some of them are relevant for cancer and rare disease. 

'Possible germline' is a tag that I'd argue we might need for "just in case" situations. If a tumor sample has a matching normal, the VCF will have a flag "Possible_germline" in `INFO` field. This is for those cases that might not have a matching normal sample. Also not only GT field, but tumor_VAF/normal_VAF ratio will give us a good clue about the status of somatic variant. And if a high AF variant is in a `GAIN` region we should also tag it as such (again, this should be tagged in VCF so we can have filters adopt for them).

**Comment by northwestwitch** [comment]
This was done in #1535 for cancer snvs. When the cancer SV page will be in place then we'll have to extend also to this type of variants. I'm keeping this open for now so we know that the task is not complete yet.

**Comment by dnil** [comment]
I believe this was done also for the cancer SVs, right? Please reopen if you miss something!
