### ISSUE TITLE
links to str variants lead to variant page, not str-variant page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1282]
Tried to open an str variant and it's treated as a variant. When you fix the link to the right page 
(url_for('variants.str_variant', institute_id=institute._id, case_name=case.display_name,
                      variant_id=variant._id))
you get an error

**Comment by dnil** [comment]
Linking to the variant page isn't too bad; it actually gets you somewhere where you can get an alignment. But lets add a specific variant page as well, where there are only STR-relevant items left (gene level info w OMIM, variant, bam view, ...) and the STR specific info shown.

Similarly, the "next page" button on the str-variants page, if it is ever shown, takes you to the "variants" view, rather than STR-variants. Fixing that should be part of the same PR. Not so urgent, since we don't load these yet, but I'm on it after tests for #1281.

**Comment by dnil** [comment]
So two things here:
- [ ] "Next page" bugfix - thats a bug; I should have remembered that when I was anyway tinkering with the page, but I rarely open trios.
- [ ] A STR specific variant page. I would actually argue against it in favour of making the  regular variant page work ok for STRs. Instead I would like to propose a gene / loci level view where all variants in the same loci for the whole case would be presented, together with the customary OMIM links etc.

There is also a perhaps more pressing third, regarding ranking / sorting, but I would guess that is being thought about under the genMod umbrella. Lets discuss that one of these days @moonso!

**Comment by dnil** [comment]
I'm closing this for now: the next page is fixed in #1364 and most of the loci level view would be covered in solving #1180. If we still feel the content on the variant page is not filled up well enough, with #1273 I'd say we could disable it, as all relevant info we currently have loaded is shown already on the str-variants page.
