### ISSUE TITLE
Keep Sanger evaluation after rerun

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1326]
Atm the Sanger order and status disappears after rerun

**Comment by northwestwitch** [comment]
@moonso doesn't look super easy as you labeled to me.. 
Anyway, once you rerun you delete all variants so the sanger validated and ordered should be saved before doing so. And then, after the upload of the new variants, these should be compared with those saved before. I would do it in this way, unless there is an easier way. Ideas?

**Comment by moonso** [comment]
Oh ok! Sorry about that. Perhaps we should turn them into events then so that they are kept even if variants are deleted?

**Comment by northwestwitch** [comment]
> Oh ok! Sorry about that. Perhaps we should turn them into events then so that they are kept even if variants are deleted?

No worries! I would use the events to collect all the sanger ordered (readapting a function that already exists) . Plus I'd collect the validated (easier). Then I'd turn them into variants (because so far I have only ids) and save them into an object.

After re-uploading the variants I'd compare with the ones saved in the object above. At least this is how I'm doing it now.. Let's see!
