### ISSUE TITLE
Delivery report missing

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1356]
I noticed that the button for "Delivery report" is missing after update of Scout. Is it hidden somewhere?

**Comment by northwestwitch** [comment]
> ng after update of Scout. Is it hidden somewher

**Comment by 1ctw** [comment]
19200 as example

**Comment by dnil** [comment]
Most new ones do have it, but perhaps sth with reanalysed cases? I saw one w/o:
https://scout.scilifelab.se/cust002/F0004963-2

**Comment by northwestwitch** [comment]
Checking in the database: delivery report is missing at that level. It's not related to the new release of Scout, but not less warning.

![image](https://user-images.githubusercontent.com/28093618/66041862-3bb36100-e51b-11e9-93f9-e2ea216895ae.png)

**Comment by northwestwitch** [comment]
@1ctw delivery report is likely there but the button doesn't show, see here: https://scout.scilifelab.se/cust003/19200/delivery-report

**Comment by northwestwitch** [comment]
I've just spoken with production team and they say that if it's recent cases (last few days) then it likely that the report has not yet been delivered to LIMS and that's why you don't see it. 
They say you should check again after you get your ticket answered. 

I'm closing this for now but please reopen if needed!
