### ISSUE TITLE
Rankscore

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1366]
Please comment / check the rank score for this variant when it comes to clinical significane.
Genmod?

https://scout.scilifelab.se/cust002/F0030188/e68575e5369dfad5ed1df323e7b11fd4

**Comment by moonso** [comment]
Hi @47KW , yes you are right, something looks strange here. Do you @henrikstranneheim have any idea how this variant can get a score of 16 only for the clinical_significance category? It would be informative to look at the raw VCF variant perhaps

**Comment by 47KW** [comment]
https://scout.scilifelab.se/cust002/F0028473/a11d1101eb23faa7691a1744eca80c9a
this case;variant also

**Comment by 47KW** [comment]
...and the opposite, low Clin Signifacne ranks core for variant with multiple ClinVar pathogen/likely path.
https://scout.scilifelab.se/cust002/F0031170/5c6827257a2d42d1df162053e7b52b45

**Comment by henrikstranneheim** [comment]
The reason seems to be (@moonso correct me if I am wrong I just glanced the code) that genmod makes all string matches on lower case and and probably a greedy regexp, which means that e.g. 'Pathogenic' will get a match on the string: 'Conflicting_interpretations_of_**pathogenic**ity'. This is the situation for this variant as it gets 15 from the CLNSIG. 

Also Clinvar has updated the terms and expanded them quite a bit so this approach needs to change for this to work I think.

**Comment by moonso** [comment]
Aha then this is a genmod bug... not good. @henrikstranneheim how come it gets +15 for that? Isn't that I bit out of bounds?

**Comment by henrikstranneheim** [comment]
It was decided on a Scout user meeting a while back to make sure that all 'pathogenic' and 'likely_pathogenic' are loaded by Scout and not missed, when mainly the frequency is high. this skewes the rank model quite a bit. I am not thrilled by this and that is why we should work on the solution we talked about in the milestone meeting to make Scout load these. Then I can lower this again to a more sane level.

**Comment by moonso** [comment]
Ok. How quickly will you be able to remove clinvar from the rank model?

**Comment by henrikstranneheim** [comment]
That is easy, but we have to wait until you Scout can load clinvar independent of MIP

**Comment by dnil** [comment]
And just to keep track, the dev version of scout can do that since a couple of weeks: #1379.
