### ISSUE TITLE
gnomAD frequencies

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1368]
The link to gnomAD is ....well.....check it
https://scout.scilifelab.se/cust002/F0028473/4b644a3b3b5892bc70a68d570e1c9dd0

**Comment by moonso** [comment]
Hi @47KW , nice find. I guess this is wrong since it is a multi allelic variant. This is a typical corner case that we need to look closer to and modify stuff in the analysis pipeline (MIP). @henrikstranneheim , could you have a look at this and see if it is VEP who can not handle the situation?

## Problem 
In scout it looks like this variant is unique, however when looking at the nomad homepage it is a fairly common variant in a multi allelic site.

**Comment by henrikstranneheim** [comment]
Hi, it is unclear why this particular variant did not get a annotation in the vcf from GNOMAD. All looks correct in the analysis both are normalized and decomposed in before the annotation process, which is done using vcfanno. I do not know why vcfanno missed this one.

**Comment by henrikstranneheim** [comment]
Ok, the production version of gnomad had not been normalized and decomposed. I have fixed this in the production setting as of now. I will write a deviation.

**Comment by moonso** [comment]
Great @henrikstranneheim ! So new analysis will not have this problem
