### ISSUE TITLE
Weird variant lines in variants template

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1416]
Look at the rank col!

![image](https://user-images.githubusercontent.com/28093618/67369963-36758f00-f57a-11e9-9e45-5826fd430b07.png)

**Comment by dnil** [comment]
Hm, the present suggestion gives another unsatisfying alignment within the cell. Kinda clunky when it overflows as well.

<img width="1576" alt="Screenshot 2019-10-23 at 15 18 52" src="https://user-images.githubusercontent.com/758570/67397221-2a54f600-f5a9-11e9-9ffc-fedc73b78cab.png">

I suppose that could be amended by changing the style width. I would like to try to move to a more complete d-flex layout, either by explicitly enabling it for all rows. 
Let me give you a suggestion.

Also, we appear get the ACMG badge twice due to a flaw in the logic for same-case presentations. . Feel free to think about that one: not sure the problem is new, but just in case. X-) I'll start with the rows.

**Comment by northwestwitch** [comment]
It might be fixed in another way but having d-flex justify-content-between align-items-center in that td is definitely an intended copy and paste error, because the other td from the same table look different. You can increase the size whichever cell but if you have enough you will see the newline in rank because of this wrong code
