### ISSUE TITLE
OMIM link

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1557]
Hello,
sorry if already known issue, but.....
the link between gene and OMIM seems to lack certain phenotype.
example shows GRN that lacks FTD (Frontotemporal lobar degeneration with ubiquitin-positive inclusions) which is rather important.....
https://scout.scilifelab.se/cust002/F0032561/baf04eeea08df797a7e7907d1e44c3f6

**Comment by dnil** [comment]
Yep, something is currently wrong with that particular display. The correct data is in the db, as seen e g on the gene page:
<img width="1659" alt="Screenshot 2019-11-28 at 10 56 15" src="https://user-images.githubusercontent.com/758570/69796190-dbb10200-11cd-11ea-869f-0dccb22c7fe7.png">

**Comment by dnil** [comment]
..and the HPO to gene map seems intact. Good. We'll look into it - thank you for the report!

**Comment by dnil** [comment]
Actually *no* diseases show up on the variants - tooltip version of that list, although it should be recent enough: 
<img width="167" alt="Screenshot 2019-11-28 at 11 02 09" src="https://user-images.githubusercontent.com/758570/69796684-b8d31d80-11ce-11ea-943d-a39a187fc442.png">

**Comment by dnil** [comment]
This is either just a case of lagging local updates to the disease term collection, or possibly an error with parsing genemap2 from OMIM - they did change some things lately..  At least the gene in question is missing from the db. I'll test updating the collection locally and see if the corresponding phenotype is parsed correctly.

**Comment by dnil** [comment]
Local gene/disease updates are not operational. It seems there are some issues over at ENSMBL at the moment. They were down earlier today, and now appear intermittent. We will get back to you as soon as the smoke clears over there!

**Comment by dnil** [comment]
<img width="865" alt="Screenshot 2019-11-28 at 13 30 15" src="https://user-images.githubusercontent.com/758570/69806508-50db0200-11e3-11ea-83f7-c848a4a81370.png">

Still no luck..

**Comment by moonso** [comment]
Wow this issue is a bit weird , there are two phenotypes with the same OMIM number. I we look at the omim page for [GRN](https://www.omim.org/entry/138945) we will see that in the list of phenotypes there are two ("Aphasia, primary progressive", "Frontotemporal lobar degeneration with ubiquitin-positive inclusions") with the same omim number:

![Skärmavbild 2020-01-29 kl  15 17 36](https://user-images.githubusercontent.com/405278/73364248-82874c80-42aa-11ea-9b6b-d921a370836a.png)

Looks like it works when we display that on the gene page like you show in your link @dnil but something goes wrong when we display it on the variant page. This should be fairly easy to fix then.
