### ISSUE TITLE
Show arbitrary data from VCF on variant view

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#1578]
A feature request that I can implement myself, but I'd like your feedback first.

The most common request I get from our users is to add some random information to the variant view (for example if the variant exists in some database or overlaps something etc). At the moment it requires that I add parsing/loading, modify variant.html and deploy a new version of scout. And if it is not relevant for others I don't want to push it upstream, so I have to maintain a local branch with all our modifications.

Wouldn't it be nice to be able to add custom fields in the vcf that are loaded and displayed in a simple table om the variant page.

For example an INFO-field like this:

```
SCOUTCUSTOM=key1|value1,key2|value2
```

Gets parsed and loaded into the variant document like this:

```
custom: {
key1: 'value1',
key2: 'value2'
}
```

And then of course display the keys and values in a table in variant.html. For simplicity all values could be treated as strings.

Any comments? Is it a bad idea? It would simplify my job significantly...

**Comment by dnil** [comment]
We have indeed discussed that before, last time partially at the beginning of this semester. But we have so far decided against it. I was initially very keen on having something like that too, or eventually a full blown definition yaml specifying whet values should be loaded how and shown where on the layout. The main argument against is probably that: in order to specify where to display the info above you have to write a fairly complex definition, which is not so dissimilar to just typing it into the code. 

Another argument is also something you touch upon: in general we find it is useful for all to have features added and live through some design conflicts to end up with something that is sharper for all. In the long term that saves effort for all. We always welcome PRs, so go ahead if you have a clear idea of how to show this, but I think we would benefit more from additional specific PRa ones rather than the general one!

**Comment by bjhall** [comment]
Thanks for your comments! I mostly agree, and I think most things should be added "properly". But for more obscure things I think somthing like this could be useful. I'm planning on keeping it very simple.

I will make an attempt at implementing this, since I think I will need it anyway. I have very limited time for Scout developement and this would save me a lot of time.

I'll make a pull request when I'm done, which you are welcome to decline if you want to! :)

**Comment by moonso** [comment]
Closed by https://github.com/Clinical-Genomics/scout/pull/1584
