### ISSUE TITLE
client ssl certificates?

### ISSUE THREAD

**Issue by parlar** [Clinical-Genomics/scout#1592]
Admittedly, my understanding of this is quite limited but for https downloads to work in our organization, locally issued certificates must be in place. I believe that many corporate environments use client ssl certificates this way.

However, this creates a problem with the use of urllib.request as currently implemented in scout as local certificates are not set. 

There are a couple of ways around this: 

1. Since urllib.request depends on OpenSSL, setting the ```SSL_CERT_FILE``` env variable solves the issue. However, I read somewhere that this is discouraged and may not work in the future.

2. Another way would be to use the ```cafile``` argument when urllib.request is called, but that requires implemention. 

If the latter solution is preferred, where should the cafile setting go? I don't yet have a good grasp of the scout code base. Is there a file somewhere where settings like this are normally put?

**Comment by northwestwitch** [comment]
I'm no certificates expert but I think it that if it works for you it would be easier to set the env variable for now. Instead of changing the code to take care of certificates I'd rather re-introduce the option to provide an already downloaded file instead..

**Comment by dnil** [comment]
Hi again! Great that you are working on this!

From the top of my head that would in routine use be the task of the web server, rather than the web app / flask? As in `gunicorn --certfile=server.crt` in [docs - server - Production](https://github.com/Clinical-Genomics/scout/blob/master/docs/admin-guide/server.md).
The only time I remember we would use a cert directly on the app would be for testing with the tiny  built-in flask web-server?

**Comment by dnil** [comment]
Ah, sry, for downloads, not inbound SSL. I don't think I have to state that this is not my area of expertise either. 😉 
I suppose I have not yet come across an env that doesn't have CA set up by default, but aren't they all different! Is this some kind of policy, or would it be possible to configure OpenSSL on setup instead so that it does have access to acceptable CA-files?

In general, system wide settings normally go in the `server/config.py`.

**Comment by northwestwitch** [comment]
Since setting up an environmental variable works I'm closing the issue. We can re-open it in the future if this will be no longer an option!

**Comment by parlar** [comment]
Great!
