### ISSUE TITLE
Rank model for cancer - also display on scout pages..

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#1620]
From https://github.com/Clinical-Genomics/scout/issues/1460

**Comment by moonso** [comment]
What do you say @hassanfa ?

**Comment by hassanfa** [comment]
I don't see why we shouldn't use a ranking. The only comment I'm concerned about is that, (I'm quoting here) "it might down prioritize some variants that are interesting".

But I'll make a very basic one, and see where we go from there. Should I move this to BALSAMIC as well? Since it is going to be part of workflow.

**Comment by moonso** [comment]
Sounds perfect, closing
