### ISSUE TITLE
Add fetal tissue among other types of tissue types used for collecting genetic material

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1640]
Introduce it also in order portal and cg?

**Comment by dnil** [comment]
@KickiLagerstedt "CVB", "Other fetal tissue" - do we need an "Amniocentesis" or such?

**Comment by KickiLagerstedt** [comment]
If ”CVB” is in the list I think we should also add ”AC” as well as ”Fetal tissue”

// Kicki


Skickat från min iPhone

22 jan. 2020 kl. 17:35 skrev Daniel Nilsson <notifications@github.com<mailto:notifications@github.com>>:


@KickiLagerstedt<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKickiLagerstedt&data=02%7C01%7Ckristina.lagerstedt%40ki.se%7C2637e17c68e242c12e1508d79f5919cc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637153077347636512&sdata=7UJmTOlyeYp%2F7WQFI9NXBQ9waNeopdOyiPh5WfYnj%2F8%3D&reserved=0> "CVB", "Other fetal tissue" - do we need an "Amniocentesis" or such?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Fscout%2Fissues%2F1640%3Femail_source%3Dnotifications%26email_token%3DAECYPF5O2VS6KMDAVUG4SE3Q7BYVHA5CNFSM4KKC2FJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJUHWWY%23issuecomment-577272667&data=02%7C01%7Ckristina.lagerstedt%40ki.se%7C2637e17c68e242c12e1508d79f5919cc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637153077347636512&sdata=UoUk2c71B6jVWUnCXqEIJ57GgWk%2BVm3T35gLui4oYNc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAECYPF27MAFWQSG4YMG6IEDQ7BYVHANCNFSM4KKC2FJQ&data=02%7C01%7Ckristina.lagerstedt%40ki.se%7C2637e17c68e242c12e1508d79f5919cc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637153077347646504&sdata=dhEYMc%2F2T1gd2iCU8U2f666ZMEROoBj48AZfoVMc3QI%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by dnil** [comment]
Thanks; let’s add all three. I prefer “other fetal tissue” over “fetal tissue” given the other options, but that is just semantics!

**Comment by moonso** [comment]
I added "AC" and "CVB" now. Is it ok to use the abreviations or better to spell it out?

![Skärmavbild 2020-02-05 kl  09 33 41](https://user-images.githubusercontent.com/405278/73824550-a1ca3080-47fa-11ea-8468-7769b0d2b20e.png)
