### ISSUE TITLE
panel edit botton not working

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1665]
![bild](https://user-images.githubusercontent.com/12525201/73360937-36390e00-42a4-11ea-81d1-9c890b1da1e1.png)
 

I can not click in the edit, neither in the add ....:(

A question:
how do I remove an uploaded gene that i do not want to submitt any longer?

**Comment by northwestwitch** [comment]
I've fixed that problem in #1661. When we update scout with this change it will work again. Sorry for the inconvenience!

**Comment by northwestwitch** [comment]
Confirmed. I'm going to fix it together with the other panel issue. Thanks for reporting it!

**Comment by northwestwitch** [comment]
Wait, but you mean those "edit", "delete" and "add" badges on the right of the genes, in pending changes?? Because these are not buttons, they're just informative of the action that is going to happen regarding that specific gene in the updated panel.

The buttons to edit/delete a gene in a panel are in the lines of the genes already in the panel, down.

**Comment by dnil** [comment]
Quite right, just labels! I think we understand the issue now, right @4WGH?
The situation is rather frustrating for a user. I'd suggest adding a button for clearing pending changes to the Pending changes section!
