### ISSUE TITLE
panel editing gene add instead of overwrite

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1673]
I've edite the inheritance model.

Text has been added to the present one that has not been remove.
see panel IEm v15, gene LHX4
inheritance is not "AR,AD,AR"

another bug :)

**Comment by 4WGH** [comment]
same in gene MMACHC 
inheritance should be "AR,DR"

**Comment by 4WGH** [comment]
anothe bug!
 if I edit a gene and I do not choose again the disease transcrip the information is lost in the update.

**Comment by 4WGH** [comment]
another bud
in the genes where I've edited the entry version in the inheritence a "," has been added ( in addition to the lost of the disease trancript information) see panel IEM v15
genes PARS2 and PGM1 for exemples.......

**Comment by dnil** [comment]
Hi again -  you've been busy! Thank you! 😊 

It is easier to start from precise reports where you have made sure we can reproduce problems, and perhaps included screenshots to make it super clear to us what view you are looking, and what results you are seeing. But, making a report is much better than just ignoring it, so don't worry too much. 😺 

- *Disease transcript info lost in update.* The current edit view requires the user to re-affirm the disease transcript, otherwise it gets cleared on update of other values. I agree, that is not obvious or practical, and we should be able to fix it easily! :+1:

- As for the extra comma, that is not so pretty. 😊 We should introduce a check for entries with only whitespace. Thank you!

- In the Inheritance model column you will see a list containing both the drop down selectable inheritance model - supposedly one of 
```
(    ('AD', 'Autosomal Dominant'),
    ('AR', 'Autosomal recessive'),
    ('XL', 'X Linked'),
    ('XD', 'X Linked Dominant'),
    ('XR', 'X Linked Recessive'),
    ('NA', 'not available'),
    ('AD (imprinting)', 'Autosomal Dominant (imprinting)'),
    ('digenic', 'Digenic'),
    ('AEI', 'Allelic expression imbalance'),
    ('other', 'Other')
)
``` 
plus a free text Other custom inheritance model to complement a selected "Other" among your models. The easiest explanation would be that you both checked AR and typed it again in the Other fields?

- Completely beside the point, but just for my learning: what do you mean by "DR" inheritance, that is not captured by eg "Digenic"?

**Comment by 4WGH** [comment]
DR = digenic.  it is the text used by OMIM, yes.
I had forgotten we had chooosen too write "digenic"

I'll try to see what we did before and be consequent.
Once the edit page works properly :)

in the inheritance model there in no drop dowm menu, it is our personal a nnotation of inheritance t hat we manually fill in.  :)
the problem is that the actual text does not appear in the edit windor, and what I write in there is add not replaced :)

**Comment by dnil** [comment]
..and if you open the drop-down for Inheritance model, you will find:
<img width="1394" alt="Screenshot 2020-02-07 at 10 49 47" src="https://user-images.githubusercontent.com/758570/74019285-ad9f2980-4997-11ea-978a-1039c3762cc9.png">
The Inheritance model column on the panels page then correctly shows first the check marked AR followed by the manually added inheritance mode "AD, AR"?

**Comment by dnil** [comment]
And thanks for the abbreviation for digenic! I didn't recognise it!

**Comment by 4WGH** [comment]
Just to be clear,
 the inheritance model I talk about is the "Other inheritance model"

I think we should NOT be able to edit the OMIM inbheritance model , that come automatically from OMIM in scout :)
So the option can be removed for safety.

For personal inheritance annotation there is the "Other inheritance model"

**Comment by northwestwitch** [comment]
Hi @4WGH, working on this now. To be clear I understood what needs to be done:

- [ ] There is a problem with disease transcript which is not preselected on gene edit and if you don't updated it manually it gets lost. This is easy to fix, I'll work on this.
- [ ] Extra comma is also easy to fix.


Regarding the inheritance:

You say there is a bug with updating the `Other inheritance model`. If I look at the gene you mentioned (panel IEM v15, gene LHX4) you say that what is displayed is wrong:

This is what is displayed in the panel page (AR, AD, AR):
![image](https://user-images.githubusercontent.com/28093618/74635113-9adddf00-5165-11ea-80ee-4db3caea86f5.png)

And this is at the gene level (AR, AD, AR):
![image](https://user-images.githubusercontent.com/28093618/74635290-00ca6680-5166-11ea-8556-717f7498f9f7.png) 

As also @dnil pointed out I think this is the intended behavior, since the panel page displays all types of inheritance models provided for the gene (from the dropdown + the manual ones).

**Comment by northwestwitch** [comment]
I've just had a call with @4WGH and we agreed on a fix based on the concept that **Inheritance Models and Other inheritance models** are the same field : Inheritance models. The first provides pre-selected standard choices and the second allows the user to enter free text. To make it more clear I'll rename the labels of the 2 fields into something more user-friendly.

**Comment by dnil** [comment]
Sounds like a plan! 😄
