### ISSUE TITLE
Activity logg stating not tru action - bug?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1716]
Looking today  (2020-02017) into fam19118
in the list of activity it is stated
" Michela Barbaro ordered sanger sequencing for 18_53298578_C_T_clinical at 2020-02-16 "

well NOT TRUE!!!!

It did not work yesterday. I didn't enter scour yesterday. 
A bug?
The variant in question had a Sager ordered previuosly that has been deleted afteward. Could this be involved in the  bug?

**Comment by northwestwitch** [comment]
What about the sanger email, did you get that as well?

**Comment by dnil** [comment]
Good question! It appears this case got a rerun rather recently? Possibly something about the re-upload & state change that doesn't play well with the Sanger updates @northwestwitch.

**Comment by 4WGH** [comment]
no e-mail about Sanger

**Comment by 4WGH** [comment]
same problemn spotted in fam 131 after re-run
again affecting Sanger order that has been deleted

**Comment by dnil** [comment]
Not sure yet wether this is a local issue with the re-upload handling, or a bug, but let's treat it like a bug first and see if we can find it!

**Comment by northwestwitch** [comment]
Checking this and as you mentioned @dnil this is not really a bug. 
Upon rerun, all the Sanger pending variants are removed and replaced by the variants from the new rerun. If among these "new" variants there is one which previously had a Sanger pending, then a new Sanger sequencing is ordered for it, so the info is not lost. Since @4WGH ordered the Sanger for the old variant, the new one is also ordered by her by default. 

So son't worry @4WGH all is as it should. I'm closing the bug now.
