### ISSUE TITLE
pymongo version incompatible between scout and loqusdb

### ISSUE THREAD

**Issue by ninanorgren** [Clinical-Genomics/scout#1754]
It seems the requirements for Scout is pymongo<3.7, but if you want to use it with loqusdb you cannot because that installs pymongo 3.7.1.

**Comment by northwestwitch** [comment]
Hi @nina, we have made changes on how Scout interacts with loqusdb recently. Or it could simply be that you are not using the most updated version of loqus (this one I guess: https://github.com/moonso/loqusdb)
@moonso could you help?

**Comment by moonso** [comment]
Yes, to avoid dependency problems like this we have decoupled loqusdb from scout. The idea is to run locusdb in its own environment so that none of its dependencies will clash. We solve this by specifying the loqus executable in the config. It is described [here](http://www.clinicalgenomics.se/scout/admin-guide/loqusdb_integration/). Just tell is you need more help!

**Comment by ninanorgren** [comment]
Ah, okay then it was by design. It wasn't super obvious from the documentation that it needs to be run in a separate environment. Or maybe I just didn't find the right place. Thanks for the help

**Comment by moonso** [comment]
Ok good, we can try to make that more clear
