### ISSUE TITLE
Missmatch Scout vs IGV/UCSC

### ISSUE THREAD

**Issue by MaribelAranda** [Clinical-Genomics/scout#1788]
Hi,
We found a variant in position 3:184056082 that Scout says falls in the gene EIF2B5. However, when looking at the same position in the IGV link and in UCSC, seems that the same position is mapped to FAM131A gene (using hg19). The compounds do not seem to match to EIF2B5 either. Different cases present the same issue. We wonder if this comes from Scout or even before, in the alignment step. Should we trust the gene name or the position?
Thanks.
Maribel

**Comment by dnil** [comment]
Without going into details, I would guess the issue derives from the ENSEBML gene ENSG00000145191?

<img width="1084" alt="Screenshot 2020-03-10 at 16 28 02" src="https://user-images.githubusercontent.com/758570/76328940-376e4980-62ec-11ea-984d-921a9c58021a.png">

The annotation stage of MIP relies primarily on the ENSEMBL gene definitions. One has to make a choice, and this is a very comprehensive, actively supported and local one. Since RefSeq is more entrenched in the clinical world, we do attempt to provide that as well, but the translation to RefSeq is somewhat complicated. For most of the "common" clinical genes, this is no longer a problem, but somewhat outside the beaten track this becomes an issue. Many of these are fixed in hg38, so it is a little hard to complain to EMBL about them, but one could!

To wrap up, I think you can in general trust both the position to the limits of genome assembly, and gene name to the limits of gene models. Hope this helps! @moonso is otherwise the local transcript expert if you want more details!

I will close this issue for now, but feel free to reopen if you want to pursue it further!
