### ISSUE TITLE
"GATK Pass" not visible in Scout

### ISSUE THREAD

**Issue by maripe1** [Clinical-Genomics/scout#1792]
Below the coverage data for an SNV/indel i Scout, we could usually see "GATK Pass" etc. In the GMCK-RD set rules for reporting a variant without having to verify it with a secondary method, one of the criterias are that we have to see GATK Pass i Scout. Hence, we need you to add it to the Scout view again on the variant view. Thanks!!

**Comment by dnil** [comment]
Thank you! We’ll check: it is not impossible this flag has also changed with the introduction of MIP8.

**Comment by henrikstranneheim** [comment]
This used to be triggered by the vcf INFO key`set=` annotated by gatk combinevariants. However, since we have turned off bcftools_mpileup the gatk combinevariants program does not process the snv/indel data anymore and the does not add the vcf INFO field. 

All variants in the snv/indel view for rare disease are called by GATK using MIP 8 (no exceptions), even though Scout does not show a badge of it.

We have to find a way to annotate the caller for each variant again

**Comment by dnil** [comment]
Perhaps the natural fallback would be to always have INFO.set=GATK, since it may change to set=GATK-whatnot with just a configuration alteration? Scout also currently recognises the INFO.FOUND_IN that could be set to GATK for all PASS variants. 

Given static versions of the callers, we could parse the VCF header to determine what callers were used, and if only one, set the caller status according to the FILTER column, but this is somewhat error prone and version sensitive.

I think I'll just try a PR to let Scout assume that GATK is the default caller if there is no INFO.set= or INFO.FOUND_IN=, and update Scout GATK filter status according to the FILTER column. This will require reloading variants again to update the MIP8 cases.

**Comment by dnil** [comment]
@maripe1 @KickiLagerstedt Did we include the intermediate GATK quality levels, like `VQSRTrancheSNP99.99to100.00` in the guidlines, or just `PASS` and `FILTERED`?

**Comment by ielvers** [comment]
@dnil is it possible to check GATK status for individual variants? We have a priority case where we'd like to answer out the variants based on the guidelines mentioned by maripe1 above (without waiting for Sanger) but we'd need to know GATK status on two variants right away for that. 
It's variants
https://scout.scilifelab.se/cust003/20042/f24b0ff57031139efaa693034316605b
https://scout.scilifelab.se/cust003/20042/fba82cce5fdf7e753cd8626d19ab33bf

Is there any way we can find this information while the issue is being fixed?

Thank you! :)
- Ingegerd

**Comment by dnil** [comment]
Yes: in general, send a ticket to Clinical genomics, asking them to provide you with the VCF file on Caesar - or the calls for these particular variants. Or ask one of your neighbours such as @henrikstranneheim, @moonso or me via some slightly less public forum. For two cases, I could look in a bit, I just need to finish something else first.. 😊

**Comment by henrikstranneheim** [comment]
@ielvers If the delivery report says MIP version > 8 - then GATK for snv/indels is the only caller.

![Screenshot 2020-03-16 at 16 21 15](https://user-images.githubusercontent.com/584738/76773064-2cab2d00-67a2-11ea-8f25-330b19234010.png)

There is no need to check the data.

**Comment by dnil** [comment]
PASS status?

**Comment by henrikstranneheim** [comment]
aha, ok the variant quality call is part of the criteria.

This is more hidden but since we have only one caller if you have "3" in the Rank results table for variant call quality filter:
![Screenshot 2020-03-16 at 16 27 47](https://user-images.githubusercontent.com/584738/76773631-1487dd80-67a3-11ea-95ac-ceebfb5349e1.png)

Then the variant is "PASS" according to GATK. 

We will try to fix something more explicit for you in the near future, but at least with these 2 criteria:
1. MIP version > 8
2. variant call quality filter = 3

You can go ahead.

**Comment by ielvers** [comment]
@dnil @henrikstranneheim THANK YOU! That was super helpful!

**Comment by dnil** [comment]
@maripe1 and @ielvers: this is now fixed on the development track, and will go into production with the next release. Since HS showed us a nice workaround, we think we should not reload the first MIP8 cases again over this. Holler if you want an exception to any particular cases. Thank you again for reporting when you find things out of the ordinary!
