### ISSUE TITLE
Clin VAr submission- page overview

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1837]
wish to see the gen symbol on the overview, to be able to easly manange the variants

![bild](https://user-images.githubusercontent.com/12525201/77524230-483fc300-6e87-11ea-9e11-b84faeb383ab.png)

**Comment by northwestwitch** [comment]
Hi @4WGH, I can add gene gene info to the variant data table (top table). I will not add the gene to the case data table (the one on the bottom) because that table is about case individuals and gene info is not available at that level (only for variant data). 
You can always associate a certain case data line to a variant using the "Variant ID" field.
