### ISSUE TITLE
Clin Var submission

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1849]
![bild](https://user-images.githubusercontent.com/12525201/78218505-2f09c880-74be-11ea-976f-c37f776b6940.png)

can the disease name be written next to the OMIM number?

**Comment by northwestwitch** [comment]
Hi! I'll try to go through your fresh list of issue from today!  :)
First thing to keep in mind:
- clinVar Scout interface is just a tool to help you in the process of submitting to clinVar and makes most of the work in preparing those excel file, but you **always** need to open those files, check and eventually fix the fields that (for whichever reason) might not be correct**

This could be done one day, but it's not a priority at the moment, also because the omim link provided is a link to the official omim page that will open in a new window with all the info required.

I'm closing this now. We could re-open if more users feel like this is a necessary feature.

**Comment by 4WGH** [comment]
this wish was from a dr. we can not cross check each thing at several level. as you shoe the HPO you can show the OMIM :)

**Comment by dnil** [comment]
Right, we understand. Try to argue with them and explain how they can click on the link, or look at the case page from another window to see the name of the diagnosis. Or search for it in the diagnosis page. When the diagnosis was made, they surely saw it? Everything takes time, in dev and prod, and every feature will go through several people changing, reading code and risking that new errors arise. It is sure not impossible, but we need to prioritise.
