### ISSUE TITLE
ClinVAr - variation identifier collection

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1852]
in case 19068
the variation identifer was not pre filled. we could find the rs number through the gnomAd link.
Bug or old case issue?

![bild](https://user-images.githubusercontent.com/12525201/78221765-43e95a80-74c4-11ea-8ca4-b93b9da78bde.png)

**Comment by northwestwitch** [comment]
It was probably not parsed at the moment the variant was loaded into scout, for some reason. The clinVar form acquires the info from what's available into Scout, and if the info is missing the field would be blank.

That's why you should always double check both the pre-filled and the blank values, and in case fix them in the form or in the excel file.

I'm closing this since it's not really a bug and it could be due to a number of reasons.

**Comment by 4WGH** [comment]
ok. I'll keep an eye on it for more recent case. ignore for old case.
