### ISSUE TITLE
Identify positions in transcript with low coverage?

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#1863]
Hi!

We have a WGS case where we are primarily interested in one gene. In the coverage report I can see that only 99.89% of the gene is covered to 10x; 0% of the two transcripts in this gene are covered to 10x. Is there any way I can identify which position(s) are not covered to 10x? A quick manual look in IGV did not identify anything, and I'm wondering for which exons I need to do Sanger :) Is there any way I can get the depth of coverage in numbers for each position? I mean, can I access that from my end?

Sample: 20053
Gene: SLC6A8, HGNC number 11055, region chrX:152953752-152962048

**Comment by dnil** [comment]
In theory yes, but it appears it was a long time since anyone used the feature so it has collected some rust. Heres a url for it: 
https://scout.scilifelab.se/reports/genes/11055?sample_id=ACC6583A7

<img width="900" alt="Screenshot 2020-04-03 at 18 38 17" src="https://user-images.githubusercontent.com/758570/78384408-6b324b80-75da-11ea-83a6-59bce075e88a.png">

So basically one exon with a dip below 10, which aint weird for X. Like so:
<img width="1610" alt="Screenshot 2020-04-03 at 18 43 06" src="https://user-images.githubusercontent.com/758570/78384959-68842600-75db-11ea-86a3-5530a1c7d719.png">
I'm not exactly sure how to interpret the reason for it, in that alt allele spanning the dip: usually, when dealing with low level events on X for a gent I'd assume I'm looking at sth that has a homologous region on Y. This is on the edge of PAR2, but afaik not formally in it. You would know this better.

I think you could figure out the syntax of the url above knowing the cg sample_id of your 20053 from e.g. the igv view in scout or from the order portal so you could repeat this for other genes if need be.

But, anyway, you are supposed to be able to get there via the coverage overview from the gene panel on the case page, here: 
<img width="703" alt="Screenshot 2020-04-03 at 18 37 37" src="https://user-images.githubusercontent.com/758570/78384407-6a99b500-75da-11ea-8d23-1cccb4f64411.png">

Going to the correct gene panel view where you can select overview:
<img width="831" alt="Screenshot 2020-04-03 at 18 38 00" src="https://user-images.githubusercontent.com/758570/78384409-6bcae200-75da-11ea-86d8-ed0bc14d5bee.png">

And get to a completeness list:
<img width="929" alt="Screenshot 2020-04-03 at 18 51 15" src="https://user-images.githubusercontent.com/758570/78385465-2dcebd80-75dc-11ea-98bf-703780ea69ef.png">

Now, that might have worked for you if the "Next" button wasn't bugged in the sense that it tries a GET request to chanjo, and this particular gene panel gene list is too long for that, so it fails. In recognition of that, we will also treat this as a bug report. There is unfortunately no time to get it into the next release (4.15, ready for deploy due Monday or so). Thank you for getting me to look.. 😸

**Comment by ielvers** [comment]
Thank you so much @dnil!

**Comment by ielvers** [comment]
Mostly out of curiosity: there are three SLC6A8 transcripts in NCBI. All three are listed in the "transcript overview" box in Scout in cases with SLC6A8 mutations. Only two are included in the report above. The missing one happens to be the disease-associated, and also the largest isoform. How come it's not included? Is there a cut-off for number of transcripts per gene?
Thank you!

**Comment by dnil** [comment]
Hi again! 'welcome! 😊

This is a bit complicated in the databases, as usual when one tries to get into biological details, and most likely much more complicated in actual cells.

In general, there has been an effort to keep gene models the same across MIP, Scout, Chanjo and the scout IGV-view: this mostly succeeds, but not always. More often, there are discrepancies between NCBI and ENSEMBL gene models. As this is especially pronounced for hg19, we mostly dodge them until we are up to hg38.

I'm guessing your three NCBI transcripts are the RefSeq NM-ones listed in Scout? There are also a few NCBI XM-ones that have not made it into the canon yet. The situation in ENSEMBL that MIP and Scout use for a primary source of gene model data is a bit more complicated: 
<img width="1425" alt="Screenshot 2020-04-08 at 12 50 00" src="https://user-images.githubusercontent.com/758570/78776259-d8a5f980-7997-11ea-8f3d-3942734523b3.png">

<img width="1662" alt="Screenshot 2020-04-08 at 13 07 02" src="https://user-images.githubusercontent.com/758570/78777478-e52b5180-7999-11ea-90a7-10e94174bd94.png">
As you can see from this gene overview in Scout (or from an ENSEMBL gene overview), they think two of the RefSeq transcripts are essentially the same, and at least from a quick look in IGV I have to say they are at least not too far off? I'm soon off to lunch, so I have not checked in genbank, but I leave that as an exercise for you! 😉 

HNGC prefer NM_001142805 as the default coordinate reference sequence for SLC6A8, which is according to ENSEMBL (and IGV) are effectively the same as the older standard NM_005629. NM_001142805 is also listed in the Chanjo report. HGNC are good, and arguably by definition the canon for gene name data, but of course they are not omniscient. Do you have newer data that indicate NM_005629 is different, and more relevant to disease? If so, it may well be relevant to communicate with HGNC about it, and we can try to update accordingly!

**Comment by ielvers** [comment]
Enjoy your lunch :) 
NM_005629 and NM_001142805 are essentially the same, they only differ by 33 nt (somewhat surprisingly these are split up over two exons). NM_005629 which is the longer is the one listed as disease-associated in HGMD and also the only one I see mentioned in Ensembl. Hence I was curious why it didn't make it to the Chanjo report :)
![image](https://user-images.githubusercontent.com/57791644/78778722-055c1000-799c-11ea-99ed-73d72a8c6076.png)
It's always interesting to learn more about what happens behind the Scout interface that we see, so thanks for taking the time to respond!

**Comment by dnil** [comment]
😄Thanks, and ditto for taking time to report things that don’t quite add up. Errors hide among them! My feeling in general is that HGMD is lagging on nomenclature, but that was based on experience from a few years back. Assuming you have recent literature again supporting them or eg disease variants in the removed regions do contact HGNC. They as all of us rely on feedback! Often you may well be the foremost expert on your gene of interest!

**Comment by dnil** [comment]
(Oh, and careful with your genome builds - the ENSEMBL picture above was from hg38!)

**Comment by ielvers** [comment]
> (Oh, and careful with your genome builds - the ENSEMBL picture above was from hg38!)

Very good point! In hg19 (or technically GRCh37), both NM_005629 and NM_001142805 are listed as RefSeq equivalents to ENST00000253122 despite differing slightly from each other.

![image](https://user-images.githubusercontent.com/57791644/78781150-0db64a00-79a0-11ea-8c1c-a610965e515b.png)

**Comment by dnil** [comment]
So to be fair, the issue with the Next button not working is not precisely in Scout, but close enough (Chanjo-Report). It will be a little tricky to test out, but expect it solved around the next release.

**Comment by dnil** [comment]
Hehe, and yes, about hg19 basically deriving from GRC build 37 - but don't forget it was the other way for a long time. 😄 Apparently that little issue over the mt sequence is now history as well!

**Comment by dnil** [comment]
Closing this as it is solved by https://github.com/Clinical-Genomics/chanjo-report/pull/4. It will still be somewhat cumbersome to get to the requested information, but possible also in the general case. 

The entire gene symbol handling in Chanjo/Chanjo report and its interaction with Scout could use an overhaul, but that is another story.
