### ISSUE TITLE
HGVS Description

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1871]
The description of the HGNC transcript is not the same as in Alamut for reference transcript NM_024729. Why is this?

https://scout.scilifelab.se/cust002/F0033889/320dd55c1342156dcdf1c8a72cbe6d52

**Comment by dnil** [comment]
Sorry @47KW I don't quite follow and may be missing an issue! Please let me know if this was more than a question about Alamut! Scout appears to be doing its job by using the current one from HGNC: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:23212 
<img width="278" alt="Screenshot 2020-04-14 at 10 57 02" src="https://user-images.githubusercontent.com/758570/79205860-c831cb00-7e3e-11ea-9b86-1eb1f200c0b6.png">. It does appear flagged as manually curated: that may be an indication HGNC have a different opinion than say NCBI or possibly other organisations such as Interactive Biosoftware that publish Alamut Visual? Not saying either is right without reading up on the gene, but possibly a clue? I'll close this for now, but feel free to reopen!

**Comment by northwestwitch** [comment]
I think he meant the HGVS descriptions for the same variant, same position (19:50812281). Specifically: 
- c.5783G>A, p.Arg1928Gln in scout
- c.5684G>A, p.(Arg1895Gln) in Alamut

?

In this case I'm not really sure. Looking at the VCF it seems that we annotate these values from Ensembl:
`ENST00000376970.2:c.5783G>A|ENSP00000366169.2:p.Arg1928Gln`

Perhaps Alamut uses NCBI transcripts (NM_024729.3(MYH14):c.5684G>A) ?

**Comment by 47KW** [comment]
Hello
I can Confirm the Chiara-view on the transcripts. Version .3 is different from the one used in Scout.


14 apr. 2020 kl. 11:32 skrev Chiara Rasi <notifications@github.com<mailto:notifications@github.com>>:


I think he meant the HGVS descriptions for the same variant, same position (19:50812281). Specifically:

  *   c.5783G>A, p.Arg1928Gln in scout
  *   c.5684G>A, p.(Arg1895Gln) in Alamut

?

In this case I'm not really sure. Looking at the VCF it seems that we annotate these values from Ensembl:
ENST00000376970.2:c.5783G>A|ENSP00000366169.2:p.Arg1928Gln

Perhaps Alamut uses NCBI transcripts (NM_024729.3(MYH14):c.5684G>A) ?

**Comment by northwestwitch** [comment]
Ok but then it must be a difference between Ensembl (that we use to retrieve the HGVS from) and RefSeq. I don't really know how to fix this (if it's a problem!?)

**Comment by dnil** [comment]
Ah, thanks! HGVS is shown precisely as derived from VEP. RefSeq did change on 26-DEC-2019, making their v.3 a little longer, but only the 3'UTR, so presumably the update didn't really touch this issue. It is actually possible to see the RefSeq coordinates from way down in the transcript table in Scout. First the ENSEMBL version:
<img width="1586" alt="Screenshot 2020-04-14 at 12 03 40" src="https://user-images.githubusercontent.com/758570/79212569-2020ff80-7e48-11ea-8935-d08e66b06bc5.png">

Then RefSeq:
<img width="1574" alt="Screenshot 2020-04-14 at 12 04 07" src="https://user-images.githubusercontent.com/758570/79212572-21522c80-7e48-11ea-9ef2-fa73371f6d5b.png">

I suppose it would be possible to construct our own HGVS_c and HGVS_p for display rather than deriving them implicitly from VEP/ENSEMBL, but this is also a little risky. If this becomes a problem, we could look at that!
