### ISSUE TITLE
Add Assertion method citation to clinVar table export fields

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#1902]
Column names in clinvar submission file does not match column names in Clinvar submssion template needed to submit variants availible: https://www.ncbi.nlm.nih.gov/clinvar/docs/submit/. 

[cases-200402-PMM2.xlsx](https://github.com/Clinical-Genomics/scout/files/4598285/cases-200402-PMM2.xlsx)
[SUB7341832.xlsx](https://github.com/Clinical-Genomics/scout/files/4598286/SUB7341832.xlsx)
[variants-200402-PMM2.xlsx](https://github.com/Clinical-Genomics/scout/files/4598287/variants-200402-PMM2.xlsx)

**Comment by northwestwitch** [comment]
Hi! we've created the downloadable files based on the document **Full – SubmissionTemplate.xlsx** (https://www.ncbi.nlm.nih.gov/clinvar/docs/submit/#tsv).

It's a while that I don't submit to clinVar so something might have changed in the process, but to be sure, are you following the instructions in Scout clinvar howto? Because the format of the files produced and downloadable by Scout is .csv (text files. comma separated) and not excel (the files you attached to the issue). During the submission process, in the "Submission format" in panel 1, make sure to select the value "Comma-separated values" (look further down).

I'm posting here the text:

**Requirements**
Make sure to register a user to the clinVar submission portal.
If your organization is not already present in clinVar you should follow the instructions to register a submitting organization to the same portal. The first time an organization is registered in the ClinVar Submission Portal, the content will be reviewed, so it will take some time before getting approved in order to start a variant submission.

**Obtain a submission ID**
If the requirements above are fullfilled, you can start a new submission by using the "Upload new file submission" button from the submission page.
This button is a link to a multi-panel (4 panels) submission page. The first panel (submission information) has a precompiled field named "Submission name".

**Fill in panel 1 and 2**
Fill in submission forms in panel 1 and 2, respectively named "Submission information" and "Organization". In the "Submission format" in panel 1 make sure to select the value "Comma-separated values".
Assemby name fields should be filled in before proceeding further with the submission.

**Download the files**
You'll need to register the Submission Name obtained from Clinvar portal in order to download variants and casedata submission files.

**Upload the files to Clinvar**
Upload the files obtained above (either the variants .csv file or the variants .csv + the casedata .csv files) in the "Submission Files" field in the third panel of the submission. The field named "Assertion Criteria File" should be left blank, since the default information is already filled in the "Variants sheet" (ACMG Guidelines, 2015).


If submitting csv files doesn't work let me know and I'll check again against their template!

**Comment by Leif-glitch** [comment]
Hi!

We followed the Howto. Why it is excellfiles attached is because we converted the csv data into an excel sheet for submission. I guess submitting the csv should work as well. But to make sure everything is correct upon the first submission it is easier to view the variants in the excel file to make sure all the data we want is in. This is also how we saw the mismatched columns. I hope i explain myself ok here 🙂.

Also we noticed that one column lacks the correct information when downloading it from scout (Assertion method citation) where the ACMG publication we use as assertion method needs to be citited (PMID:25741868). This information is required for clinvar submission.

To clarify also, the cases and variants files attached are the finished versions of the files that we were able to submit after adjusting them to the Full – SubmissionTemplate.xlsx. The case and variants are version of the CaseData and Variant tabs in the template.

Vänliga hälsningar/Yours sincerely,
Leif Karlsson,
Sjukhuskemist, Med.dr.
leg. Biomedicinsk Analytiker

CMMS L7:05,Karolinska Universitetssjukhuset / Karolinska University Hospital

171 76 Stockholm /SE-171 76 Stockholm, Sweden



________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 8 maj 2020 13:41
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Leif Karlsson <leif.e.karlsson@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Clinvar submssion file (#1902)


Hi! we've created the downloadable files based on the document Full – SubmissionTemplate.xlsx (https://www.ncbi.nlm.nih.gov/clinvar/docs/submit/#tsv).

It's a while that I don't submit to clinVar so something might have changed in the process, but to be sure, are you following the instructions in Scout clinvar howto? Because the format of the files produced and downloadable by Scout is .csv (text files. comma separated) and not excel (the files you attached to the issue). During the submission process, in the "Submission format" in panel 1, make sure to select the value "Comma-separated values" (look further down).

I'm posting here the text:

Requirements
Make sure to register a user to the clinVar submission portal.
If your organization is not already present in clinVar you should follow the instructions to register a submitting organization to the same portal. The first time an organization is registered in the ClinVar Submission Portal, the content will be reviewed, so it will take some time before getting approved in order to start a variant submission.

Obtain a submission ID
If the requirements above are fullfilled, you can start a new submission by using the "Upload new file submission" button from the submission page.
This button is a link to a multi-panel (4 panels) submission page. The first panel (submission information) has a precompiled field named "Submission name".

Fill in panel 1 and 2
Fill in submission forms in panel 1 and 2, respectively named "Submission information" and "Organization". In the "Submission format" in panel 1 make sure to select the value "Comma-separated values".
Assemby name fields should be filled in before proceeding further with the submission.

Download the files
You'll need to register the Submission Name obtained from Clinvar portal in order to download variants and casedata submission files.

Upload the files to Clinvar
Upload the files obtained above (either the variants .csv file or the variants .csv + the casedata .csv files) in the "Submission Files" field in the third panel of the submission. The field named "Assertion Criteria File" should be left blank, since the default information is already filled in the "Variants sheet" (ACMG Guidelines, 2015).

If submitting csv files doesn't work let me know and I'll check again against their template!

**Comment by northwestwitch** [comment]
Hi @Leif-glitch and @4WGH, I'm comparing the submission files that are downloadable from Scout and those that worked for you (SUB7341832.xlsx, right?). If I understand the situation correctly the problem arose because when you went in Clinvar and tried to submit directly the files downloaded from Scout the system complained because there were fields missing, i.e. too few columns compared with the official document header (as in SUB7341832.xlsx), is it so?
That is because the official excel sheet template contains white columns for each of the fields that are not filled in, while the Scout version had only columns with filled in info, no blank columns.

The biggest difference between Excel file submission and txt (csv) file submission in clinvar is that **in the csv file submission you should omit empty columns** while if you stick to the excel file submission you should provide both filled in columns and empty columns.

**Scout does not support the Excel file submission** and that's why I don't expect it to work, but please correct me if I understood it wrong.

Regarding the assertion method I think we intend 2 different fields. Scout variant downloadable files contains an "**Assertion method**" column that is pre-filled in with "ACMG Guidelines, 2015".

This field is optional. Another optional field in the official submission template is the one named "**Assertion method citation**" and that is the one where you should write PMID:25741868. Our template does not contain this field (I thought it was redundant since we are already providing the assertion method, that is the same document), but if you feel like having it we could introduce it.

![image](https://user-images.githubusercontent.com/28093618/83120971-083ccc80-a0d2-11ea-9e96-1ce59e763f8f.png)

Let me know what you think about this!

**Comment by northwestwitch** [comment]
I take the liberty to rename this issue to "Add Assertion method citation to clinVar table export fields".  Correct me if I'm wrong but I think the error you received from clinVar was due to the use of Excel format instead of a CSV files, so there is no action needed by our side there.

**Comment by 4WGH** [comment]
yes!

I've found out the problem with the upload of the csv files.
We have Swedish Pc, with swedish excell so the file in cvs get a ";" instead of a ",".

So the fomat is not komma separated 🙁

I've found a decent solution to work around the problem. Now we know wht our csv files whre not accepted by ClinVar. Whyle the excelle file busmission went throug 🙂


Michela
________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 5 juni 2020 09:27
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Add Assertion method citation to clinVar table export fields (#1902)


I take the liberty to rename this issue to "Add Assertion method citation to clinVar table export fields". Correct me if I'm wrong but I think the error you received from clinVar was due to the use of Excel format instead of a CSV files, so there is no action needed by our side there.

**Comment by dnil** [comment]
Ah sorry, I didn't notice that it changed name! My bad!
