### ISSUE TITLE
Annotations for cancer

### ISSUE THREAD

**Issue by lindakohn** [Clinical-Genomics/scout#1905]
Hi,

How should the vcf be annotated for cancer analysis? Do you have an example .ini file?

Regards
Linda

**Comment by dnil** [comment]
Hi there; good to have you onboard! 

In general, VEP --everything is fine for a start. I would recommend at least also including COSMIC. There is an example cancer case in the demo dir to look at (pedagogically named "cancer_test"). I would also suggest having a look at the loading tests to get an idea of what is already available for display.

Since you ask for an ini, I suppose you mean for GenMod? We did make samples of those for cancer, but we are not actually running them for production; check with @hassanfa, @szilvajuhos or @moonso?

In Solna, we usually run BALSAMIC (https://github.com/Clinical-Genomics/BALSAMIC) and MIP (https://github.com/Clinical-Genomics/MIP) for hereditary cancer or when the affected tissue is not expected to be very heterogeneous, e.g. leukaemia, paediatric tumor etc.
Both pipelines are very compatible with Scout, and at least MIP can be started from VCF if you already have it.

**Comment by lindakohn** [comment]
Great, thank you! I'll check with them. So, the rank scores can be added by either BALSAMIC or MIP?

**Comment by moonso** [comment]
Hi @lindakohn ! No rank scores are adde with genmod. There is a template for a score model somewhere, it would be nice to develop something together. Or what do you say @hassanfa ?

**Comment by lindakohn** [comment]
Hi @moonso, sounds good. I'll absolutly help with what I can. If you find that template I'll be happy to see it.

**Comment by hassanfa** [comment]
Linda, I sent you an email regarding how we do it in BALSAMIC. As Daniel mentioned, and as you know VEP is way to go.

For sake of having it here under the issue, here is the copy of it as well:

> I'd recommend following a standard VEP annotation and include COSMIC. There are a lot of resources out there for ranking and putting variants in tiers. I highly recommend to use Genmod (Måns developed this) for ranking variants. 
> 
> For somatic mutations an initial filtering strategy might even interest you. In BALSAMIC's VCF files, we usually filter out variants with low coverage, low AD count, and very high or very low AF (0.01< & >0.95) and annotate them as low_quality_somatic_variant.

**Comment by dnil** [comment]
Hi again,
looking to close some old issues, I think this has been worked on in other threads in the meantime. We did make an example .ini, though I honestly have not seen any evaluations from it yet. 😊 

https://github.com/Clinical-Genomics/reference-files/blob/master/cancer/rank_model/cancer_rank_model_-v0.1-.ini

Lets revisit this in other issues!
