### ISSUE TITLE
Clarification on global comments and classifications

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1943]
Three questions or comments about global comments and classifications:

1. Are global comments shared between rare disease and cancer tracks? i.e. is it tied to variants regardless of track?

1. If global comments are shared between rare disease and cancer tracks is it possible to limit it? (This is my question and not customer request)

1. Is it possible to have global classification similar to global comments? (just a question to know about how it works). e.g. tagging a variant as likely pathogenic in one case and seeing it in another case.

**Comment by dnil** [comment]
1. Essentially they are separate, as they are operated on relative to variant_id, which contains the variant category. This has pros and cons, but I guess from 2 that you will be mostly relieved by this.
2. I guess this rather becomes is it possible to retrieve both? It would be possible with a little active id mangling adding e.g. cancer_sv to an sv search, or cancer instead of snv in the variant id for the latter. Please ponder and return with a request for changes if needed.
3. In principle this is how it works by default on the RD side. Evaluations are retrieved for display based on variant_id, so including category but excluding case and institute, if that makes sense. Of course they are not directly applied, as the patient phenotype may be something completely different, but they should be globally available for viewing.

**Comment by dnil** [comment]
Ok, closing this if that answers the question! Just reopen otherwise!
