### ISSUE TITLE
ExAC shows 0 but the frequency is 0.2797 

### ISSUE THREAD

**Issue by nicolelesko** [Clinical-Genomics/scout#207]
For this variant ExAC shows 0 
https://clinical-db.scilifelab.se:8083/cust003/15091/variants/c76a40cee5078fb65eebaf73476800ff

**Comment by moonso** [comment]
Thanks Nicole,
I'll have a look into this

**Comment by moonso** [comment]
@henrikstranneheim 
Ok so in ExAC.r0.1.sites.vep.vcf.gz the line looks like:

```7	147335933	.	CTT	CTTT,CT,CTTTT,C	1701754.22	PASS    AF=0.133,0.077```

in ExAC.r0.3.sites.vep.vcf.gz it looks like:

```7	147335933	.	C	CT	1.70175e+06	PASS    AF=0.13```

How was this annotated, with what file and when?

**Comment by henrikstranneheim** [comment]
1. Exac seems to update their website before releasing new flat files so sometimes we go out of sync (As in this case, explaning AF=0.13 (flat file) and AF=0.27).
2. If the variant is not present in 1000G, there was a bug in MIP overwriting the exac frequency as 0 instead of 0.13. This has been fixed some versions ago by introducing "snpSiftAnnotationOutInfoKey" flag. However, this bug of course remains for "old analyses".
