### ISSUE TITLE
Scout report improvements for Cancer view

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2108]
Besides being able to know which filter was used to generate the report, I'd like to also be able to see a table of variants in the report. For rare diseases this doesn't matter much, right? But for cancer view, it'd be great so the report contains the following information:

- [x] Discard inheritance model reporting
- [x] Discard GQ (?)
- [x] Add AF of reported variant
- [ ] Squash variant table into a more compact form. e.g. we can remove allele depth and add AD to reference and alternative
![image](https://user-images.githubusercontent.com/1086877/93575862-74518200-f99a-11ea-9723-b147da6c0303.png)

- [x] It still says "Affected": Yes/No even for cancer variants. I'd like to have it as Tumor or Normal. Or just use "Phenotype", Daniel: possibly with another name
- [x] Discard `Single sample family. No pedigree available.` for cancer samples. There is no pedigree.
- [ ] Discard 1000G, always show gnomad? pop_freq_max?
Daniel: Population frequencies are shown as annotated (and parsed on import). We can certainly ditch or deprecate 1000G from parsing, but if it is not annotated it will also not be shown. This is a general issue for Scout really, that could so slowly perhaps be resolved by only showing GnomAD assuming that essentially all cases should have it.
- [ ] Add bait set name to the report instead of "PANEL". HFA: Could this be a value in Scout config? Also ultimately the information about panel according to https://clincial-genomics-hybrid-capture.readthedocs.io/en/latest/ in a nice format as BALSAMIC report.
Daniel: this has been extensively discussed in other issues, and conforming to Scout panels will do much good for the overall experience. But if you want not only the gene panel for use with Scout display filtering, but also a capture panel linked, add it as a key to the load config and we'll link to it from both the case page and show it on the case report. Compare e.g. the rank model links that we have now.
- [x] Discard ancestry if empty (i.e. N/A)
- [x] Discard parenthood if empty (i.e. N/A)

What do you think? @vwirta any more items I missed?

**Comment by dnil** [comment]
I'd be distressed to see the variants table dumped to pdf, especially if no-one interacted with or triaged variants. For that, you want a different tool.

That said, all of the above sound great for the cancer general report and should clearly be added. Can we start with that, plus the option to more easily pin more variants and see where that takes us?

**Comment by northwestwitch** [comment]
Perhaps also the general report should be distinct

**Comment by dnil** [comment]
Possibly yes. I would argue polymorphism would be ideal, rather than completely different or the current with "if cancer" for every third line. 

In the general report, the mechanisms for adding different evidence for different reasons will be useful anyway. Since we have cancer specific dismiss reasons, that should be easy enough (and e.g. showing GQ for "technical issues" should benefit RD as well).

**Comment by hassanfa** [comment]
> I think we should aim for different templates for RD and cancer cases. They're becoming so different

They are like kids growing... I get teary eyes when I release a new BALSAMIC version. It is 5 now 👀

Now serious:
Good points. 👍 My devious plan is to turn cancer report into a molecular report of the current trends in   industry and other hospitals in other countries. Thus having a table of reported variants in first page of report would serve as a snapshot view.

So if make mass-pinning easy, then reporting will be as it is now 👍 

Base report framework is good, but wouldn't it make them still depending on each other? I would favor decoupling cancer report away from RD completely.

**Comment by dnil** [comment]
😅And I would argue that concept is hopelessly dated. RD dittos were the same - and a few that have not yet been eliminated are still. You would only be dealing in biomarkers and leave causation and genetics out. It’s a little like if you would stain tumor sections with random dyes rather than specific antibodies for proteins of causal relevance. That is all good and well, but can be done with a VCF2pdf tool. 

The current cancer view is intended for finding causal variants - or ones important for treatment or prognosis. Think leukemia, brain tumors and so on. That’s why we have tier classification etc.Those variants are not going to be many and they may require a little filtering, expert discretion in assignment etc. Very similar to the typical RD case, only different knowledge base and biology.

Again, bookkeeping for biomarker variants is a different thing. That belongs in separate files, delivered as scout downloads or bundles to caesar directly from pipelines.

**Comment by vwirta** [comment]
Some further ideas to add to report
- bait set used for enrichment (sequencing field says now 'panel', but would be more informative if we add the actual bait set)

To remove?
- In Pinned varriants: Do we still need to have the 1000G freqs? Would it be more informative with gnomAD(max)?
- In Other Manual Ranked Variants: would look better if freqs here are the same as for pinned variants

**Comment by hassanfa** [comment]
> That is all good and well, but can be done with a VCF2pdf tool.

That's a bit pessimistic, but you've got a point.

> The current cancer view is intended for finding causal variants - or ones important for treatment or prognosis. Think leukemia, brain tumors and so on. That’s why we have tier classification etc. Those variants are not going to be many and they may require a little filtering, expert discretion in assignment etc.

Fair enough, it is very hard to design a one for all solution. This seems like a tricky sitatution.

> Again, bookkeeping for biomarker variants is a different thing. That belongs in separate files, delivered as scout downloads or bundles to caesar directly from pipelines.

Could be suitable for workflow, and crunched later in Scout though variant list and by experts.

Also, added Valtteri's comments to list of wish list.

**Comment by dnil** [comment]
> That's a bit pessimistic, but you've got a point.

Cheers - you are very reasonable! I wouldn't say pessimistic; just matter of fact on that part. No reason to introduce loads of conflicting code to fill that niche?

> Fair enough, it is very hard to design a one for all solution. This seems like a tricky sitatution.

Until someone shows me otherwise, I'm going to remain convinced that is what your end users will want - at least in a few years when they have gotten some large scale genetics experience. Granted, depending on who they are and what they do, the may also want biomarkers, but again, that is very easily solved with a bypass mechanism. No manual triage needed for those!
