### ISSUE TITLE
Insertion positioning in IGV is one base off?

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2170]
I'm looking at an insertion called on position chr5:1221430, but in IGV it looks like it would be on position chr5:1221429. 

Variant https://scout.scilifelab.se/cust003/20017/8b3e8fe403457286663a106909776556
It's the insertion of an A changing the sequence from GTAA to GTAAA:
![image](https://user-images.githubusercontent.com/57791644/97572621-da451680-19e8-11eb-8d6c-0117b6dce8a3.png)

However in IGV it looks like the A would be placed before the T, not after - changing the sequence to GATAA (and abolishing a splice site):
![image](https://user-images.githubusercontent.com/57791644/97572728-ffd22000-19e8-11eb-8540-cb3052610ffd.png)

Now, this is probably just how things are displayed in IGV as I see the same discrepancy when looking at small insertions in other cases. But can you please (a) reassure me that it's IGV that places the insertion one base upstream and (b) tell me if it can be fixed?

**Comment by dnil** [comment]
Well spotted: keen eyes are needed in the view you show. It is perhaps clearer and more unfortunate when zoomed in:

![Screenshot 2020-10-30 at 09 59 46](https://user-images.githubusercontent.com/758570/97680538-2058b380-1a97-11eb-870c-67d8adb43702.png)

It is indeed (a) an issue with IGV.js. If in doubt, look at the raw read sequence shown from your right-click menu on the read in igv.js. If you wish, you could report it with them to get some cred for it, otherwise we will. That will also afford an answer to (b) - but of course it will be fixed when phrased as in the question. This is pertinent.

**Comment by ielvers** [comment]
Thanks for your answer! Please feel free to report it :)

**Comment by northwestwitch** [comment]
Are you sure that this behavior is a bug? Because the call says TA instead of T occurring at 1.211.430, and that's exactly what IGV.js shows: an insertion starting at that position. If the call was AA instead of A at position 1.211.431 then I would agree with you that the purple marker should be shifted one base to the right.. 🤔

**Comment by dnil** [comment]
Thing is it works rather well when zoomed out far, but when it is zoomed in all the way it has the little insertion line shown 5' to the reference base, when the insertion actually extends to the 3' side. It is extremely easy to think this means read sequence was GATAA rather than GTAAA. I would think it unambiguous if it was shown eg as a solid purple background on the T - or on the 3' side of it.
