### ISSUE TITLE
VAF missing in the report

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2254]
Hi again! 

The VAF (variant allele frequency) is not shown anywhere in the PDF report, is this something that can be done? Becasue now we are writing it as a comment on the specific variant. But as said, it would be good if somehow the VAF is visible once you create the PDF report. 

Hälsningar Hero

**Comment by hassanfa** [comment]
Hi Hero,

It is part of what we discussed couple of month ago to improve Scout-cancer here: https://github.com/Clinical-Genomics/scout/issues/2108 (item two in the list) Maybe we can move this discussion there?

**Comment by heronikdin** [comment]
Of course, I forgot about that one. As long as it comes up as a request from us :) Thank yoU

**Comment by dnil** [comment]
Thanks for that - some very good suggestions have been idle on that issue, partly due to the characteristically verbose discussion on export of large number of variants plus a long list of other fun things to do. We'll try to figure out where those checkboxes belong and get back on it! Lets leave this issue open for a little bit so we don't forget! 😊

**Comment by northwestwitch** [comment]
Fixed by #2257. In production starting from the next Scout release, so I'm closing the issue!
