### ISSUE TITLE
wrong transcript/connection on case report

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#2259]
https://scout.scilifelab.se/cust002/F0037125/cce4d3ad01f80405137e886f6b26f519

The position in transcript HGNC NM_022089 should be c.2978 not as below, which is shown in Scout.

  | ATP13A2 | NM_022089 (ENST00000452699) (hgnc-primary) | c.2963C>T

**Comment by dnil** [comment]
Agree - and so does actually the transcript table.. That variant overview box pulls from ENSEMBLs mapping to RefSeq which is imperfect (especially for hg19).
<img width="1608" alt="Screenshot 2020-12-15 at 12 57 43" src="https://user-images.githubusercontent.com/758570/102212558-b58ffa00-3ed5-11eb-8603-168757c478b8.png">

**Comment by dnil** [comment]
I had a call from @47KW, so can provide some more detail.

Part of the issues is the usual over ENSEMBL to RefSeq mapping. This will resolve when we switch to hg38, with higher quality transcript correlation and MANE etc.

But the other part is a couple of variant and case general report readability issues.

- [ ] General report formatting: we should be more clear about the origin of the "RefSeq" transcript number in there. As it is now, the variant that is pinned in this case looks good on the transcript table. It also gets the canonical coord on the case page when pinned, since we use the hgvs there. On the report we use what VEP and ENSEMBL think is the best refseq mapping, but we just show the ENSEMBL-to-RefSeq transcript number without mentioning that is what it is. 
Suggestions include that we in the report could 1) use the actual refseq transcript from the annotation 2) note that the transcript name is really a best-guess from ensembl or 3) use the gene symbol + hgvs like in `pretty_link_variant`. 
![Screenshot 2020-12-15 at 17 19 44](https://user-images.githubusercontent.com/758570/102242203-1af5e200-3efa-11eb-8f27-4b59eb36d52e.png)

- [ ] In the transcript overview we could consider trying to 1) try use the one from the "real" refseq transcript, or flag if they differ or 2) at least show the ENSEMBL ids as solid black and the NM-ones as gray guesstimates.. 
<img width="1076" alt="Screenshot 2020-12-15 at 17 18 00" src="https://user-images.githubusercontent.com/758570/102242033-ebdf7080-3ef9-11eb-8e4a-9d0fe184c1d4.png">

**Comment by dnil** [comment]
This also potentially doing a lot of work for something that will anyway likely resolve with changing reference, but since we do get the native refseq annotated from vep nowadays, we could verify on load (or on display worst case) that the inferred ensemble-refseq nucleotide and protein sequence position is equal to the native one - else flag it so that the user knows this is a contentious transcript mapping call..

**Comment by northwestwitch** [comment]
Working on this atm, I might have some questions as I go

**Comment by northwestwitch** [comment]
It might take some time as I want to test it locally but the EBI FTP service that we use to download the gene definitions in Scout is down : ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt

**Comment by dnil** [comment]
OK, so, @northwestwitch made a great start to this. The report will now clearly indicate that the transcript is actually ENSEMBL-derived. The transcript overview will also be much neater. We have a tentative plan for over-ruling VEP and having the native RefSeq transcript flagged as the primary one. But that will require another level of work, and be better done after some well earned holiday rest! To remember it, I'll reopen this, but reflag it from "bug" - as the most dangerous part is fixed now - to "enhancement" as getting the native RefSeq transcript, with the proper hgvs aa change, flagged primary will be lovely.

**Comment by northwestwitch** [comment]
I'm going to close this since we reached an agreement on the transcripts that are shown on variants pages and the report. Otherwise let's reopen it.
