### ISSUE TITLE
NEw SCOUT: not possible to choose a gen list in the filter function. 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#229]

**Comment by robinandeer** [comment]
Hi,

can you give some more details regarding this issue? Perhaps you have a URL that isn't working as expected?

For me it works to filter by gene panel :)

FYI: there are multiple version of the gene lists for some of the cases. This issue is already known and fixed but it might look weird in Scout right now as well as in the coverage report.

**Comment by 4WGH** [comment]
![new](https://cloud.githubusercontent.com/assets/12525201/12246218/860c4e86-b8ad-11e5-9240-ff3218d3f066.PNG)
this is what I see in the new scout once I try to choose a list
![old](https://cloud.githubusercontent.com/assets/12525201/12246229/9894daa0-b8ad-11e5-9768-abdf5b55b94c.PNG)
this is what I see in the on going one.

**Comment by robinandeer** [comment]
Oki thanks!

I think it has something to with this case specifically, the other cases seem to work fine so when we do the proper upload I would expect this to be resolved :)
