### ISSUE TITLE
Annotation and gene track in pileup.js out of sync?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#232]
It seems pileup.js displays another gene track than the one used for annotation (VEP)?

See e.g. https://clinical-db.scilifelab.se:8081/cust002/F0001933-miptest/variants/25b618863290fec5576faf2b2da175b8
Annotated as a TTN intronic variant; appears exonic/3pUTR in SESTD1.

**Comment by robinandeer** [comment]
Good catch! We are working on creating our own BED file with correct gene coordinates

(We were using the demo-version from the `pilup.js` guys)

**Comment by robinandeer** [comment]
This is now addressed with a CCDS based gene track - please try it out!

**Comment by robinandeer** [comment]
@henrikstranneheim: interesting case here
ALG1 is annotated in CCDS between 5121849 to 5134881 whereas in MIP a [variant](https://clinical-db.scilifelab.se:8081/cust000/A1140-miptest/variants/717be7e5519237b1ff04cbdcc361424a) on position 16:5112636 is annotated as ALG1 intronic. Which source does this annotation?

**Comment by henrikstranneheim** [comment]
VEP. Do you have the correct version of CCSS - b37?

Skickat från min iPhone

**Comment by robinandeer** [comment]
CCDS 15, based on GRCh37.p13

**Comment by henrikstranneheim** [comment]
Ok, let's dig into this tomorrow.

**Comment by robinandeer** [comment]
Absolutely,

for the discussion:

There's only one [CCDS transcript](http://feb2014.archive.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000033011;r=16:5083703-5137380) in ALG1. If I simply use those coordinates, then some genes that VEP annotates will not show up in the genome browser.

So do we stick to CCDS or include more liberally just the longest transcript so that we get closer to the VEP annotations?

**Comment by robinandeer** [comment]
We collapsed all exons in each gene and now they show up as expected ^^
