### ISSUE TITLE
Expose more information in scout cancer variants list

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2385]
The following are suggested improvements to the cancer variant list.

## Expose information
1. Hide rank column if not used ([link](https://github.com/Clinical-Genomics/scout/issues/2393))
2. Split Gene:Transcript:Exon:HGVS column into separate columns ([link](https://github.com/Clinical-Genomics/scout/issues/2391))
3. Add column for QC [(link)](https://github.com/Clinical-Genomics/scout/issues/2392)
4. ~~Rename ExFreq to PopFreq~~
5. Show only canonical transcript for HGVS
6. Move flags to separate column [(link)](https://github.com/Clinical-Genomics/scout/issues/2392)

## Alter functionality
1. ~~Rejected variants are de-promoted to bottom of the list~~
2. Add sorting function to table ([link](https://github.com/Clinical-Genomics/scout/issues/2393))
3. Remove cytoband and CADD from filters
4. Make dismiss variants button as a floating div that follows the window. ([link](https://github.com/Clinical-Genomics/scout/issues/2394))

**Comment by hassanfa** [comment]
👍🏽 Good summary. We have bunch of other cancer-view QoL changes or issues requests: https://github.com/Clinical-Genomics/scout/issues?q=is%3Aopen+is%3Aissue+label%3ACancer Should we put all of them here as well?

**Comment by dnil** [comment]
Good stuff!

In general, it is a Good Idea to make smaller Issues, and add them to a Project or Milestone if a more global checklist is desired. That way it is easier to be more detailed, and to have a discussion. Obviously multiple small changes to the same view go together.

Comments:

Expose:
- Off the top of my head I think I did at least #4 above not too long ago (#2351).
- Hiding rank order is being tested on another branch, but feel free to implement it anyways - we can reconcile that as needed.
- Canonical transcript is somewhat frowned upon on the RD side. Is this established with your geneticists? Otherwise consider primary transcript hgvs?

Alter:
1. Did you know that you can optionally hide dismissed variants since a little while back (#2277)?
2. As for sorting and non-ranked variants, those are nice things for a research setting, but we have really tried to avoid for a long time. These requests pop up every time we have a new user/developer/researcher look at the system. Manual variant triage through sorting and filtering does not scale well towards larger datasets. A trained geneticist that quickly did panels will struggle to finish a negative exome in a couple of h and confidently finish few negative genomes. Maintaining a ranking system is essential: for cancer I suppose a tentative first pass automatic AMP-tier triage with a simple numerical score added could substitute as well? If you are hard pressed to add them by your users, perhaps we could find a compromise and add sorting only on the research view. If I recall correctly, you anyway load "all" variants of interest, and never really use the research track?
3. Remove CADD is good. I would still consider cytobands somewhat useful, at least for the SV side, but that is not a strong opinion. It is of limited use for non-cytogeneticists.
4. 💯

**Comment by mhkc** [comment]
Sounds good to break this up into dedicated issues but I think we should leave this as a parent issue for a little while to give Björn or Viktor an opportunity to add more items.

**Comment by dnil** [comment]
Hi! I think we are done with this issue as well for now, right? I'm very sure someone will suggest sorting columns again at some point. 😬
