### ISSUE TITLE
variant not filtered

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2390]
https://scout.scilifelab.se/cust003/116/d848dbdb0dfb939a4ca929adfd46e641

I see this variant in fam 116.
The 2 genes are not in the IEM or EP v16. Why do I see it?

**Comment by dnil** [comment]
Hi! Thank you for the vigilance!

The TPI1 gene was added to the IEM panel (v17) by one of your colleagues. As the gene is also on the master list, it is automatically searched with the updated panel, as usual.

You can see some details of this in the alerts on the sidebar. The orange exclamation mark alerts you that a new version of the panel is available, and its time to rerun if you are not certain that the analysis will be satisfactory. There are some details as well, where you can see the gene differences.  
![Screenshot 2021-02-24 at 14 43 39](https://user-images.githubusercontent.com/758570/109009539-f020ca80-76ae-11eb-81ed-35c6631598a8.png)
Again, we do not control what has been run previously on MIP, so if there are completely novel disease genes on the new version, that were not previously on any other panel in the master clinical list, you may still need to order a rerun.

**Comment by 4WGH** [comment]
This pat is not re-runned with version 17
I should not see it! So I still not understand why as it is not re-runned with v17 I see it .

Accoring the case page
[cid:c75cf55e-3720-4b38-8f5d-4c005f570c9d]
________________________________
Från: Daniel Nilsson <notifications@github.com>
Skickat: den 24 februari 2021 14:52
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] variant not filtered (#2390)


Hi! Thank you for the vigilance!

The TPI1 gene was added to the IEM panel (v17) by one of your colleagues. As the gene is also on the master list, it is automatically searched with the updated panel, as usual.

You can see some details of this in the alerts on the sidebar. The orange exclamation mark alerts you that a new version of the panel is available, and its time to rerun if you are not certain that the analysis will be satisfactory. There are some details as well, where you can see the gene differences.
[Screenshot 2021-02-24 at 14 43 39]<https://user-images.githubusercontent.com/758570/109009539-f020ca80-76ae-11eb-81ed-35c6631598a8.png>
Again, we do not control what has been run previously on MIP, so if there are completely novel disease genes on the new version, that were not previously on any other panel in the master clinical list, you may still need to order a rerun.

**Comment by dnil** [comment]
Hi Michela,

we didn't get what I think was supposed to be your image; please try again, perhaps from the web page rather than by email if that didn't work?

If you think the gene TPI1 was added in error, please speak with the panel maintainer if that is not you?

Or do you mean the whole use-latest-gene-panel in general or this specific gene in particular?

That first was decided / presented on user meetings and released with [v4.21](https://github.com/Clinical-Genomics/scout/releases/tag/4.21) last year, as I'm sure you remember?

A potential source of confusion might be that it *could have* happened that you didn't see it, if the gene introduced on a later panel was not already an established disease gene (on clinical master), and thus NOT included in the MIP selected variant set. But if the gene is already on that established list, and is added to a later panel version, we show it.

**Comment by 4WGH** [comment]
I think we are not understanding eachother.
I will try to contact you tomorrow.


Michela
________________________________
Från: Daniel Nilsson <notifications@github.com>
Skickat: den 24 februari 2021 17:25
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] variant not filtered (#2390)


Hi Michela,

we didn't get what I think was supposed to be your image; please try again, perhaps from the web page rather than by email if that didn't work?

If you think the gene TPI1 was added in error, please speak with the panel maintainer if that is not you?

Or do you mean the whole use-latest-gene-panel in general or this specific gene in particular?

That first was decided / presented on user meetings and released with v4.21<https://github.com/Clinical-Genomics/scout/releases/tag/4.21> last year, as I'm sure you remember?

A potential source of confusion might be that it could have happened that you didn't see it, if the gene introduced on a later panel was not already an established disease gene (on clinical master), and thus NOT included in the MIP selected variant set. But if the gene is already on that established list, and is added to a later panel version, we show it.

**Comment by 4WGH** [comment]
![image](https://user-images.githubusercontent.com/12525201/109157756-c204be80-7772-11eb-9b47-7b81c15fd385.png)
 the missing image

**Comment by 4WGH** [comment]
This is what we undestand:

1. if there is  v16 on the case view (wee above image)  the variant list use the  v16 is .

2. the side column with the "!" sings alerts me there is an updated version of the panel 

3. if we want to analyze a patient with v17 we need to order a re-run

THere are some concerns about what happen now with the filtering whne a panel is updated.

**Comment by dnil** [comment]
Dear Michela, those are all good!

There is a 4. that has been in place for at least 6 mo, and was discussed extensively at the time. We talked about this yesterday, both in text and on the phone, so I do not quite see what your concerns are now? It would be good if you phrase them specifically, and we can adress them, discuss them and change if we decide something needs changing. I feel the current version is good, flexible compromise for optimising patient returns with rigor. Instead of worrying, please give me a solid counterexample where you would NOT like to see a variant in a gene introduced in a later version of the same panel, if it is anyway available on the case selected VCF?

May I kindly ask that you try your very best to stay pro-active when new features are introduced as well? We all had concerns around this issue 6 mo ago, and it would have been great with input at that time. 😊 I quite understand that things slip through sometimes, and late feedback is better than no feedback - we'll get it good anyway.  Let's worry about any actual problems at hand, ok?

**Comment by 4WGH** [comment]
I'm very sorry I did not  understand properly when you explained it 6 months ago. 
Sometime things need to run a while to see/understand consequences.  (I was glad at least I was not alone on it)

I plan to work keeping this info in mind now and see how we get affect in our work. Maybe the conserns will diseppear :)
I'll come back to you with contructive exemples in case we think we need :)

**Comment by dnil** [comment]
Perfect, thanks! And again, all your bulletpoints above are still perfectly valid. It's just that you immediately benefit from the curation of more up to date versions of the same panel if we already can accommodate part of it without a rerun. 😊
