### ISSUE TITLE
Problem with uploading gene panels using Scout interface

### ISSUE THREAD

**Issue by fulyataylan** [Clinical-Genomics/scout#2406]
Hi Scout team,

I am experiencing problems with uploading .csv formatted gene panels to Scout. The files are formatted according to the Scout user guide. Is it an issue with the customer account that I belong to?

Thanks for your help!

Best,
Fulya

**Comment by dnil** [comment]
Hi Fulya! Would you mind sharing your file via eg email so we can take a look? It is possible but unlikely that there is an issue with something, but the majority of times it’s just some non-obviuos thing about the file content or format. Cheers!

**Comment by dnil** [comment]
Tested ok after file editing. We can't find a function error, but the documentation is pretty far from perfect. In particular, it is confusing - not only our doing - that "csv"-files are semicolon separated in locales with decimal comma. Also, we could really note that files should not contain blank lines.

**Comment by northwestwitch** [comment]
The pages hosting the documentation have changed address so any link pointing to those pages, including the instructions to create gene panels doesn't work at the moment. I'm going to make a small PR to improve this documentation but I think we should release a new version soon, otherwise nobody will be able to see it
