### ISSUE TITLE
Classification category for Risk Factor (RF), also visible on variantS page

### ISSUE THREAD

**Issue by TJO-Lund** [Clinical-Genomics/scout#2414]
![image](https://user-images.githubusercontent.com/36200036/109828190-b581d980-7c3c-11eb-80e4-759095cef7b1.png)

Can we have a grey button next to the other 5 ACMG Classification Buttons (on the Variant page under "Bascics") and for SV-variants as an option in the Variant tag drop down list? This would make it easy to annotate a variant as a "Risk Factor" for disease (for instance if a variant increases cancer risk by a few percent above background risk, this should be allowed within the ACMG-guidelines, as far as we understand in Lund). If you agree the button could be grey (when pressed) and have the letters RF on it.
What do you think? All the best Tord

**Comment by dnil** [comment]
> "Moreover, in almost all of the common diseases the risk alleles can explain only up to 10% of the variance in the population, even when the disease has high heritability. Given the com- plexity of issues, this recommendation does not address the interpretation and reporting of complex trait alleles. We rec- ognize, however, that some of these alleles are identified dur- ing the course of sequencing Mendelian genes, and therefore guidance on how to report such alleles when found incidentally is needed. The terms “pathogenic” and “likely pathogenic” are not appropriate in this context, even when the association is statistically valid. Until better guidance is developed, an interim solution is to report these variants as “risk alleles” or under a separate “other reportable” category in the diagnostic report. The evidence for the risk, as identified in the case–control/ genome-wide association studies, can be expressed by modify- ing the terms, such as “established risk allele,” “likely risk allele,” or “uncertain risk allele,” if desired." (ACMG 2015) 

Do you have a more up-to-date statement from them?

Otherwise, how about adding Risk allele - or even all of the above suggestions with modifiers - to the manual variant tag list? Or did you have a particular reason for wanting to have it in the ACMG category? 😊

**Comment by ehre** [comment]
My first post here, so be kind ...  @dnil  ;-)
How about using ClinVar as the reference here, "risk factor" is an accepted term: https://www.ncbi.nlm.nih.gov/clinvar/docs/clinsig/

**Comment by dnil** [comment]
Kind as always? 😁

Most happy that you weigh in, both of you! We can name it whatever you like - it could be the new SFMG guidline! - and do parse those categories off the ClinVar variants anyway so they are familiar.

Formally, we should probably not call it an "ACMG" classification, unless you have more up-to-date versions of their guidelines?

Technically, there is currently a difference in how the ACMG classifications are handled (e.g. used for reports and categorised for upload to ClinVar) and how the local manual assessments (loosely compatible with DECIPHER/aCGH classification categories) are stored (reports only essentially).

Let's start with how you want to use it after it is flagged, and take it from there! Where do you want it to appear - reports, clinvar, matchmaker? And what term(s) would you like?

**Comment by dnil** [comment]
If it wasn't clear my suggestion was for a new variant tag or three. These are conveniently located a couple of lines above the ACMG buttons:
![Screenshot 2021-03-03 at 17 01 54](https://user-images.githubusercontent.com/758570/109834234-427b6180-7c42-11eb-9376-42496c124f7e.png)

**Comment by ehre** [comment]
Yes, well. So maybe not "ACMG" then (but in all honesty, we already use the same buttons for our oncogenetic variants where we primarily use ENIGMA or InSiGHT criteria instead of ACMG). I think the important thing here is that we would want to use "RF" **instead** of e.g. "P". So if we put it as a tag it is less evident that those classifications are exclusive (ad modum ClinVar). I think we would mainly use the classification internally to drop variants from further evaluation, but integration to ClinVar export is certainly a nice feature.

**Comment by dnil** [comment]
Ah, I feel like a peddler of used goods, but if you intend to use it to drop variants from triage I have another suggestion for you: how about a dismiss criteria? It could even be made cancer-exclusive if you wish, though risk factor could certainly work with any kind of RD really.

**Comment by ehre** [comment]
As you know, I don't work primarily in Scout, but a Southern bird whispered in my ear that when the same variant turns up in the next patient, the "ACMG" class will be immediately visible in the variant list and hence easy to dismiss again, but this is not true for the tags (if I understood it correctly). So that would be an argument for putting the "RF" in the same group as the ACMG class 1-5. And in addition, what I tried to say earlier, I think it would be complicated if a variant is both classified as pathogenic and a risk factor. To answer your question, it is not a specific problem for cancer, so should be available for the RD samples.

**Comment by ehre** [comment]
Here's a wild idea: Perhaps consider replacing the headline "ACMG classification" with the ClinVar term "Clinical significance"? Then those buttons could be used in good faith for ACMG (including the ever increasing number of ACMG modifications), ENIGMA, InSiGHT etc systems. We could still keep the "Classify" form for the occasions when we want to assign the different ACMG criteria. And slightly off topic - we probably should update the "Classify" form to allow for altering the evidence strength of the different criteria as per published ACMG modifications.

**Comment by dnil** [comment]
Yep, that that's a nice other use case! A global comment would do the same for alerting in future cases, but not be dichotomous / orthogonal to the ACMG classification.

I'm tempted to argue that a variant can indeed be both P in one disorder and RF in another, but let's leave that. It can also be P and B to different disorders anyway.

Let's investigate it! We should then also modify what ACMG-levels are shown for previous variants; currently that is only P and LP, in order not to have users auto-dismiss variants that were poorly classified as LB or VUS without thinking about what an additional case would do or that the patient- and variant classification phenotypes may differ. 

As an alternative then, we could also let certain variant tag assessments show on the variants lists, much as the ACMG, but with care taken so they are of the creating-interest kind rather than dismiss-easier kind?

We could certainly also introduce a new classifications, like we did with the cancer Tier system, and decide where to use/display it. Clinical significance according to ClinVar sounds good, we already parse it anyway.

**Comment by dnil** [comment]
Btw, do you regularly classify variants according to ENIGMA or InSiGHT? If so, we could add those as well?

**Comment by ehre** [comment]
One of the reasons I haven't posted here earlier is that I don't fully understand the differences in implementation between Stockholm and Lund. For instance, I am pretty sure that we see earlier LB/B classifications (at least in some institutes). Perhaps we should discuss that off GitHub.

What I like about ClinVar's approach is that they allow for different classification criteria, as long as the end result can fit into the predefined groups. We do use ENIGMA/InSiGHT where appropriate, but I don't think we should add those to the interface, rather try to condense everything into "Clinical significance". As I wrote earlier, I anticipate evermore gene/disease-specific adaptations of the ACMG criteria anyway, so it won't be possible to include all different upcoming models.

And yes, I agree with you that certain variants could end up with different classifications depending on context, but I still believe it is desirable to have the possibility to flag variants with a certain statistical association to a phenotype but low predictive value as something else than "pathogenic".

**Comment by dnil** [comment]
It is hard to stay on point in this format, and with many ideas flowing, but let’s see:

- We are working towards a completely common codebase, and the difference found so far have been small. Expect this ready soonish - though I cannot speak for when you will have that deployed (@bjhall?). There have at time been version differences with what you have deployed, partly due to the difficulty keeping up with merging two different forks. The display feature in question has evolved much as everything else - and can change again on request! We’ll add config options where we have system differences, but previous experience with other clinics in Solna is that reaching a sound common feature set through discussion benefits all.

- The variant tags might have had a couple of differences between the forks as well, but we will come up with a plan for that together if it was so.

- The difference to Coyote is larger, but progress is being made there as well.

- The way to change the content of ACMG classifications is by interacting with ACMG. I think Heidi R or others would listen if you have a good argument. Mixing it up within the same db with some cases following different system criteria will lead to pain later.

- I have not felt the pressure for additional classification systems since AMP, but that is my n=1 ignorance showing. I would still suggest we introduce them one by one as needed: there are ok patterns in the scout code so it can be quickly done. Any assessments could be shown on other cases if desired. ClinVar could be one such, but if the only purpose is to expose one tag it seems a bit redundant. Or we can make an SFMG version - that’d be quite fun. But another issue. 😸

- Consider that global comments allows you free text recurring classifications

- The variant tag system is also a good go-to one for introducing recurring classifications that don’t fall into a formal system. It seems cleaner to make those visible on the variantS page - and give them abbreviations like “RF” - than mess with the practice guideline ACMG ones. Sound ok?

**Comment by ehre** [comment]
It's getting late but I'm not sure I follow what you are saying now. I certainly haven't suggested "changing the content of ACMG classifications", if I gave that impression I should probably clarify. Tomorrow ... 🙂

**Comment by dnil** [comment]
My impression right now is that your issue would be solved if you could give variants an RF label, that would show on other cases? I think we can solve that! We would not need to introduce it in the ACMG classification for it.

**Comment by ehre** [comment]
Ok, so the quick fix seems to be to implement a variant tag "Risk Factor" that is seen globally, so let's do this. I still believe we will need to think about replacing the narrow and limited implementation of ACMG criteria to a more inclusive and dynamic assignment of clinical significance (that shouldn't have to involve Heidi Rehm at all, IMHO). And again - ClinVar has already realised this and accepts different models. But that discussion probably requires a meeting and not a GitHub thread.

**Comment by dnil** [comment]
Nice! Let's have the join Scout team make a suggestion and you can check it out!

Regarding ACMG 2015, quite possible, and sort of underway internally in ACMG as well since some time, with modifiers, probabilities etc, also welcoming input. But there is nothing stopping also making an SFMG or advocating an ESHG one. I would say the "extra" non-ACMG ClinVar categories caters to much what our tag and dismiss categories do, but yeah, a good national work group meeting theme rather than GitHub. 😊
