### ISSUE TITLE
SNP link not working - bug?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2460]
![image](https://user-images.githubusercontent.com/12525201/111803745-a30bcf00-88cf-11eb-9a50-72f22b6b5153.png)

The link "rs371429653;93175 " is not working as there is extra information. (it is not recognizedin SNPedia)

rs371429653 - correct rs number
93175 come from ClinVar

the "rs371429653;93175" is also copied in the ClinVar submission form (and is NOT accepted).
I've noticed this problem in some other family where i was preparing ClinVar submission

Hopefully  just a bug :)

**Comment by dnil** [comment]
Thank you! Sounds like the rsID format has changed a little from VEP. We'll check and hopefully it's an easy fix!

**Comment by dnil** [comment]
Heh, it turns out that was a MIP7 case, and this is an old style VEP ID column. If you rerun it all should be nice.

We will investigate if we can add a check for this as well, but it will be slightly delicate as COSMIC IDs for the cancer pipe are passed in the same column, but with a different separator format. 🙄

**Comment by northwestwitch** [comment]
This was fixed by #2474, closing the issue!
