### ISSUE TITLE
Fix gnomAD link for MT variants in build 37

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2479]
> > How is the situation in current master regarding the MT gnomAD frequency for genome build 37? Always None? Tested a few and looks like it. Both the values parsed from the VCF and the link.
> > While there isn't much to do for the values parsed from the VCF, especially because we are all moving to build 38 anyway, the link to gnomAD can be adjusted to use gnomAD version 3.11 regardless of the genome build, right? Perhaps in another pull request?
> 
> That sounds right to me; perhaps we double check that with HS & AJ before changing so we are very sure the links are correct, and document that so no-one else goes 37 with some old MT build and gets the wrong position. But there is no need to keep them for 37:
> 
> ```
> $ zgrep MT /home/proj/production/rare-disease/references/references_9.0/grch37_gnomad_reformated_-r2.1.1-.vcf.gz
> $ 
> ```
> 
> and
> ![Screenshot 2021-03-25 at 15 09 35](https://user-images.githubusercontent.com/758570/112486503-38014300-8d7c-11eb-9d8e-2e5498821629.png)

Moving this to a dedicated issue!

_Originally posted by @northwestwitch in https://github.com/Clinical-Genomics/scout/issues/2475#issuecomment-806829179_

**Comment by dnil** [comment]
Since we already have the hg38 ref MT, most other users are all on hg38 anyway, and there is really no content for hg19 there anyway we should be very fine. A tooltip or such indicating that links lead to 38 might be good for any legacy uses that we are not aware of, but honestly most centers probably used the NC_012920.1-spiked version of hg19 anyway before switching to hg38.
