### ISSUE TITLE
Webadress going wrong

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#2490]
Hi, the link for BEAN1 PubMed record in STR page under "Repeeat Locus- BEAN1" is pointing at wrong adress

**Comment by dnil** [comment]
That is actually the fault of the author of Stranger, and will have to be fixed there. 😆 

Will keep this open so we remember though..

**Comment by 47KW** [comment]
I see, but maybe I will get some points for posting anyway?


Från: Daniel Nilsson ***@***.***>
Skickat: den 30 mars 2021 10:43
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Håkan Thonberg ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Webadress going wrong (#2490)


That is actually the fault of the author of Stranger, and will have to be fixed there. 😆

Will keep this open so we remember though..

**Comment by dnil** [comment]
Ok, fixed in Stranger. Unfortunately the changes will not benefit you right away. First it will have to go into a reference repo for MIP, and then it will be included with the next release (tentatively after the Easter break). And even then it will only apply to fresh or rerun cases.

Feel free to use this link until then: https://pubmed.ncbi.nlm.nih.gov/19878914/

Thanks again!

**Comment by dnil** [comment]
To redeem your extra point(s) for this, I suggest you paste the above link as a new comment to the relevant BEAN1 variant(s). 😉

**Comment by 47KW** [comment]
“Use a good Scout when recruiting a Stranger”

Från: Daniel Nilsson ***@***.***>
Skickat: den 30 mars 2021 11:06
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Håkan Thonberg ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Webadress going wrong (#2490)


To redeem your extra point(s) for this, I suggest you paste the above link as a new comment to the relevant BEAN1 variant(s). 😉
