### ISSUE TITLE
coverage file missing

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2507]
![image](https://user-images.githubusercontent.com/12525201/114151131-1926b300-991d-11eb-9c55-9c9821c1343e.png)

fam 18150
there is not coverage file....
bug?

Michela

**Comment by northwestwitch** [comment]
We recently made a change because users analyzing cancer cases didn't want to see coverage and MT reports on the sidebar, so we are showing them only cases with `track:"rare"`.

This case which should belong to the track "rare" doesn't have a key/value `track:"rare"` in the database. I can see this difference comparing for instance with [this other case](https://scout.scilifelab.se/cust003/20166). 

Now I don't know why it is that and we'll need to check if there are more. Should be fixed now that I've added manually the right track to the case. Thanks for reporting the error!

**Comment by 4WGH** [comment]
thank you for such a fast fix :)

**Comment by northwestwitch** [comment]
Also missing the coverage and MT report: [15056](https://scout.scilifelab.se/cust003/15056), uploaded the day after 18150. Cases before and after these 2 look fine. I'm fixing the 15056 as well and closing this, but please reopen if you find any other of this.

I don't think we need to take further action because current cases looks fine. Must have been some bug in the process that has been fixed immediately after these 2 cases
