### ISSUE TITLE
Order ClinVar submission sub-items by date

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2519]
what is the order the variants get listed?
![image](https://user-images.githubusercontent.com/12525201/114458918-245d3580-9be0-11eb-9753-b6541a5fa1de.png)

- it is not the order they are added (which will be the best in case I want to check the variant  and the case just added to the submission went in
- not the order of coordinates
- no gene name
- no family name

It would be helpful to know  so I can cross check the data without having to look (randomly ) for it  
The longer the list of variants  (and cases) the more I need to look up and down to find the newly added variants and case (I need to change the name to each case so it is very important to do it correctly :)

**Comment by northwestwitch** [comment]
The order might reflect the database document IDs of the submitted variants. Changing it to order them by submission date (from the oldest to the newest or the other way around) shouldn't be so complicated.

**Comment by 4WGH** [comment]
it would be lovely in order of date and time 🙂🙂


________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 13 april 2021 09:46
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Clin Var submission page - question (#2519)


The order might reflect the database document IDs of the submitted variants. Changing it to order them by submission date (from the oldest to the newest or the other way around) shouldn't be so complicated.

**Comment by northwestwitch** [comment]
Hi, I was looking into this and I've realized that the date saved for the variants in the submission objects is not relative to when the scout user has added the variant to the submission, but it's a free text that the user fills in during the submission of the variant that is named `Date last evaluated`

![image](https://user-images.githubusercontent.com/28093618/116200216-5cb05800-a738-11eb-9d84-3c83135f8bb0.png)


This field corresponds to the "Date Last Evaluated" in [this file](https://www.ncbi.nlm.nih.gov/projects/clinvar/ClinVarDataDictionary.pdf):

![image](https://user-images.githubusercontent.com/28093618/116200444-a305b700-a738-11eb-9ff2-5bba43833f86.png)

It's a free text because as described in the manual above, it could be set to whichever date (only date - no hours, no minutes, no seconds etc) prior to the submission. For instance if you evaluated the variant 2 years ago you can set it to 2 years ago

The default value is the date you add it to the submission, and this date is saved in the database if you don't edit it. But of course if you edit it when sorting the variants by date, the sorting will not reflect when the variant was added to the submission.
Additionally, the sorting will be only sorting by date, not exact time it was added to the submission (even if you didn't edit the field when submitting).

Do you still want the sorting by date @4WGH ?

**Comment by 4WGH** [comment]
I never edit that date.

I whish trhe sorting of variants in the submssion file could be the order we add the variant to the submission.
So I know that the last added it is at the end of the list 🙂

that is the most logic in my mind 🙂


Does this answer to your question?








________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 27 april 2021 09:20
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Order ClinVar submission sub-items by date (#2519)


Hi, I was looking into this and I've realized that the date saved for the variants in the submission objects is not relative to when the scout user has added the variant to the submission, but it's a free text that the user fills in during the submission of the variant that is named Date last evaluated

[image]<https://user-images.githubusercontent.com/28093618/116200216-5cb05800-a738-11eb-9d84-3c83135f8bb0.png>

This field corresponds to the "Date Last Evaluated" in this file<https://www.ncbi.nlm.nih.gov/projects/clinvar/ClinVarDataDictionary.pdf>:

[image]<https://user-images.githubusercontent.com/28093618/116200444-a305b700-a738-11eb-9ff2-5bba43833f86.png>

It's a free text because as described in the manual above, it could be set to whichever date (only date - no hours, no minutes, no seconds etc) prior to the submission. For instance if you evaluated the variant 2 years ago you can set it to 2 years ago

The default value is the date you add it to the submission, and this date is saved in the database if you don't edit it. But of course if you edit it when sorting the variants by date, the sorting will not reflect when the variant was added to the submission.
Additionally, the sorting will be only sorting by date, not exact time it was added to the submission (even if you didn't edit the field when submitting).

Do you still want the sorting by date @4WGH<https://github.com/4WGH> ?

**Comment by northwestwitch** [comment]
> Does this answer to your question?

Yes, thanks!
