### ISSUE TITLE
Meaning of filter warning "Gene not included in case clinical list" is not at all clear for users

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2664]
Especially when they filter using HPO genes. In that case they get long list of genes in that warning and they wonder why. 

This is just a warning clarifying that genes used in the search are not in the panels used to analyse the case (nothing weird with it). But the warning is worrisome for many:

Suggestion:
- Change the color of the alert to green, instead of yellow
- Change the text of the alert to be more self-explanatory

**Comment by mhkc** [comment]
Could you please define what a "case clinical list" is :)

**Comment by dnil** [comment]
Good idea - it is probably too obvious to us by now. It's a few different updates, of genes panels and occasionally phenotypes.

The way we have things set up in Solna, each case is run with a clinical panel coinciding with the original gene panels present on the case at load. The variants are hard filtered ("selected") to avoid variants outside the genes on the list. Hence it becomes interesting to know what genes were on the clinical panel or select list, since if you wish to search for variants in a gene outside of it, you cannot find them unless you load the full, research list. Not loaded is rather different than not present. I believe in the beginning Lund ran everything as "research" but maybe that has changed?
