### ISSUE TITLE
Bad gateway error in causatives page

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2665]
In version 3.35.0 we frequently get "Bad gateway error" in the /causatives page

**Comment by northwestwitch** [comment]
I think this issue was fixed in #2613. You need to update the indexes of your prod Scout. @dnil could help with more detailed instructions

**Comment by dnil** [comment]
Hm, we had out of memory errors with it before. Well, I would strongly suggest updating the indices as per #2613 anyway, but not really for the causatives. For that part I just moved the sort from the db engine to the web server. For us thats a big improvement - do you have more constraints there possibly?

**Comment by dnil** [comment]
Or do you get any nice log messages that you could share from the crashes? Normally we get an admin log email with each crash that caused a Bad gateway, where one can usually see what is going down. I had to fix the sort a few times since there were some unexpected configurations of gene symbols on the variants. Perhaps you have one or two interesting versions of that that we dont have?

**Comment by dnil** [comment]
The immediate issue was solved with #2673. It would be very helpful to the overall index size if we take the time to rewrite this last(?) large use of variant_id queries to _id, but let us call that part an enhancement instead.
