### ISSUE TITLE
Assign phenomodels at the case level

### ISSUE THREAD

**Issue by oliviajhenry** [Clinical-Genomics/scout#2686]
Hi Scout team,
I know this has been on the agenda for a while but just thought it might be useful to make a formal request. We are hoping to use phenomodels in a study we are currently carrying out to test the efficacy of deep phenotyping in WGS analysis. 
Cheers,
Olivia

**Comment by northwestwitch** [comment]
Hi Olivia! I know that that you've been waiting for a while. The phenomodels feature is quite big and we have been working on features that are quite urgent and have an immediate impact on a broader group of users (for instance Scout Cancer, unifying the codebase with the Lund facility, RNA analyses visualization). Given the current resources working on Scout we've been forced to prioritize down this feature. Your request is not forgotten and we'll eventually implement it. Phenomodels has been assigned with prio2 tag for Q3 of 2021 (https://github.com/Clinical-Genomics/project-planning/issues/257). You can monitor the status there if you have access or directly on the original issue (#1952). Closing this issue since it's a duplicated of #1952.

Best,
Chiara

**Comment by oliviajhenry** [comment]
Hi Chiara,

I hope you’ve been well! 
That sounds fair enough, I know you have a huge workload at Scout. 
Thanks for directing me to the appropriate case, will check in there for progress. 

Best,
Olivia
