### ISSUE TITLE
Help with coverage and understanding 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2695]
Hi, 

We are having some problems interpreting manually looked up variants in IVG. Hoping for some clarification / suggestions on how we should proceed. 

Here we have the coverage metrics in percentage over the whole panel, which is for this particular case: 429X 100%

![image](https://user-images.githubusercontent.com/62098218/120785762-ba9d4000-c52d-11eb-92f5-f7e40fb6727e.png)

If we go into a variant view and look at the GT call box we usually see a coverage of roughly ~1000-1500X, however if I go into IGV for that particular variant I see a coverage of ~2000-4000X. This is not variant or case specific. 

Our problem arises when we have follow up sample for the myeloid analysis, and for these patients we go manually into the genomics coordinates, like for this variant: Here  we see 4879 reads and 3 reads for the alternatvie allele T. 
![image](https://user-images.githubusercontent.com/62098218/120787932-297b9880-c530-11eb-8705-0518a94e728c.png)

The question here is first of all: 
1. Can we trust the 3 reads for T as IGV does not always represent the coverage metrics and the GT call (as described above)? 
2. How much reads from IGV is filtered out? 
3. How can me in a easy way monitor these manually genomic coordinates which we look up, due to the increpancies described above? 

Thanks !! 

Hälsningar Hero

**Comment by northwestwitch** [comment]
Hi Hero, I think you should trust the numbers shown in the GT box (comes from the VCF file with the calls) and not counting from what you see in IGV (numbers computed dynamically from the cram alignment file every time you move to a new locus). 

IGV desktop (and probably also the browser version we have integrated into Scout) allows even to substitute the computed coverage data with custom pre-computed data to have better coverage estimates, check the documentation here: http://software.broadinstitute.org/software/igv/alignmentdata#coverage

**Comment by dnil** [comment]
Hi Hero! I believe we all had a long discussion on email and in person on a very similar theme back in April? Whats new? 😬

1. You need to be very careful when counting bases in IGV, since it is prone to downsample. If the count for a high coverage sample is to be trusted is rather a question for the IGV developers, but let us say that we trust it until anyone proves differently, and if so we have that fixed?
2. I think we covered that part well in the email conversation from April. At least all reads below Q<22.5 will not be used in VarDict. And then there is the Balsamic 1% noise filter.
3. Let's see what we can do, but it depends on why you looking them up!
- Are you still using MPS for minimal residual disease testing? I thought we agreed targeted methods that offer a greater linear correlation to input at low fractions are better for this purpose; cf local digital droplet PCR projects by eg Cecilia Arthur? If you still want to do this, you probably need a more interactive approach where you submit positions to be tested - e.g. by indicating that all variants from a previous sample should be genotyped.
- Or is this for know hotspot positions where detection by screening has failed in some way before? If the latter, I would suggest also opening this on Balsamic and discussing the possibility to run it with a HotSpot-variant set, ensuring genotyping on all desired variants. That way you could have them represented in the variant call as well?

**Comment by dnil** [comment]
😊 Did you also worry about the coverage vs % covered, since you show that picture? You would expect the average coverage at a locus to be considerably higher than the lowest depth at which the covered bases fraction is still 100%. Most bases will be covered more than the lowest covered one. In a PCR free wgs things are a little bit different, but in a panel I would expect wild differences.

**Comment by northwestwitch** [comment]
The variant in the picture she showed doesn't look to be a downsampled area (no black bar under the coverage track) but I still wouldn't trust those 3 reads only because IGV shows that number. What you say about downsampling is true @dnil, never trust those IGV numbers, especially in the highly covered regions.

**Comment by dnil** [comment]
I know, but the last variant they asked about was. 😸
Do you have an example where the the count does not work, or is expected not to work, except when downsampling? The docs do give the option to override the track, but I believe that is mainly for if you want to show approximate coverage also on zoomed out views, where the built in count would be too slow.

**Comment by heronikdin** [comment]
Hej! 
I am so sorry for not answering, to be hones I completely forgot... 

But you are right, we have had this conversation before and thank you both for the exaplanations. We are using this for MRD monitoring, but do mention in the report that the Myeloid panel is not optimal and has lower sensitivit. We have set up mrd monitoring with eg qpcr for certain variants, and we for some we can send then to uppsala for ddPCR.

Thank you again! 

Hälsningar Hero

**Comment by northwestwitch** [comment]
No worries! 😃
