### ISSUE TITLE
Display VCF filters as QC bages in scout cancer

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2722]
I was going to add the annotated VCF filters as badges for the cancer variants list view.

Scout stores these flags as "filters" in the database and are included in the `variant_obj`.

We would like to apply different formatting to these flags in a way that would be extendable and meaningful for different sites. I was therefore thinking of storing the configuration in the scout database, much like how we do with the dismissal terms.

What do you think?

**Comment by northwestwitch** [comment]
If it's standard filters we could also include them in the constants. We could benefit from having them as well!

**Comment by mhkc** [comment]
In our pipeline some filters are set by the variant caller and some do we annotate ourselves. I do think it would be good to have a default set of filters i think we do need to have them configurable to some extent.

**Comment by northwestwitch** [comment]
We could also sharpen up the parsing of these filters values, so that we collect the required values regardless of the filters, perhaps

**Comment by northwestwitch** [comment]
What type of filters (and which values) would you like to parse?

**Comment by mhkc** [comment]
We dont have a comprehensive list as there are several different filters from multiple pipelines.

The filters are being parsed correctly by scout as can be seen in the snippet below. Filters in this context relates to the content of the filters column in the vcf file which can only be either PASS or the names failed filters (strings). 

```
"filters" : [
        "FAIL_PVALUE",
        "alt_allele_in_normal",
        "WARN_VERYLOW_TVAF",
        "t_lod_fstar",
        "low_t_alt_frac"
],
```

**Comment by bjhall** [comment]
Just to make sure we're all on the same page:

We're talking about the strings in the FILTER field in the VCF (the 7th field). This is simply a list of semi-colon separated strings (defined in the header). I think Scout is already parsing and loading this, right?

What Markus is talking about is adding the possibility to show a selected subset of these FILTER strings in the variant list to "warn" the user that something is fishy about the variant.

For example, our somatic variant pipeline add filters such as "WARN_STRANDBIAS" or "WARN_VERYLOW_TVAF" to indicate that the variant has a strand bias or very low tumor variant frequency, respectively. We show these as badges in the variant list in Coyote.

The problem is that theses are completely arbitrary and there is no standard for how to name filters. You probably don't want to show all filters (since some variant callers tend to add a lot of useful or less useful filters). Therefore it would be nice to be able to somehow tell Scout which filters it should show and how to display them, maybe in a config-file?

To emulate the behaviour of coyote (just as an example), one could imagine a config like this:

```
filter_badges = [
  {
     "filter": "WARN_STRANDBIAS",
     "abbreviation": "SB",
     "description: "Strand bias",
     "status": "warning"
  },
  {
     "filter": "WARN_VERYLOW_TVAF",
     "abbreviation": "XLO",
     "description: "Variant has very low tumor variant frequency",
     "status": "warning"
  },
]
```

The `abbreviation` is what would be displayed in the badge, and `description` would be shown as a tooltip. The `status` would determine the color of the badge (eg. yellow for `warning` and red for `fail`)

Hope that makes sense. I'm simply describing how this is solved in Coyote, I don't mean that it has to be identical i Scout.

**Comment by hassanfa** [comment]
We also have bunch of filters specific for our workflow. They are mostly custom tags and filters. Maybe we should also add those?

In BALSAMIC, there are 7 different filters used as well. Alongside somatic, loh, likelysomatic, and couple of others. Should we add them all as constants? This could be quite useful 👍🏽

**Comment by northwestwitch** [comment]
I don't see any problem adding them all as constants. The problem may occur if different facilities want to have different settings for the same filter

**Comment by hassanfa** [comment]
I think to solve that, we should avoid using general filter names. Adding a prefix to indicate center/software can be useful. In BALSAMIC, all filters and tags have a `balsamic_` prefix.

**Comment by mhkc** [comment]
Wouldnt that soon become bloated and hard to manage? Especially if different sites are to have different prefixes. Then it would be better to let the formatting be defined in the config.py or to load the configuration into the database.

**Comment by northwestwitch** [comment]
By the point of view of a new facility, it would perhaps also be good if as many filter settings are already available in Scout constants. So it's less work for them to define and curate their own. On the long run It would be also good to try to unify the filter definitions used for when 2 facilities use the same tool

**Comment by mhkc** [comment]
Not having these in the constants file doesn't mean that there are no defaults. We could either have a defaults json file which are being loaded when the database is being setup (just like the evaluation terms), or just have a default dictionary in the config file.

I do think we should strive to unify as much as possible but it seems to me that is a process that takes a lot of time to mature.
