### ISSUE TITLE
Use latest gene panel for panel overlap in variantS and variant view

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#2733]
It appears that, when filtering the variant list with gene panels it is always using the latest version of the panel instead of the version saved in the case object in the database. I can only confirm that this is happening för SNVs but possibly also for other variant types.

Not sure if this is the indented behaviour or not. If it is the intended behaviour, feel free to close the issue, bit I think it should be reconsidered :)

**Comment by dnil** [comment]
Hi @bjhall! It is indeed intended behaviour, since #2007. There are also angry color cautions and clear text messages describing this (e.g. #2077) on both the case and variantS pages. The logic is that it is highly rare to want to actively choose to use what more up to date clinical knowledge has determined to be a better panel. In all but a small number of specific use cases, the user would be better off analysing from the latest version.

It would always be possible to use an arbitrary gene list or single genes if the use case is for detective work regarding an old deviation or delta to newer case. If the reason is that the case was actually hard filtered with a panel, the "clinical list" saved on the case does take care of that, and warns if genes in the latest version of the panel were not on said clinical list.

**Comment by bjhall** [comment]
Thanks for the explanation. Personally I agree that you'd typically want to use the latest version. The problem is that our geneticists are using Scout as an archive and for tracability reasons it can be a bit confusing when you go back to an old case to find a large (or small) number of unevaluated variants (the case where we noticed this was from last week, and we had a large update of some gene panels today)

I'll ask if the warning is enough for them!

I suppose it should be considered a bug that the "lists of panels a gene is in" in both the variantS and variant view still use the old behaviour?

**Comment by dnil** [comment]
Good! Yes, the archive part was discussed before the introduction, and it was agreed that the case reports were sufficient  - -- and that one can if need be recreate the behaviour for troubleshooting or clearing ones conscience in case of deviations or discoveries at other labs. Just a quick look in the gene panel page and history there usually tells the story better than the original panel on the case would. 

Well, the warnings are intended to be measured to the degree that the warning for clinical list should use the original case upload panel version, whereas the missing gene symbol warnings etc should be for the latest, actually used version. It is entirely possible that this logic is flawed somewhere, but please give a specific example that you feel could be handled better that we can discuss from!

**Comment by dnil** [comment]
Oh, the "number of panels" badges you mean? Quite possibly, yes.

**Comment by dnil** [comment]
If you don't mind we could re-title this issue to solve that problem instead? It can easily be recreated on e.g. demo by editing the test panel1 to remove a gene present on the case, say IFT43. It is no longer on the panel, and won't be found using it, naturally but then explicitly searching for it on the case still shows it counted in the "number of overlapping gene panels":
<img width="368" alt="Screenshot 2021-06-28 at 18 59 10" src="https://user-images.githubusercontent.com/758570/123675772-64c56a80-d843-11eb-9618-75695005e75f.png">

**Comment by bjhall** [comment]
Yes that's what I meant (sorry for being unclear, I was typing on my phone...)

I think the same bug affects the variant page's "Gene panels":

![bild](https://user-images.githubusercontent.com/11991860/123759249-02f71600-d8c0-11eb-9a08-72015dc8bac8.png)
