### ISSUE TITLE
Filtering on genes not in gene panels does not work

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2760]
Filtering SNVs by genes that are not part of the gene panels associated with a case when it was loaded into scout does not work. This is regardless if the additional genes were added to the dynamic panel in the case view or by searching for them in the "HGNC Symbols/Ids (case sensitive)" box in variants list view.

The bug was introduced in Scout version 4.32.

**To reproduce**
1. Setup scout instance
2. load case 643594
3. goto `/cust000/643594`
4. Add TBX1, POT1, SIRT3, SLC9A3 to the dynamic panel
5. goto `/cust000/643594/variants`
6. click filters > HPO gene list button
7. Ensure that "Test panel" has been deselected form the filters

**Outcome**
 - Only variants located on POT1 and TBX1 genes that are part of the "Test panel" are displayed.
 - Variants, `cust000/643594/e0163bf1348a4e2723148b490f3fc224` and `/cust000/643594/6b3f7cbc1d25fa84bb5cbb190055c728` (rank 1 and 5) are missing from the output

**Comment by northwestwitch** [comment]
Could it be that those variants were not loaded, since they don't belong to
the case panels and that is the reason why you don't find them when
filtering by those genes? 🤔

**Comment by mhkc** [comment]
The variants are loaded into scout. You can see them in the variants list by deselecting the gene panel (Test panel) and refilter the variants

**Comment by northwestwitch** [comment]
Ah ok, then it sounds like a bug!

**Comment by dnil** [comment]
Sorry, I'm on vacation, but I don't quite hear the bug here - though I can't test it from the phone. Does it affect the research variants search?

The clinical variantS ought to show a warning when a non-clinical gene is searched, encouraging the gene of interest to be added to a clinical panel. Have you tried adding those genes of interest to a clinical panel for the case? Are they still missing?

It would not be impossible to show any non-clinical gene that for some arcane/development reason is loaded as clinical with a warning, but that would be a feature request and one that we would have to discuss at least briefly to make sure it does not risk making it too easy to  unintentionally reveal something.

**Comment by ViktorHy** [comment]
Does this stem from differences in how we analyze variants in scout? Do I understand this correct, if you load a case without a default gene panelyou are free to filter on any gene. But when loaded with a default panel you can only filter within this panel? Has this always been the case, or this a new thing?

I was under the impression that you even intersected your VCFs against the gene panel before you loaded them scout? If that's the case why the extra precaution? 

I think at least there should be some note saying that the filter is not global, but rather within gene panel. I myself would really want a global filter on gene symbol, outside whatever gene panel was loaded.

**Comment by ViktorHy** [comment]
I withdrew my post, I realized the issue now. So the problem lies within filtering within a selected gene panel. So say you have loaded a case with a gene panel consisting of 4 genes. While this panel is selected for the case say I want to filter out only variants for one of these genes. That's not possible, don't know whether this has ever been possible, I want to remember it has been?

Did that make it somewhat clearer?

**Comment by ViktorHy** [comment]
> 
> 
> The variants are loaded into scout. You can see them in the variants list by deselecting the gene panel (Test panel) and refilter the variants

I think dnil is correct in saying that it expected behavior. If you have selected a gene panel it should only ever be possible to list variants within this panel. See my above post for what I believe might be a bug however.

**Comment by mhkc** [comment]
Okay, Then I understand. We have misunderstood how the filter is intended to be used and therefore when the function changed it caught us off guard.

I am closing this issue. Thanks a lot and I am sorry to disturb your vacations!
