### ISSUE TITLE
RNA data not visible in Scout

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2847]
In a meeting with Anders and Henrik today, it became apparent that we're supposed to be able to view RNA data in Scout. But we cannot. Here are three example families where RNA data exist and apparently should be visible for us:
families 52, 14022, 17172

individual ID for the DNA samples: 52-1-2A, 52-1-4A, 52-2-1U, 52-2-2U; 14022-I-1A, 14022-I-2A, 14022-II-1U, 14022-II-2U; 17172-I-1A
DNA from 17172 has been sequenced twice, from blood and from muscle, but the RNA data comes from blood so I'm guessing it will be linked to family 17172 and not 17172-muscle.

Happy bug hunting ;) Thank you!

**Comment by dnil** [comment]
🐞🔍  Thank you, thank you! We will take a look at the specific cases, but I can confirm that we do indeed support that, and have RNA loaded for some cases.

**Comment by dnil** [comment]
Yeah, e.g. 17172 has fusion reports available for download, and keys pointing to splice junction tracks. We'll fix: it could be an issue with the upload system for some particular new configuration, but more likely it is just an issue with the RNA-button being inadvertently hidden since there are no genome DNA crams for this case.
