### ISSUE TITLE
MANE transcript fix - inconsistent behaviour

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#2862]
In https://github.com/Clinical-Genomics/scout/pull/2683#issue-658334675 , the aim was to fix three things with MANE annotation: MANE Select and Plus Clinical should get green badges, version number should be added to MANE Select, and finally MANE Select should be shown first in the list of transcripts. From my experience with the Lund installation (v4.38), the first two objectives are solved, but the third item is inconsistent. Sometimes the MANE Select transcript is indeed shown first, but in other instances it is further down the list (see attached screenshot). I haven't been able to find a pattern for this inconsistency.
![MANE Select](https://user-images.githubusercontent.com/12267779/132512297-4f28f1df-c315-4c72-9383-31e814a964d8.png)

And while I am on the subject, it would be good to add version numbers also to the (few) MANE Plus Clinical transcripts, since that is in line with how MANE is supposed to be.

**Comment by northwestwitch** [comment]
Hi! I haven't tested this change since here in Stockholm we are still using build 37 (we'll hopefully switch to 38 soon) but by looking at the code it seems that gene transcripts are not ordered by the presence or absence of MANE transcripts so they're shown in the order they are retrieved from the database. Perhaps we could fix the database query to return transcripts which have a MANE tag first.

Other possible improvements:
- Move the code preparing the content of this table to the backend, to have a better control over what is shown and simplify the jinja code of the page 
- For genes in build 38, parse MANE information when the genes are created. This could be done by extracting `MANE Select` and `Mane Plus Clinical` entries directly from the transcript information retrieved from the Ensembl Biomart used to build genes:
![image](https://user-images.githubusercontent.com/28093618/133048821-a11c34c9-1137-4c40-b05a-e2740025ccf6.png)
This would actually be a great improvement, worth of a PR of its own!
