### ISSUE TITLE
Configure tsl for http requests for the rest API

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/scout#2875]
The rest api data needs to be encrypted with tsl for https requests

**Comment by dnil** [comment]
Hi! Could you clarify why? Normally the app only serves bare html for the reverse proxy, which in turn handles the external https request, securing it with TLS. When still internal on localhost there is surely not much use in a TLS , and when outside, only the reverse proxy prod should be open?

**Comment by dnil** [comment]
To summarise from the meeting, this is a servers issue rather than a Scout issue, if any?

gunicorn serves http requests with scout app contents locally on localhost for a specific port, like 8083 for stage.
Then nginx proxies any calls to https://scout-stage on clinical-db to http://127.0.0.1:8083, keeping the external traffic under TLS encryption.
Attempts to access the api directly from http from the outside (not localhost) should just end with a redirect to https, regardless if authenticated or not.

And any unauthenticated API requests via https would end with a redirect to the login page for Scout.

```
 $ curl -I http://scout-stage.scilifelab.se/api/v1/cust000/cases
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 14 Sep 2021 12:57:56 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://scout-stage.scilifelab.se/api/v1/cust000/cases

$ curl -I https://scout-stage.scilifelab.se/api/v1/cust000/cases
HTTP/1.1 302 FOUND
Server: nginx
Date: Tue, 14 Sep 2021 12:58:34 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 285
Connection: keep-alive
Location: https://scout-stage.scilifelab.se/?next=%2Fapi%2Fv1%2Fcust000%2Fcases%3F


```

**Comment by dnil** [comment]
But, if you found a way in, we are eager to know! That would not be the first time in history something is not as safe as it seemed.😬

**Comment by elevu** [comment]
ok, looks great, I guess I have to use less Postman and more curl!
