### ISSUE TITLE
Docker image extremely slow to build

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2908]
To build the Scout image from Dockerfile is extremely slow (today it took 13 minutes from my computer). I think it's due to the fact that numpy requires a long time to be built. We could perhaps base the Scout image on an image that has already a pre-installed numpy?

The current Dockerfile has a multi-stage build and I wonder why.. Was there some package that was difficult to install in just one go?

**Comment by dnil** [comment]
For me, the cyvcf2 build from source and the apt-get-updates are the big performance hogs. I guess they will put different demands on your setup: the first requires a bit of cpu, the latter bandwidth, and not only on your end. I had issues with that on scripted solutions since the repo hosts dont want to be spammed.
