### ISSUE TITLE
Filter and export 

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/scout#2954]
Hej!
När man använder ”Filter and export” (gula knappen),   för att ladda ner SNVs eller SVs, 
blir det max 500 varianter exporterade, kan ni ta bort max antal varianter? Alltså möjlighet att ladda ner flera tusen varianter, det är bara text filer och filerna sparas inte på CG server, så de tar inte plats
Ibland har jag 2000 varianter att ladda ner, sprida över alla kromosomer då måste jag ladda ner krom efter kromosom för enskilda prover
Det tar jätte lång tid per prov!!
Tack!!

**Comment by dnil** [comment]
Hej! I princip kan vi nog det, även om det tar lite tid att köra. Men, det här har historiskt alltid varit om något annat. 😁 
Varför behöver du ladda ner så många varianter? Om för att säg spara, kunde man inte bara filtrera direkt på vcf:en? Om för att annotera eller söka vidare med, vore det inte bättre om vi kunde lösa vad du nu vill ha dem till i systemet? Om du visar vad de ska vara till kanske vi kan automatisera det hela vägen istället?

**Comment by terestahl** [comment]
Hej
Jag har inte tillgång till vcf, var kan jag ladda ner vcf?
Jag vill filtrera för antal AD reads som stödjer den AD variant, det finns inte sån filter för mig/somatic pipeline

**Comment by terestahl** [comment]
Scout it is very slow, it takes 5 min to upload IGV pictures, difficult to work actually

**Comment by dnil** [comment]
Hi again, thanks for the reply!

In the future, please try to keep each issue focused on one thing. That makes it easier to see what is going on, and close issues that are solved. Also it will shorten responses. 😅 

As for slowness, Im not seeing it so it is presumably somewhat case specific. Could be that certain areas are a little slower today since we swapped servers yesterday and caches need to refill, but 5 mins sounds way much for any page!
What does "upload IGV pictures" mean - do you mean loading the IGV alignment viewer page or something else? What case?

Similarly, what does AD reads mean? Something different than e.g. "Min alt count", "Depth". "Tumor AF", "Normal AF" can't solve? And this is something that you actually in a clinical setting need to triage, but dont have in the Balsamic pipeline? Or is it more like a development step where you are trying to figure out good values for this?

While I have a hard time understanding how this would be a part of a diagnostic/triage step rather than the pipeline itself, 
if the data you want to filter on is actually exported using "export" it should be easy just to add a filter option for it?

**Comment by dnil** [comment]
And yeah, VCFs would be available from the general download area for your institute, if you ordered them (like clinical-delivery.scilifelab.se / caesar.scilifelab.se. Or you can always ask for them for a particular case in a support ticket!

**Comment by terestahl** [comment]
OK

I need to look at each SV en IGV as there are no annotations to judge after balsamic, but I want to look at the most important ones
I can only download a txt file from scout and count the alternate reads to try to find the interesting variants (the alternate reads are not displayed in the first page of scout, and I can not click on each variant when I have hundreds of variants to find out the AD-Reads counts) so I have to use the export function and get a txt file, that is what I need to filter all variants and this I am doing manually

These:
AD_reference_MOL2470-21T     AD_alternate_MOL2470-21T              GT_quality_MOL2470-21T          AD_reference_MOL2508-21G-2021-27483-03            AD_alternate_MOL2508-21G-2021-27483-03

I count the AD_alternate to find the best SVs that can be relevant for the case

Sorry Ih ave to leave now

I can answer better if you do not understand

**Comment by dnil** [comment]
Ok, I still don't fully understand what you do, but at least there must be a filter option missing on the cancer-SV page. Super cool that that page is now in good use, and I'm sure we are missing more than one thing! We can have a look at the cases you mention and see if we can't understand!

Perhaps we can also have a short meeting / hangout session sometime soon and you show us what you do, and we can try to implement something that will help you.

**Comment by terestahl** [comment]
yes. better to discuss than only write
I am happy to meet
thanks



________________________________
