### ISSUE TITLE
CADD score filter monday-issue! 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#304]
Thank you kindly for the quick inclusion of CADD score filtering! Will make a couple of our doctors very happy.

One major caveat though: the current version seems to filter out unknown CADD scores as well (similar to the unknown frequency bug)! Not intended usage..

**Comment by moonso** [comment]
Is this not a philosophical question?
If the variant have not cadd score, probably due to beeing a structural variant, it does not have a higher cadd score that the treshold..
I don't really care which way to see it but we should all agree on how the filter should work.

**Comment by dnil** [comment]
;-) Well, I do see your point in general, but in this context I'd argue there can be little doubt. We wish to filter out/hide variants that have some kind of evidence of being benign. A NA value in a filter should not cause the variant to be dropped. It simply says CADD has no opinion, and another method of ascertainment should be applied.

Compare to the frequency issue: we wish to filter out variants with evidence of being common. This does not imply that we wish to drop stuff not seen before. NA is different from 0.

**Comment by moonso** [comment]
Hi, 

I think there is a significant difference between CADD and frequencies. 
A non existing frequency have a meaning, namely that the variant most probably have a very low frequency which most of the time means that it is very interesting to us.
A non existing CADD score most probably mean that the variant is a SV since it should be calculated for all possible SNV:s in the entire genome.
The problem with including NA CADD variants is that if you set the filter high the result will almost only include SV:s which will clog the result.
Is it not better to use another filter to see those?

We will discuss this further on the user meeting this wednesday (7/9).
Hope to see you there!

**Comment by dnil** [comment]
Still see your point, and think an option named "CADD filter" should not be used to remove all novel indels, as if CADD had called all of them benign? A separate filter on in-frame deletion, low quality calls or such would be more transparent. 

Discussion sounds good. See you!

**Comment by henrikstranneheim** [comment]
I have fogotten to mention that MIP uses a reference which only contains CADD >= 10. So not all snvs are annotated with a CADD score.

**Comment by dnil** [comment]
Right, that is common practice. Since variants are ranked with multiple information sources anyway, I still think it makes little sense to loose potentially high impact novel indels for the luxury of looking at a clean CADD-filtered list.

**Comment by henrikstranneheim** [comment]
We are looking into 2 options:

1. Possibility of including NA data 
2. Only inlcude true data

**Comment by robinandeer** [comment]
implemented!

**Comment by dnil** [comment]
I'm afraid this has broken again. Checking the CADD inclusive option does not seem to bring back variants without CADD to the query results.
