### ISSUE TITLE
Customer can't update gene panel

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/scout#3081]
Problem described in this ticket: https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=45865

I tried to update a panel and I fail as well. I can successfully create a panel. Then when I try to modify that panel the file never "shows up" and the "Gene panel file"-section keeps telling me "choose file".

**Comment by northwestwitch** [comment]
I've tried updating test panels on Scout stage with the files provided by the user, using the same software version installed on prod server and it works. I think the problem is that it is not super clear what the steps are, and we can improve on this regard:

1) First problem I see is when you upload a file using the form, after the uploading it still says "choose file", it could be changed into the name of the file uploaded:
![image](https://user-images.githubusercontent.com/28093618/148897308-d8c008a5-2fac-4131-bad8-8e7b24ab90f6.png)

2) Second problem is that the page should probably redirect to the page of the panel to be updated, where the list of proposed changes is:

![image](https://user-images.githubusercontent.com/28093618/148897539-8a879db1-24a0-4d62-b560-33fa81ac3e8f.png)

To update the panel the user has to save those changes and the update should work.


I'll explain her this and in the meanwhile I'll try to fix those 2 things!
