### ISSUE TITLE
General case reports generated in SCOUT

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3142]
Regarding new update

•	Export general case report to PDF using PDFKit instead of WeasyPrint
•	Do not include coverage report in PDF case report since they might have different orientation

**We would like to have the coverage report included in the general case report**

**Comment by dnil** [comment]
We quite understand. The problem is the balsamic coverage report is large, and hence in landscape mode. Extra columns can get pruned away currently, which is kind of worse, as one may think it is complete. We will try to find a solution, either through modifying that report or inventing a way to merge them losslessly anyway.

**Comment by northwestwitch** [comment]
I'm checkin this now and the problem is not only with the content of the balsamic report: also coverage report for RD case are incomplete when exported to PDF, that's why I've decided to remove it from the general report.

![image](https://user-images.githubusercontent.com/28093618/152971788-9bbda4d5-0c02-4cfc-85ac-c8f757cddd16.png)

I'm looking into it to find a solution!
