### ISSUE TITLE
Scout user meeting 15/6 @ 9-10.30

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3263]
Time: Jun 15, 2022 09:00 AM Stockholm
Zoom link: https://ki-se.zoom.us/j/64021668001?pwd=NXZzTjBNaUZsd0pybHBTVEtLYW5Mdz09

## Recent changes
- Dark mode and Bootstrap 5
- Allow marking case as solved without defining causative variants
- Export VCF variants to Beacon -- upcoming feature
- Added more somatic variant callers -> Balsamic v9 SNV (TNScope, TNscope_UMI), develop SV (DellySV, CNVkit, ASCAT, DellyCNV, TIDDIT)
- Download .cgh files from cancer samples table on cancer case page
- cDNA and protein changes displayed on institute causatives pages
- Point Alamut API key docs link to new API version
- Rank score results now show the ranking range
- Add an IGV.js direct link button from case page
- Fixed updating genes in build 37 - Need to fix an error in update HPO feature! --

## Discussion points
- Phenotype-based priorization
- Managed variants different for each institute
- SESSION_TIMEOUT_MINUTES -- suggestion to time out connection after 10h of inactivity
## Content prioritisation
- Bugfixes
- Pipeline features (archive case-count, mitosign, ...)
- https://www.menti.com/xj99xmo2xs
## Major release pending
- Launching the app using a .yaml config file will be deprecated
- Loading cases using .ped files will be deprecated
- Changes in app config file relative to loqusdb settings (accepted format: dictionary, strings and lists will be deprecated)
??
## Pipeline updates
- MIP minor
- Balsamic
-

**Comment by dnil** [comment]
- Issue prioritisation (updating the below) 
![Uploading Screenshot 2022-03-23 at 11.30.11.png…]()

**Comment by dnil** [comment]
Suggested discussion points:
- per institute managed variants (#3379)

**Comment by angelicadelgado** [comment]
Suggestion: Phenotype-based priorization of variants

**Comment by dnil** [comment]
> Suggestion: Phenotype-based priorization of variants

Thanks! We have as you know opted to leave the phenotype out of the rank. We can discuss this again: just a brief summary of the current constraints. Prioritization/ranking is still at the pipeline stage. This means the attending clinician would have to fix the detailed phenotype up front around when ordering the case. As it is, only a panel set is (including OMIM) is typically picked before loading. The phenotype then can decide the gene list, as in either just looking at a single panel, picking genes with HPO terms and/or using phenomizer. The thinking goes that variants that are high after that phenotype-selection, would still mostly be high on a phenotype-rank. It is not trivial do devise a scoring scheme that weights phenotype matching to detailed leaf terms, broad trunk phenotype categories vs genes with more or less evidence for phenotype and contrast those quantitatively against the molecular effect of the variant. Some attempts do exist, e.g. exomiser. Do you have a particular system in mind that you like?

**Comment by northwestwitch** [comment]
Software releases since previous user meeting:

## [4.54]
### Added
- Dark mode, using browser/OS media preference
- Allow marking case as solved without defining causative variants
- Admin users can create missing beacon datasets from the institute's settings page
- GenCC links on gene and variant pages
- Deprecation warnings when launching the app using a .yaml config file or loading cases using .ped files
### Changed
- Improved HTML syntax in case report template
- Modified message displayed when variant rank stats could not be calculated
- Expanded instructions on how to test on CG development server (cg-vm1)
- Added more somatic variant callers (Balsamic v9 SNV, develop SV)
### Fixed
- Remove load demo case command from docker-compose.yml
- Text elements being split across pages in PDF reports
- Made login password field of type `password` in LDAP login form
- Gene panels HTML select in institute's settings page
- Bootstrap upgraded to version 5
- Fix some Sourcery and SonarCloud suggestions
- Escape special characters in case search on institute and dashboard pages
- Broken case PDF reports when no Madeline pedigree image can be created
- Removed text-white links style that were invisible in new pages style
- Variants pagination after pressing "Filter variants" or "Clinical filter"
- Layout of buttons Matchmaker submission panel (case page)
- Removing cases from Matchmaker (simplified code and fixed functionality)
- Reintroduce check for missing alignment files purged from server

## [4.53]
### Added
### Changed
- Point Alamut API key docs link to new API version
- Parse dbSNP id from ID only if it says "rs", else use VEP CSQ fields
- Removed MarkupSafe from the dependencies
### Fixed
- Reintroduced loading of SVs for demo case 643595
- Successful parse of FOUND_IN should avoid GATK caller default
- All vulnerabilities flagged by SonarCloud

## [4.52]
### Added
- Demo cancer case gets loaded together with demo RD case in demo instance
- Parse REVEL_score alongside REVEL_rankscore from csq field and display it on SNV variant page
- Rank score results now show the ranking range
- cDNA and protein changes displayed on institute causatives pages
- Optional SESSION_TIMEOUT_MINUTES configuration in app config files
- Script to convert old OMIM case format (list of integers) to new format (list of dictionaries)
- Additional check for user logged in status before serving alignment files
- Download .cgh files from cancer samples table on cancer case page
- Number of documents and date of last update on genes page
### Changed
- Verify user before redirecting to IGV alignments and sashimi plots
- Build case IGV tracks starting from case and variant objects instead of passing all params in a form
- Unfreeze Werkzeug lib since Flask_login v.0.6 with bugfix has been released
- Sort gene panels by name (panelS and variant page)
- Removed unused `server.blueprints.alignviewers.unindexed_remote_static` endpoint
- User sessions to check files served by `server.blueprints.alignviewers.remote_static` endpoint
- Moved Beacon-related functions to a dedicated app extension
- Audit Filter now also loads filter displaying the variants for it
### Fixed
- Handle `attachment_filename` parameter renamed to `download_name` when Flask 2.2 will be released
- Removed cursor timeout param in cases find adapter function to avoid many code warnings
- Removed stream argument deprecation warning in tests
- Handle `no intervals found` warning in load_region test
- Beacon remove variants
- Protect remote_cors function in alignviewers view from Server-Side Request Forgery (SSRF)
- Check creation date of last document in gene collection to display when genes collection was updated last

## [4.51]
### Added
- Config file containing codecov settings for pull requests
- Add an IGV.js direct link button from case page
- Security policy file
- Hide/shade compound variants based on rank score on variantS from filter
- Chromograph legend documentation direct link
### Changed
- Updated deprecated Codecov GitHub action to v.2
- Simplified code of scout/adapter/mongo/variant
- Update IGV.js to v2.11.2
- Show summary number of variant gene panels on general report if more than 3
### Fixed
- Marrvel link for variants in genome build 38 (using liftover to build 37)
- Remove flags from codecov config file
- Fixed filter bug with high negative SPIDEX scores
- Renamed IARC TP53 button to to `TP53 Database`, modified also link since IARC has been moved to the US NCI: `https://tp53.isb-cgc.org/`
- Parsing new format of OMIM case info when exporting patients to Matchmaker
- Remove flask-debugtoolbar lib dependency that is using deprecated code and causes app to crash after new release of Jinja2 (3.1)
- Variant page crashing for cases with old OMIM terms structure (a list of integers instead of dictionary)
- Variant page crashing when creating MARRVEL link for cases with no genome build
- SpliceAI documentation link
- Fix deprecated `safe_str_cmp` import from `werkzeug.security` by freezing Werkzeug lib to v2.0 until Flask_login v.0.6 with bugfix is released
- List gene names densely in general report for SVs that contain more than 3 genes
- Show transcript ids on refseq genes on hg19 in IGV.js, using refgene source
- Display correct number of genes in general report for SVs that contain more than 32 genes
- Broken Google login after new major release of `lepture/authlib`
- Fix frequency and callers display on case general report
