### ISSUE TITLE
Add genomic reference sequence

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3460]
It would be useful to add annotation with the genomic (chromosomal) RefSeq on the variant page, especially for copy number variants. An example on correct reporting from the latest ISCN (genome build GRCh38):

NC_000023.11:g.89555676_100352080del

**Comment by dnil** [comment]
Agreed, I really like those, and they are getting better with each ISCN release! Unfortunately they still have not converged on a description that is strictly unique. Multiple arguably equally parsimonious descriptions exist. But, that would only make it easier to produce at least one. 😁

**Comment by ehre** [comment]
You have to remember that I am a mere mortal and not a bioinformatician like you, @dnil ;) But if I understand you correctly, you have issues with ISCN using different descriptions in their suggested terminology? I would then argue that as long as the RefSeq database is stable, we could still use a description as the example above and everyone would interpret it in the same way? Anyway, I think it would add value to display info such as NC_000023.11 on the variant page.

**Comment by dnil** [comment]
Hehe, for an MD the professor has an unusually solid grasp of informatics, so its hard to know what is obvious and not! 😁 

Yes, it works just fine! All roads lead to Rome. We can certainly provide some description, compatible with ISCN2020. But it would be nice to be able to give a highly specific, unique address.

For the del case, I think they may actually be unique now in the 2020, at least if one pretends there is only a single event. 
Unfortunately they opted for 3'-normalisation from hgvs rather than the left align convention of genomics, but its still has uniqueness potential. The difficulty now really is with dup, ins and delins (and inv, since it can be given with ins as well as individually).

**Comment by ehre** [comment]
Great. So a minimum could be to just list "NC_000023.11" on the corresponding variant page, and the CLG can map together the correct coordinates if that part is difficult to solve automagically right now?
