### ISSUE TITLE
manual inheritance not coming up in Scout in some variants....

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3504]
hi, in fam 22187 there are pinned variants in ADRA2B and in ADARB1 where the manual inheritance is not coming up in the variant page.  the information is present in the panel....
BUG?

**Comment by northwestwitch** [comment]
Which panel is it?

**Comment by northwestwitch** [comment]
In these cases a functionality like [this](https://github.com/Clinical-Genomics/scout/issues/3497) is super useful!

**Comment by northwestwitch** [comment]
I'm not sure. @mikaell could you look into it when you have time?

**Comment by mikaell** [comment]
> I'm not sure. @mikaell could you look into it when you have time?

A PR is getting prepared for this. Have a look at #3506

**Comment by dnil** [comment]
Hi, Im sort of back from vacation, though covering up at the clinic for a couple of weeks until more are back. I don't quite see the issue. I see the manual inheritance models just fine? I note that HB added new default panels not long ago, so a tentative guess is that the genes were simply not on the default panel back when the issue was made. This can be a little confusing, but it is 

Closing for now, but feel very free to reopen if I missed anything!

![Screenshot 2022-08-04 at 14 59 37](https://user-images.githubusercontent.com/758570/182853367-ddd73f89-f8f4-44df-8051-7e3029ac2a6e.png)
