### ISSUE TITLE
Matching causatives missing

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#3512]
We have a case where Matching Causatives from other cases, is not visible on the first case page . But we found a variant that has been classified as causative in a earlier case, which is also evident from the variant page where the text "Matching causatives from other cases: xxx" is seen at the top of the page. 

Why is it missing on the first case page? Bug or related to the specific case/variant?  It seems to work on other cases we have (different variants). 
/Sofie

**Comment by dnil** [comment]
Hi, thanks, do you have case number for us to look at?

**Comment by sofievonlanthen** [comment]
Case 722701400185fam. The variant was previously found in case 517701600648fam

**Comment by dnil** [comment]
Peculiar! Thank you, we will have a look as soon as we have some hands on the project again.

En passant, I saw that your institute loqusdb config was a little off and set it back to default. Feel very free to change it back, but I think this is what you would want. 😸

**Comment by northwestwitch** [comment]
I think I know why this is happening: in the code we look for the same causative variant in other cases by matching the variant positional name (example: `7_124491972_C_A_clinical`). The problem is that in the first case you have a clinical variant and in the second a research one ( with positional name like `7_124491972_C_A_research`) so the names don't match and you don't find the research one. This could be fixed easily. because you want to see matching causatives found among research vars, right?

**Comment by sofievonlanthen** [comment]
Great, glad you found the issue. Yes,  we would like to see all variants classified as causative, even if it was found on the research list. The gene in question is now (thanks to the research case) on our PID panel. Would be great if this is fixed. Thanks!

**Comment by dnil** [comment]
Ah, nice catch! We have avoided having information going that way before, showing the clinical results for the research only, but in this case it is a Good Thing to match also the research causatives. Even better if it allows for finding another patient for the few one had for a first publication.
