### ISSUE TITLE
Filtering/hover info for genotype

### ISSUE THREAD

**Issue by leahkemp** [Clinical-Genomics/scout#3537]
Hi all!

One of our collaborators using scout asked after a possible feature request.

We are currently working with some singletons, which means we don't have the same level of inheritance information that you'd have with cohort. For example, we won't have the "Inheritance model" section of scout the filter variants by. However, these singletons still have genotype information that is viewable on a given variant page (in the "GT call" box).

We were wondering if it would be possible to do one of the following:

- have an option to filter variants by genotype call (make the most sense to me)
- have the GT calls viewable on the variant summary page for example as a hover box
- have the ability to filter variants by the inheritance model of the gene the variant is in (this option seems a bit harder since it relies on gene and inheritance model for genes annotations being available)

This would provide the benefit of being able to filter for variants or quickly see if variants are hetrozygous/homozygous on the variant summary page for singletons.

We're currently working with scout version  4.57.4

What are your thoughts?

**Comment by dnil** [comment]
It sounds a little redundant to the way we have things set up with Genmod, and prone to the usual complications with GT like hemizygosity for X for XY individuals, but it is a nice general feature. 

If I recall correctly it is code wise a little bit more involved, since all variant fields for individuals are not available at variantS filtering, but have to be populated at that stage with a slight memory and processing penalty. But, not too bad. Let's check at least!

For a general comment though, since you don'r run Genmod, does that means you run your setup without variant ranking, or did you implement another tool for ranking? I would strongly argue the benefits of working with an automatic rank system of some sort. One can always filter later, but being able to triage along the variant list according to some probability of causation is very useful.

**Comment by leahkemp** [comment]
We run genmod models on our cohorts, but not on our singletons. It's my understanding that genmod models isn't setup to run on singletons? We still utilise rankscoring using genmod score for both cohorts and singletons, however the rankscoring for singletons doesn't include the genetics models (given it's not annotated) so is therefore comprised of allele frequency, filter and CADD (https://github.com/ESR-NZ/vcf_annotation_pipeline/blob/master/workflow/scripts/score_single.ini). I'm now wondering if this feature request could be accounted for in my analysis rather than the scout software downstream

**Comment by northwestwitch** [comment]
I've started working on this. I'm thinking that not all centers/users are using genmod to rank variants before loading them into scout.. Would something like this male sense?

<img width="769" alt="image" src="https://user-images.githubusercontent.com/28093618/196134976-5da11ba5-97b1-4c5c-b3dc-de2b7a1d0046.png">

**Comment by leahkemp** [comment]
That looks great :)
