### ISSUE TITLE
Include all condition types in ClinVar submission, even if Scout supports only OMIM and HPO

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3602]
All condition types accepted by the ClinVar API are:  
- OMIM
- MedGen
- Orphanet
- MeSH
- HP
- MONDO

This can be done in the form by introducing a select with the list above and a free text field that can be filled in by the user on the fly when creating the submission

**Comment by dnil** [comment]
Phenopackets also allows fairly flexible use of CURIE identifiers like these. We could e.g. implementing link out requests via identifiers.org. Compare HGNC: if the term is `HGNC:12345` we ask identifiers about the CURIE prefix https://registry.identifiers.org/registry/hgnc and get the URL pattern for the id `https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/{$id}` back.

**Comment by northwestwitch** [comment]
I see that some (all) of the phenotypes from the list are missing from the registry. They should be included first then

**Comment by northwestwitch** [comment]
I'll add this feature in #3572, since we are already touching the code!

**Comment by dnil** [comment]
Missing? Thats odd! We should ping them then, but perhaps they just hide under their official designations? Which one in particular did you miss? Like OMIM is there as its official [MIM](https://registry.identifiers.org/registry/mim). MedGen is [medgen](https://registry.identifiers.org/registry/medgen). Orhphanet has an extra resource descriptor for the site, but I think we want the [ORDO](https://registry.identifiers.org/registry/orphanet.ordo). MeSH is [mesh](https://registry.identifiers.org/registry/mesh) simply. HPO is [hp](https://registry.identifiers.org/registry/hp). I see, I can't find MONDO; maybe because it didn't use its own CURIE at first, but the ones from the most representative merged term? But they seem to have started with internal ids as well, so it should probably be there?

**Comment by dnil** [comment]
OLS seem to have the full MONDO: it does perhaps not look quite as clean as that registry site, but maybe it is a bit more complete: https://www.ebi.ac.uk/ols/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_2410

**Comment by northwestwitch** [comment]
> Like OMIM is there as its official [MIM](https://registry.identifiers.org/registry/mim). MedGen is [medgen](https://registry.identifiers.org/registry/medgen). Orhphanet has an extra resource descriptor for the site, but I think we want the [ORDO](https://registry.identifiers.org/registry/orphanet.ordo). MeSH is [mesh](https://registry.identifiers.org/registry/mesh) simply. HPO is [hp](https://registry.identifiers.org/registry/hp).

I looked for OMIM, not MIM for instance 😆
