### ISSUE TITLE
RNA multiQC report

### ISSUE THREAD

**Issue by pbiology** [Clinical-Genomics/scout#3647]
As discussed during a meeting on 22-10-28 with @dnil and @northwestwitch, it would be good for the customers who has RNA data associated with a DNA case to also have access to the MultiQC report for the RNA sequences.

Adding it as a report, perhaps just differentiating it from the DNA multiQC with some added tag would be enough for now.

**Comment by dnil** [comment]
Right, dupe for #3645 I guess, but let's leave this one open - you gave the first hint! 😁

**Comment by dnil** [comment]
It would be nice to do the same for the RNA analysis delivery report as well; as it is one can't really tell from what pipeline version the junction tracks stem etc.

The tags for the multiQC reports etc are the same in Hermes for MIP and MIP RNA, but CG should be able to produce different keys for scout anyway I hope, since it's from distinct pipelines (https://github.com/Clinical-Genomics/hermes/blob/11876b741ee380fe9bd980c1a552cd01d1dc66b9/docs/mip-rna_map.md and https://github.com/Clinical-Genomics/hermes/blob/11876b741ee380fe9bd980c1a552cd01d1dc66b9/docs/mip-dna_map.md). For Scout, just let us know what the new key is, and we'll add it as well as a separate re-upload option.

**Comment by pbiology** [comment]
Ahh, missed the duplicated issue. my bad!

As for the tags, I think that @fevac is working on this. @fevac could you add them in here once that is implemented?
