### ISSUE TITLE
Missing BAM files

### ISSUE THREAD

**Issue by MUebe** [Clinical-Genomics/scout#3686]
Hi!
We are missing the BAM-files for case briefsquid.
Is this temporal? It's been like this for some days now.
Thanks in advance,
Malin

**Comment by northwestwitch** [comment]
Thanks for reporting it. We'll check and fix it!

**Comment by northwestwitch** [comment]
One problem was that the path to the bam file was missing in the database, at the cease individual level. I've added it manually, since the bam, files are present on disk. Now it shows that the case has bam files, but they don't open in IGV:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/28093618/204073662-5823130b-1374-4f43-b2dd-0adcb714ffb9.png">

**Comment by northwestwitch** [comment]
Bam files are missing both on disk and on the config file used to load this case. I'm sure that they exist, but I don't know what happened to them. I'll open a ticket and ask the bioinfo prod team! Sorry for the inconvenience!

**Comment by northwestwitch** [comment]
This error should be fixed now. Thanks @mathiasbio!

**Comment by northwestwitch** [comment]
Closing this issue now, but please reopen @MUebe if it does't work as it should. Sorry again for the inconvenience!

**Comment by MUebe** [comment]
Thanks Chiara! It looks good now.
Malin
________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 29 november 2022 09:08
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Malin Ueberschär ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Missing BAM files (Issue #3686)


Closing this issue now, but please reopen @MUebe<https://github.com/MUebe> if it does't work as it should. Sorry again for the inconvenience!
