### ISSUE TITLE
bug with causative variants

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3710]
![image](https://user-images.githubusercontent.com/12525201/206707158-57da1aac-4278-4778-9c68-022b8f22573b.png)
 hi. 
One variant come listed twice (i did no click it twice)
IF I delete one of the duplucated both duplicates get deleted.

**Comment by northwestwitch** [comment]
Weird, we'll check! Thanks for posting it

**Comment by northwestwitch** [comment]
I've been trying to understand what has happened in order to fix the issue. I see on the event log that you happened to mark it as causative several times in a row without unmarking it as causative in between. How did you do it, did you have different tabs with the same variant open and you marked it as causative in several of them? 🤔 

<img width="569" alt="image" src="https://user-images.githubusercontent.com/28093618/206712300-84f84ec5-bdac-476d-b15b-79fe9fb8b4bb.png">

I have tried to unmark it causative and set it as causative again and it's present only once now..

**Comment by northwestwitch** [comment]
Yes, it's the tabs, I could reproduce on my local demo:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/28093618/206713411-8a98baca-c5c9-42af-9943-3a9f72652c5e.png">

I'll write a fix!

**Comment by 4WGH** [comment]
I did not 🙂

I did deleted and marka again several time to correct the duplicat 🙂


Mic
________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 9 december 2022 14:26
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] bug with causative variants (Issue #3710)


I've been trying to understand what has happened in order to fix the issue. I see on the event log that you happened to mark it as causative several times in a row without unmarking it as causative in between. How did you do it, did you have different tabs with the same variant open and you marked it as causative in several of them? 🤔

[image]<https://user-images.githubusercontent.com/28093618/206712300-84f84ec5-bdac-476d-b15b-79fe9fb8b4bb.png>

I have tried to unmark it causative and set it as causative again and it's present only once now..

**Comment by northwestwitch** [comment]
Checked the database and the variant gets actually saved twice in the case document, under causatives:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/28093618/206715704-07f8ad7f-0d60-4cd5-b8b8-e5b6883ebca8.png">
