### ISSUE TITLE
Genepanel PanelApp Green genes

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3780]
We would like to add the genes from Panel App (validated green genes) to OMIM-AUTO (or as a separate gene panel that are always included where OMIM-AUTO is). https://panelapp.genomicsengland.co.uk/

According to Klinisk Genetik in Lund Hans E has possible written / has asked someone else to write a code for this to be performed (@dnil might know more).

According to Klinisk Genetik in Lund (ie Tord) it may be as many as 600 genes or so that are in this gene list that are not present i OMIM-AUTO.

Thank You!  :=)

**Comment by ehre** [comment]
Hi @KickiLagerstedt,

It is correct that we (for trio analyses) routinely apply two gene lists, OMIM-AUTO and "PanelApp Green", where the latter list contains all genes that are green on at least one PanelApp panel. The reason why we chose to do this is that we observed that sometimes OMIM is a bit slow to include newer genes with sufficient clinical evidence. However, both OMIM-AUTO and PanelApp Green are maintained by our bioinformaticians and not by me. Perhaps @mhkc can provide more details.

**Comment by dnil** [comment]
Indeed, and it is a good idea indeed! We'll await an update from @mhkc, but if I'm not mistaken this is done a bit on the side / pipeline level in Lund?

In summary, this is a more like a project than a Scout update, but a two core thing can be done in Scout:
- since we have dl and update of PanelApp panels, we could construct functionality to make a new scout panel "PanelAppGreeen-AUTO" from all PanelApp panels green genes.
- make an integrated command like the "scout load panel --omim" that retrieves and updates panel app green, and updates said "PanelAppGreeen-AUTO". 

Once we have that panel in place, we in Solna can add the new panel to the panel master list in CG, much like for OMIM-AUTO.

**Comment by KickiLagerstedt** [comment]
@dnil 

@mhkc 

We are about to reorder old WGS-trios and would like to include this gene list as well. DO You have any idea when this could be up and running?

**Comment by dnil** [comment]
I'll let @mhkc answer how portable their solution is, but setting up a new inside Scout would probably be about a week including testing etc, then to fit into the general release cycle so a few weeks away at least if this what we prioritise. It is a very tempting, low hanging fruit so chances are good for that given that nothing important breaks in the meantime. 😸
