### ISSUE TITLE
ExAC frequency

### ISSUE THREAD

**Issue by RosRom85** [Clinical-Genomics/scout#382]
Hi!

I have a question about ExAC frequency in Scout. I found a mutation in UNC93B1 (p.Val498Met) in PID132, which was completely fitting the phenotype, rare, coding region and I considered the case solved.
Today I was searching literature to get more info about the mutation. I figured out that the population frequency for ExAC is in Scout 0.005 and on the ExAC website is 0.04, very difference as you can notice. 
Is there some mistake or there another reason for that? 

Thanks!

Best,
Rosa

**Comment by moonso** [comment]
It is usually because ExAC updates there own database faster than we.
So we download a version of ExAC and annotate the variants, after a while they might have updated but you will still see the older annotation in scout.
What you can do is to follow the link to ExACs homepage to see the most accurate annotation.
