### ISSUE TITLE
panel available at case level

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3841]
on the same case this is happening

here I can see these panels
![image](https://user-images.githubusercontent.com/12525201/223489493-342c80ec-265c-4a07-b1e6-cb0a66952a39.png)

but on the main case page I see these
![image](https://user-images.githubusercontent.com/12525201/223489707-52940329-fa87-4d61-b6f0-9649c524c0cf.png)

Possible panels to select are note matching.... shoulf it be like this?

**Comment by dnil** [comment]
Hi again @4WGH! Nothing is out of the ordinary here, as far as I can tell?

All active panels run for the case are available on the Filters Gene Panels dropdown, plus the ones selected for the institute to always be searchable. I think you recall, we helped you add DSD-S to that list in a previous issue. You can always undo that on the Institute Settings page if you like.

I think what is confusing might be the missing two panels, SEXDIFF and SEXDET panels? They appear to be "deleted" from the gene panels by someone - hopefully intentional?

<img width="1719" alt="Screenshot 2023-03-07 at 18 17 21" src="https://user-images.githubusercontent.com/758570/223498769-a2376901-ece8-4d21-904a-3a1c39839246.png">

 Note if you uncheck the tick mark at the top of the Panels page you can still interact with them - much like other deleted things on computer systems, they are not permanently removed. 

<img width="290" alt="Screenshot 2023-03-07 at 18 11 16" src="https://user-images.githubusercontent.com/758570/223498294-09ee6d9f-1dd0-4e0e-8b1d-cd4a5a21ee45.png">

If that is intended, you can fully restore them by hitting the "restore" icons on the panels over to the right.

<img width="372" alt="Screenshot 2023-03-07 at 18 23 34" src="https://user-images.githubusercontent.com/758570/223500234-39021892-76a0-4d61-bb59-79f73417c5b9.png">

Closing this issue with this. Note that all new DSD cases should now hopefully be run with your DSD-S panel, but it will not be retroactive - you would need to trigger a rerun for that. But, as we discussed in that previous issue, the genes appear to be on OMIM anyway, so you should be ok with just using the DSD-S from the dropdown.

Cheers, thanks for reporting!

**Comment by 4WGH** [comment]
well 
DSD syndromic is coming up at the filter but not in the case level.

Same for hydrops that shoulf not be showing.

what is the diffenrece at case an filter level?

**Comment by 4WGH** [comment]
breast cancer should not come up in the filter too

**Comment by 4WGH** [comment]
how do I define a panel to show up at the case level. that is what I wish?

**Comment by northwestwitch** [comment]
Hi! Gene panels shown on the case page are the panels used to filter the variants uploaded for the case. On the other hand gene panels shown in the variants filters could be any panel that has been selected in the institute settings by somebody in your institute:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/28093618/223637754-f2675984-eae5-4133-993d-372432a63cd1.png">

Gene panels shown in the filters are the same for all cases of the institute (so perhaps somebody needed the breast cancer panel to analyse some other case, and that's why it is there).

To answer you question (how do I define a panel to show up at the case level) - @dnil correct me if I'm wrong - you need to order the analysis with the panels that you need to show on case page.

For instance the case in your example was analysed (uploaded) with the following panels:

<img width="196" alt="image" src="https://user-images.githubusercontent.com/28093618/223639813-252bc2a4-4349-4089-a897-3d1748f7f014.png">

That are the same panels that show on the case page:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/28093618/223639886-ee94d3ae-7a72-489f-a9ec-7d2bccb2822f.png">

**Comment by 4WGH** [comment]
THanks. I will try to sort things out.

Nobody at KlinGen could help me to sort out who have choosen what.
I will need to reorganize in a more appropiate way the DSD cases.
I'll come back for help soon 🙂





________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 8 mars 2023 07:50
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] panel available at case level (Issue #3841)


Hi! Gene panels shown on the case page are the panels used to filter the variants uploaded for the case. On the other hand gene panels shown in the variants filters could be any panel that has been selected in the institute settings by somebody in your institute:

[image]<https://user-images.githubusercontent.com/28093618/223637754-f2675984-eae5-4133-993d-372432a63cd1.png>

Gene panels shown in the filters are the same for all cases of the institute (so perhaps somebody needed the breast cancer panel to analyse some other case, and that's why it is there).

To answer you question (how do I define a panel to show up at the case level) - @dnil<https://github.com/dnil> correct me if I'm wrong - you need to order the analysis with the panels that you need to show on case page.

For instance the case in your example was analysed (uploaded) with the following panels:

[image]<https://user-images.githubusercontent.com/28093618/223639813-252bc2a4-4349-4089-a897-3d1748f7f014.png>

That are the same panels that show on the case page:

[image]<https://user-images.githubusercontent.com/28093618/223639886-ee94d3ae-7a72-489f-a9ec-7d2bccb2822f.png>

**Comment by dnil** [comment]
That is quite correct @northwestwitch!

I would reaffirm that the VariantS page - Filters - Gene Panel dropdown contains both the panels that the case was actually analysed with (the same that you see on the Case page - Panel) plus a set of panels that are common to all cases in the institute, and can be adjusted on the Institute - Settings page.

`Hydrops` and `Breast cancer` are there because colleagues of yours needed it in cases not ordered with it at one point. Much like the DSD-S is currently on all their cases. I think you can guess at least a group of persons involved for each, and ask them if you think its time to remove it from the always searchable list on the settings page.

I assume this is in part due to your request to add https://github.com/Clinical-Genomics/cg/pull/1764. This is deployed as of yesterday, but it is not retroactive. Again, if you for some reason want to explicitly add the DSD-S panel to old cases, order a rerun. The genes were apparently already in the OMIM panel though.
