### ISSUE TITLE
Some views have long load times

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#3906]
Views like `/<institute_id>/cases` takes several seconds to load. In some cases it seems to be caused by inefficient queries for counting the number of documents.

**Comment by dnil** [comment]
Hi @mhkc! I'm very sure we could optimise this, perhaps most easily by adding indices that include the categories inquired on the cases page. This is simple and rewarding since the case collections are comparatively small, and the new indexes will build quickly and be small. We could also cache results, since uploads happen seldom compared to page loads, but probably no need really. I personally don't feel this is a bug, but lets see.

**Comment by dnil** [comment]
I will say that it will be a little hard to test during optimisation - our stage server holds only a few thousand cases. 😊

**Comment by northwestwitch** [comment]
> Hi @mhkc! I'm very sure we could optimise this, perhaps most easily by adding indices that include the categories inquired on the cases page. This is simple and rewarding since the case collections are comparatively small, and the new indexes will build quickly and be small. We could also cache results, since uploads happen seldom compared to page loads, but probably no need really. I personally don't feel this is a bug, but lets see.

Perhaps running a query on the cases collection and grouping by case status, something like the query in #3898 ?
