### ISSUE TITLE
Scout container tmp filling up

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/scout#4024]
### Description
While running the latest scout container (4.70) it was found that it created a tmp folder that just kept growing (`...../containers/storage/overlay/<layer_SHA-SUM>/home/tmp`). By the time we noticed it was 125 G.

For more information see [internal issue](https://github.com/Clinical-Genomics/IT-issues/issues/710)

**Comment by northwestwitch** [comment]
Oh no, hope it didn't cause a lot of trouble! I'm on vacation until Sunday
(I think Daniel is too). I can take a look at it on Monday.

Chiara

**Comment by dnil** [comment]
Yep, I’ll be around from end of next week. Looks like you handled it well from the internal issue Vincent: likely the storage will be ok for a few weeks now. Shout otherwise, and we’ll fix when we are back!

// Daniel

**Comment by northwestwitch** [comment]
I've extracted what is found in the ever-growing temp folder of the scout container and it looks like it's VCF files. I've saved the content under /home/hiseq.clinical/scout_container_temp_folder

Let's remember to remove this folder after everything is fixed!

**Comment by northwestwitch** [comment]
Ok, I finally found out the cause of this problem. It's happening every time a user opens a variant. Specifically, I believe it happens when [this code](https://github.com/Clinical-Genomics/scout/blob/208da889b3a7fb70c4c3088b1400ad5fd422336a/scout/adapter/mongo/variant.py#L837) is invoked from [this function](https://github.com/Clinical-Genomics/scout/blob/208da889b3a7fb70c4c3088b1400ad5fd422336a/scout/server/utils.py#L204).

I've reproduced it also locally, starting a container and opening this variant:

<img width="219" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/8f87e7e4-0ab1-411a-9370-59de63e19534">

When you look inside the temp folder of the container, then it has created the reduced VCF file for the variant:

<img width="1115" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/37e9b12b-7fb7-4371-9bdf-a7373ca4719e">
