### ISSUE TITLE
Disease term to gene mapping to use hg38 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4124]
There currently appears to be no no option to select build when updating disease mappings. The consequence is that hg38-only genes are never mapped to diseases, since they will be missing from alias lists. See e.g. #4123.

On the table is also to figure if it is safe to use both for alias mapping completeness, or if it the mapping really needs to be build selective.

**Comment by dnil** [comment]
This is quite possibly a bug for hg38 analysis?

**Comment by northwestwitch** [comment]
This appears to e fixed by #4644.

I've tested it locally, where:
- Having a database containing genes (both builds), HPO terms and diseases
- If I modify the VCF file of the demo fusion case to include gene NOTCH2NLC (build 38 only) and load the case:

<img width="259" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/a2c4a02d-fb91-4780-ae82-fce6ca661789">

Then if I go to the variant page I see that the gene is associated to diseases:

<img width="537" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/f5a3d36d-0467-44e6-b8da-2d231bfa2512">

Closing this issue, but please @dnil reopen if I misunderstood

**Comment by dnil** [comment]
I think you are right - the issues had the same root!
