### ISSUE TITLE
nice view of size for SV

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#4131]
![image](https://github.com/Clinical-Genomics/scout/assets/12525201/f31c0493-2313-4b3a-be18-3616c058fdbc)

Hi we were wondering if it is possible to show the size for large SV in a more comfortable way for the eyes, 
with space or comma after the million bp,  

instead of "71449439" 
something like this 
"71,449439" or "71 449 439" 
that would make it easier for us read it 

thanks

**Comment by northwestwitch** [comment]
It's a great suggestion, and not that difficult to achieve I think!

**Comment by 4WGH** [comment]
thank! this was very much appreciated.
Some users wonder if it could be extended to the variant view, see ex (and other places where it could be applicable )

![image](https://github.com/Clinical-Genomics/scout/assets/12525201/0dad61ad-cd15-43a9-a6cd-1d56fdb4be09)

**Comment by dnil** [comment]
In general, it breaks copy-pasting to other applications. While we of course would like to be able to link to sites that ppl use instead of relying on copy paste, it is probably best not to remove the possibility completely. But, we could do something like a "copy-to-clipboard" coordinates button, much like we do for very long ref-alt alleles, which would allow us to break these other number displays as well. I think that could work?

The second part is the readability. Personally I still feel numbers without characters in them are so much easier to read. I would assume at least some of your colleagues are likewise weirdly wired. It would be possible to make a personal preference, much like dark or light mode, but that would be rather low prio I'm afraid. 😊

**Comment by 4WGH** [comment]
in the Length would be good. this not my personal wish, but collection of collegues opinion.

**Comment by dnil** [comment]
Sure thing; the length is unlikely to be pasted anywhere!

**Comment by 4WGH** [comment]
thank! that was the most important

**Comment by 4WGH** [comment]
[like]  Michela Barbaro reacted to your message:
________________________________
