### ISSUE TITLE
Show all "Inactive cases" respectively "Active cases" on the Cases-page for each Institute in Scout

### ISSUE THREAD

**Issue by TJO-Lund** [Clinical-Genomics/scout#4209]
Institute Cases page: In addition to the option under "Limit", where default is 100 cases (on the Cases page). We in Lund would like to have a better overview of Inactive respectively Active cases. A better default-setting for us would be to always show all "Inactive cases" and all "Active cases". 

Archived cases, Solved cases, and Ignored cases could show just the latest samples (maybe two weeks). We believe these changes would add a better overview-function for planning (weekly-follow up of the queue) using the Cases-page.

**Comment by dnil** [comment]
Let's see what we can do!

Currently, you always have visible counters for all categories in the meantime, which should give you most of the general overview you need without searching.

There are several ideas here. Let's see:

## The use of time for queries
We only have that on the CLI currently, suggested it a few times for the Dashboard, but it hasn't got that much interest at the user meetings. Eg monthly reports of solve rate, number of new cases and the fraction of open cases. That could be done also on the caseS query side of course, in fact would almost automatically, since Dashboard and caseS use the same queries.
## Number of cases is very different for each institution
### Large, slow process
The caseS page is used differently depending. With a large rd institute, with investigations holding up for consultations, reflexive testing or phenotyping, there can be thousands of "active" cases, and hundreds of inactive on a given week.  They currently rely more on their own LIMS to keep track. We will try to provide some more tagging / nuancing "active" to help with this (https://github.com/Clinical-Genomics/scout/issues/3937).
### Small, fast process
With fewer cases, more acute cases, panels etc, the inactive/active categories are very important.
How about an institute specific limit, that you could set to a few thousand to fit all the inactive and active? And maybe we could add an institute selectable default search prio as well, like status: inactive, status: active, where the current upload time based is the overall default.

**Comment by TJO-Lund** [comment]
Can a button in the upper right panel be added called Show all Active and Inactive cases? Alternatively one button for "Show all Active cases" resp. "Show all Inactive cases"? Statistics would be nice to have but perhaps lower prio.

**Comment by northwestwitch** [comment]
What about configuring this feature from the institute settings page to prevent accidental resets or modifications that may occur due to inadvertent clicks on the cases page?
