### ISSUE TITLE
Gene filter for fusion vcf should work for fusion_gene names

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/scout#4286]
- Gene filter should work for fusion_gene names when fusions not having gene objects associated

**Comment by fevac** [comment]
@dnil @northwestwitch could some of you work on this? It would be great to have it

**Comment by dnil** [comment]
Ah, we kind of thought it was a placeholder for you! Sure, maybe you could show us what you mean at some point? Maybe like a huddle Thu/Fri sometime? Or maybe it's obvious if one looks at a few current fusion cases? 😊

**Comment by northwestwitch** [comment]
> Ah, we kind of thought it was a placeholder for you! Sure, maybe you could show us what you mean at some point? Maybe like a huddle Thu/Fri sometime? Or maybe it's obvious if one looks at a few current fusion cases? 😊

I know what she means: fusion variants sometimes are loaded with gene names that don't exist it the scout database. She wants to filter using these strings

**Comment by fevac** [comment]
Exactly! Thanks

**Comment by dnil** [comment]
But what are those, and why don't we load them if they are found among the clinical variants? Are they like ncRNA or pseudogenes? Do they have hgnc_id for starters?

**Comment by dnil** [comment]
We are considering loading a larger gene set at some point since we both would like to get better at finding actual RNA-gene mutations, and also since we kind of get more definitive calls for gene family genes with long reads. It's a bit touch and go if it's worth it on hg19 though, but we could perhaps push that up a bit if it would help here?

**Comment by fevac** [comment]
We don't have an hgcn_id for those genes, so they are not properly parsed and only get a fixed gene name

**Comment by dnil** [comment]
I checked a couple of cases. It seems the RNAFusion annotation pipe is using some transcript numbers instead of gene names. This is an issue in common with Tomte/Drop. Perhaps we could work a little on it and see if we can identify the faulty annotation source? That might help both pipes.

<img width="169" alt="Screenshot 2024-03-13 at 07 12 12" src="https://github.com/Clinical-Genomics/scout/assets/758570/2c04d696-c145-4f9d-a6d1-6d4084186a98">

I guess it could be some kind of fallback annotation when whatever tool you use is uncertain? Like the transcript AL365209.1 might be safe to call, but there are like two possible genes IGSF21 or TEC?

<img width="542" alt="Screenshot 2024-03-13 at 07 45 11" src="https://github.com/Clinical-Genomics/scout/assets/758570/0cf6f1c7-979f-468e-84c3-dd1e91326fce">

It seems we also have an issue with the alias parsing for the fusion events; by the looks of it, when one of the gene symbols in the fusion is not correct, the other is not looked up? 
`IGH@` is probably not a real symbol or alias, more of a placeholder for any of many IG-heavy genes perhaps? But no reason to drop `FCGR2B` - that is an established [symbol](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:3618). We'll try to fix at least that part!

**Comment by fevac** [comment]
IGH@ refers to the IGH locus - but it would be nice to be able to filter based on the name even if it cannot add gene specific information as it doesn't have and specific gene id associated
