### ISSUE TITLE
Cannot chose newly added gene panel

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#4320]
Hi awesome Scout team!

I've added a new gene panel, Hereditary optic neuropathies (https://scout.scilifelab.se/panels/6583de2d8423ff92e097bb32). It's visible on the Gene Panels page but I can't chose it in the drop-down menu on cases run after the addition and it cannot be chosen in the order portal for new cases. What have I missed? :)

Thanks,

Ingegerd

**Comment by northwestwitch** [comment]
Happy new year!  - first issue of the year by the way - 😄  

the reason why you can't choose the panel when ordering the analysis is that the panel is still missing from the panels'master list present in the order portal application. I've opened a pull request in the software repository that handles this (cg) to fix it. It will take a few days I think before you'll be able to select this panel on new analyses.

Regarding your other question - why you can't choose the panel as default panel from the case pages - that's because no case has been runned with that panel yet. so the panel is not available from the selectable panels on case page. I have no changed the settings of cust003 so the panel should be at least available when filtering the variants on variants page:

<img width="437" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/2a1765b4-80fb-4333-9301-275aacc6ed90">

Hope it helps in the meanwhile while we fix the main issue. We'll keep you up to date so you know when it will work to oder new analyses with the new panel.

**Comment by ielvers** [comment]
Thanks Chiara!

**Comment by northwestwitch** [comment]
Hello again @ielvers. We have just applied the fix in the cg software and I've created the panel in our status database. I'm not 100% sure it will works because I'm not very familiar with the procedure but could you check if the panel is available in the order portal now? Thanks!

**Comment by ielvers** [comment]
Hi! Now I can chose it when ordering a rerun. We're looking at how it would work if we do a regular order with a .json file.

**Comment by ielvers** [comment]
It works! We can upload a .json file with OPTIC and it looks good. Thank you!

**Comment by northwestwitch** [comment]
> It works! We can upload a .json file with OPTIC and it looks good in the order portal. Thank you!

Nice! You're welcome! Closing this issue now :)
