### ISSUE TITLE
Display user responsible for adding to ClinVar subs on the submission list

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4326]
Would help keeping track (and getting in touch with the right person) for larger institutes *cough* cust002 *cough*.

**Comment by northwestwitch** [comment]
This one makes sense. In order to fix it we have to either introduce an event with a ClinVar-related new verb or add the id of the user to the submission object itself, that now looks like this

<img width="385" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/5ed58f89-00cc-45f6-b041-13acabbdad51">

Since ClinVar submissions are institute-level events they can't be shown on the case pages as we do for normal events so I'd opt for option 2. Should be easy!

**Comment by dnil** [comment]
I was thinking about the variant addition step primarily, but it sure would not hurt to track who opened the list as well! You are very right we actually don't have an event for adding a pinned var to clinvar submission - in contrast to e.g. adding it to beacon or patientmatcher. It would make sense have one, wouldn't it: that is still case level.

**Comment by northwestwitch** [comment]
Ah OK, because I think before you wrote that your were interested in knowing who opened the submission object, or something, so I figured each user wanted to have their own submission object - which would make sense to me. But also adding the clinvar verb would be nice. Perhaps one can have both?

**Comment by dnil** [comment]
Both is best, but the issue I wanted to solve here was the variant addition step! Practically when sharing submissions we would like to see who added it to be able to ask about it when submitting the list. It should also really be on the audit log, timeline etc, shouldn't it...

**Comment by northwestwitch** [comment]
This is closed by #4357 and #4355
