### ISSUE TITLE
plugin for variant export

### ISSUE THREAD

**Issue by parlar** [Clinical-Genomics/scout#4515]
Hi everyone,

In Umeå, we think it would be useful to be able to export a selected subset of variants from cases in Scout to a other variant assessment tools, QCI for example. Like a second opinion in tricky cases. And subsequently also import results/assessments back into Scout from the secondary tool.

We have received extra funding from RCC for hiring a consultant to focus on this and also other things related to our infrastructure. 

We do not want to fork Scout and it would be nice if the generated code could go into the Scout project. But the question is how. Do you think that it would be possible to develop this functionality as Scout extentions? What do you think?

**Comment by dnil** [comment]
As perhaps expected I don’t understand the Why here? Why not just give the commercial software the VCF from start? I have no recent experience with the tools in question, but from prior experience I would have guessed it more of a (semi)routine case tool than tricky situation one? Ready-to-customer reports or readymade classifications isn’t usually what you get for tricky cases? 

I would personally prefer to spend dev effort/money on better tools for the cases, rather than on interfacing with something that ought to be able to do the job from scratch if it had a good cost-benefit?

From a technical point, I think extensions would work well here if you want to interface their api for a few variants; it’s kind of similar to other extensions, asking loqusdb or what not about a variant, submitting a few variants to MatchMaker etc. 

It is also possible to export small sets of variants from the variantS filter results, but you would not be able to interact with any returned values from the other , which you could via an extension.

**Comment by parlar** [comment]
Thanks Daniel, I understand your view.

The background is that, for wgs data, american cloud services is still not ok here. The idea is to avoid sending everything. (The Identity could also be further obfuscated by e.g. inclusion of fake high frequency hapmap variants. Not perfect but perhaps good enough.)

**Comment by dnil** [comment]
For the record, we had a nice conversation, and touched upon several dev projects of interest, e.g. loading nice tumor mutation signature profiles. Regardless which path you and your team choose, I think we can close this for now and open more specific issues for it. Thank you again!
