### ISSUE TITLE
Nonsensical key/value in demo instance variant

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4729]
What's this?

<img width="1417" alt="image" src="https://github.com/user-attachments/assets/fdf99d2d-d764-4923-a612-deb58183e00e">

To reproduce: scout setup demo, then in mongodb compass check the schema for the variant collection

**Comment by northwestwitch** [comment]
And this? 

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/03db28ef-c496-4085-932e-927ba2e3d52e">

**Comment by northwestwitch** [comment]
Woa

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/b3a416b8-084d-4ea7-b803-19da214fa3e3">

**Comment by dnil** [comment]
Something weird from the ME test VCF FOUND_IN?

**Comment by dnil** [comment]
Yeah, pretty sure it must be here: 
https://github.com/Clinical-Genomics/scout/blob/be9dc04341d70e23571d9a146716956dd5b95a74/scout/parse/variant/callers.py#L30
in combination with incompletely escaped CSQ/INFO lines from ME calling/SVDB processing. In that function, we should not trust the caller in the file, rather fall back to storing only options from `CALLERS`...

**Comment by dnil** [comment]
Ahem, that was very likely just from a speedup I totally forgot on the Tomte branch. Trolls happen. I think it remains that the use of `svdb_origin` is non-standard in this file, but let's revisit that and make sure. We changed that with v4.60...

Bug or not, both the first `if` statements are unsafe. Compare the last one which does a key lookup to make sure the caller exists.

**Comment by dnil** [comment]
Ahem, so, the (demo file) issue remains with the original file as well. And with current prod cases. We apparently use SVDB use to merge multiple individual VCFs with the `SVDB_ORIGIN` used to mark the individual file instead of the caller in that workflow. To be fair that is an intended use case, as the VCF header kind of hints at. I think we will at the very least update the header description in SVDB to reflect this - the one for the newer SUPP_VEC is better, like  "Vector of supporting callers/files (order: ACC00000A0_lanes_12345678_fastp_sorted_md_all_me)." 

The vast bulk use today is with that describing the callers - compare both the SVDB code, and use cases all over - so I think the mod we made for balsamic in 4.60 is still pretty good.

We will keep the slightly weird MEI demo file, since it is similar to current prod, and fix the issue by adding checks to the remaining `if` statements as originally intended. But always feels good to drill down to bedrock before deciding... 😆
