### ISSUE TITLE
Add user sending requests to log

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/scout#4758]
### Description
As part of the move into a hospital setting they request more thorough logging of who has accessed patient data. Currently all requests send by the scout front-end are logged, however the user performing the action is not included.

I would like scout to write both which endpoint was accessed and by who to the log.

**Comment by northwestwitch** [comment]
I'll start working on this one

**Comment by northwestwitch** [comment]
This is now done and will be available from the next release. In order to log users' activity to a dedicated file, one needs to add a [specific parameter](https://github.com/Clinical-Genomics/scout/blob/7ba0973d6c6eb50fc1d90eb073a628a494bf3c15/scout/server/config.py#L156) to the scout config file

And then users will be asked to agree to their activity being monitored when they are logging in:

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/f49cc0b5-dd6e-456b-8951-48d99f1ad352">
