### ISSUE TITLE
MIssing cases

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#4827]
Missing cases from the last few days that were visible the other day. 

Same for other users in cust004 and also cust002. 

Older cases are still there. 
Example of missing case: 024701400228

**Comment by NicoleCMMS** [comment]
Same for cust003.  Case 23312 was apparently rerun and uploaded to Scout on Monday but I cannot find the case at all.

**Comment by northwestwitch** [comment]
Oh no, we'll investigate and re-upload them, sorry for this!

**Comment by sofievonlanthen** [comment]
Great thanks. Did you solve the sample mixup?

**Comment by dnil** [comment]
Emails regarding this should have gone out to all the persons ordering - please check in with production support to get a summary of exactly this has affected your runs!

**Comment by NicoleCMMS** [comment]
And the case magically reappeared in Scout :-)  Thanks guys!

**Comment by northwestwitch** [comment]
> Great thanks. Did you solve the sample mixup?

Yes, all is solved. Apologies again 🙏🏻

**Comment by sofievonlanthen** [comment]
mine hasn't reappeared yet, but guessing it's on its way..

**Comment by northwestwitch** [comment]
> mine hasn't reappeared yet, but guessing it's on its way..

Should be!

**Comment by sofievonlanthen** [comment]
our cases are still not back?

**Comment by northwestwitch** [comment]
> our cases are still not back?

They're working on it. You should be getting a notification soon!

**Comment by northwestwitch** [comment]
We've just been notified that all removed cases are re-uploaded now

**Comment by dnil** [comment]
Ok, with that we are closing this issue. Please either contact the CG Solna support directly if you are still missing anything, or worst case just write back here and we will try to catch them! There are already three deviations open regarding the samples affected by a bug in the sequencing LIMS - and the ones taken offline while it was unclear which samples were affected (https://github.com/Clinical-Genomics/Deviations/issues/697, https://github.com/Clinical-Genomics/Deviations/issues/693, https://github.com/Clinical-Genomics/Deviations/issues/694), and I hope you have all got all the information regarding them from production you should have - otherwise please just inquire again. All the best!
