### ISSUE TITLE
variant scoring discrepancy

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#4959]
Hello dear Scout team!

I'm classifying a variant with the updated classification tool. But the added classification in the bottom left corner, including a score, does not always match the classification in the middle (which is the value that gets submitted when pressing Submit). Some examples:

![image](https://github.com/user-attachments/assets/bfbd9759-d91a-4ecf-aea7-54cf6ee71dc3)
![image](https://github.com/user-attachments/assets/8635551b-9e69-434f-ab8a-5c99b9f84186)
![image](https://github.com/user-attachments/assets/579f6e9c-cba0-4963-bebf-2a510344c55f)
![image](https://github.com/user-attachments/assets/10b6aeff-3dfb-41ac-911b-61a8e6bf6905)
![image](https://github.com/user-attachments/assets/42b9c229-df8b-4b33-a2fa-c730b91b53f9)
![image](https://github.com/user-attachments/assets/2f14230f-f347-423d-bbda-ab5bba939bdf)
![image](https://github.com/user-attachments/assets/bd2eb736-28b0-46f7-b484-a4c0ea12d4db)
![image](https://github.com/user-attachments/assets/0a9fe976-f565-4e9d-a051-f03243f2ad9e)
![image](https://github.com/user-attachments/assets/64a11d64-fc09-4528-8d08-990aba2164f4)
![image](https://github.com/user-attachments/assets/8509f894-2910-4e67-8499-fa5bc5706633)

So sometimes (example scores -4, 8, 9, 10 above) the interpretation in the bottom left corner does not match the overall classification in the bottom middle. Also extra confusing that scores 6 and 7 gives Likely pathogenic in the middle while scores 8 and 9 lowers the classification to VUS.

For the Likely benign examples, I don't think score -1 is meant to be Likely benign? That should still be a VUS, right? I'm mostly including those to show that there is a discrepancy among Likely benign / Benign as well.

**Comment by dnil** [comment]
> For the Likely benign examples, I don't think score -1 is meant to be Likely benign? That should still be a VUS, right? I'm mostly including those to show that there is a discrepancy among Likely benign / Benign as well.

I'm not quite sure what you mean with this? See eg https://pmc.ncbi.nlm.nih.gov/articles/PMC8011844/ table. Or consider that the scale from a VUS perspective is centering around the tepid range somewhere, and 0 is the point on the thermometer scale where a VUS freezes forever into a likely benign. 🥶

**Comment by ielvers** [comment]
Hi Daniel!

I appreciate your response but I'm not quite sure I follow. I thought the point of the bottom left box was to give additional information to the summary classification in the bottom middle, not to use something completely independent? I realize I might have overreacted :)

PVS1 + PP4 (OR PP1) gives "Score 9 Likely pathogenic" vs "Uncertain Significance" 
PS1 + PS3 gives "Score 8 Likely pathogenic" vs "Pathogenic"
PS1 + PS3 + BS2 gives "Score 4 Warm VUS" vs "Pathogenic"
Are the two classification systems supposed to disagree that much?

**Comment by dnil** [comment]
Right, a little bit of both; it does show the idiosyncratic nature of a couple of Richards et al rules, notes a few missing potential rules, highlights the lack of full guidance in Richards on how to weigh conflicting benign and pathogenic criteria - and gives a cool colourable output scale in the VUS regime.

I have a sense you are step by step rediscovering the first Tavtigian paper conclusions, and a little more?https://pmc.ncbi.nlm.nih.gov/articles/PMC6336098/

1. This is as predicted. On a personal note, seeing a frameshift in a gene with very high specificity, with no contradicting criteria, would make me itch to call it a LP. The same if the frameshift was "only" cosegregating with disease in several family members. Note perhaps the **LP(i) (1 PVS + 1 PM ~ 0.994)** in https://pmc.ncbi.nlm.nih.gov/articles/PMC6336098/#T1 being stronger than expected by Richards. A 1 PVS + 1 PS would give an Odds_Path of 350, or a Post_P of 0.975, or about as much as the somewhat controversial P(ii) rule.
2. Your second observation (PS1+PS3) exactly corresponds to the **bolded Path (ii)** in https://pmc.ncbi.nlm.nih.gov/articles/PMC6336098/#T1. They find that the posterior likelihood of this is decidedly lower than the other Pathogenic criteria from Richards (0.975 compared to 0.994), and weaker than eg LP(i) (1 PVS + 1 PM = 0.994).
3. Having established that the PS1+PS3 is too strong in Richards, this is now rather clear. But it also highlights what happens when you have a sum rule to add in the benign criteria, before they trigger a classification in Richards. A BS alone is to us not    the source of any classification (VUS). But PS1+PS3-BS1 in Tavtigian gives a meager Odds_Path of 18.7 or Post_P of 0.675. Way below a LP; a warm VUS, very much risking dropping to tepid. I will however hold that you are not going to be able to give me all that many examples of known pathogenic variants, with solid functional evidence, that also show a frequency that clearly puts them above the (continental) population frequency threshold for a disease of that kind and inheritance pattern, so maybe we are wandering into somewhat academic territory here?

**Comment by dnil** [comment]
Ah sorry, you had BS2 in your third example! 😊 I guess those would be a bit more common - that'd be the reduced penetrance ones. But that is another step entirely. Which we could probably formulate in statistical terms, or maybe find the missing contributions in other factors, genetic or otherwise. But another day! 😅

**Comment by ielvers** [comment]
Thanks for responding, Daniel. I appreciate the score within the bottom left classification. I thought it was supposed to match the bottom middle classification, but I was wrong :)

**Comment by dnil** [comment]
Super! Use it with thought, not just picking the results that fits the feeling at the moment, and  perhaps as an indicator for when to dig a little deeper into the Richards criteria. In general I do feel Tavtigian is a bit more thought through, but note that we formally usually say we use Richards when reporting. Bayesian or not, this is still far from a fully automatic process - quite some manual judgement involved.
