### ISSUE TITLE
Managed variants VCF

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/scout#4969]
Hello scout team
Looking into the managed variants VCF exported by scout I see a couple of entries that are troublesome for downstream tools.
For example:
```
7   117119797   .   A       .       END=117119797;TYPE=SNV
```
which doesn't have an ALT entry (the dot is in the QUAL field)

Also variants missing REF:
```
11  64577603    .       del .       END=64577615;TYPE=DEL
11  64577603    .       ins .       END=64577603;TYPE=INS
```
We can try to remove these entries, but then we are excluding potentially important variants.

**Comment by dnil** [comment]
Hm, those all seem rather solveable with “N” REF / ALTs. Would that work for you?

**Comment by jemten** [comment]
True! I'll run some tests next week and get back to you.

**Comment by dnil** [comment]
Nice to know what’s needed! We’ll polish them a bit regardless - no reason to have to have an extra conversion step if we can convince the VCF writing step to be clearer. It looks like just upper-casing the type and enclosing it in braces should fix the alt as well.

**Comment by dnil** [comment]
Hm, I checked the writer code, which is not too bad in general, and also these variants, and can confirm that this is the way they have been input. We will beef up the checks on these a bit. To solve the issue at hand, I'll add a couple of fallbacks (such as alt "N" or "<DEL>" or "<INS>" above) and ref "N" for the missing ones above.

**Comment by jemten** [comment]
Also looks like the filter column is empty. Shouldn't that be set to `.` to indicate a missing value?

**Comment by dnil** [comment]
Indeed, as could perhaps the others have been (though the definition is a little peculiar for "." on alts, basically saying only to use that if there are no alts).

**Comment by dnil** [comment]
Great with the example in `clearshrimp`: it also had a del alt allele "-". Again, sorry for the relaxedness here. It is essentially a power user tool let loose to more users than first envisioned. We'll fix first what we see in terms of export, and then ensure a more controlled vocabulary in the future.

In general though, it would probably be best if the normalisation of the variants is done by the pipe that shall use them - I take it you do already? We *could* otherwise fire up e.g. `bcftools norm` ourselves, either on the browser side or on CLI export.

**Comment by jemten** [comment]
We can do normalisation, like running `bcftools norm` but it would be good if scout could export a VCF following the v4.2 spec so that the pipeline doesn't have to do custom editing in the file. I don't know enough about how the export to vcf functionality is implemented in scout to know if that is possible. If it turns out to be very hard we can look into a pre-processing step for scout exports.

**Comment by dnil** [comment]
We should be able to keep it conforming to spec; normally the export would already do so, but that turns out to be assuming the imported variants are conformant. In the current PR we have added some quick edits based on what you saw here/in `clearshrimp`, and will proceed to make sure the input (and output) conforms.
