### ISSUE TITLE
compounds not displaying correctly

### ISSUE THREAD

**Issue by Dilea** [Clinical-Genomics/scout#534]
In the case below there are 15 variants in a particular gene. When trying to see the compound variants you only get one variant that is not even within the gene boundaries and therefor is not loaded. Is this intended or a bug?

https://clinical-db.scilifelab.se:8083/cust004/217701600132fam/variants?csrf_token=1496072538%23%2347cf150835edd2fab1d004c6f8ad7ff3fb3b1070&variant_type=clinical&hgnc_symbols=HSPA9&cadd_score=&thousand_genomes_frequency=&exac_frequency=#

**Comment by moonso** [comment]
Hi, there are some things that are as they should be and some that are not.
When investigating the variants we see that almost all of them are present in the mother, thats why they do not show as compounds. 
On the other hand the variant that you mention should be loaded so we need to check why that did not happened.
We can discuss this closer at the scout meeting tomorrow 1/6.

Måns

**Comment by moonso** [comment]
The reason why not all compounds where loaded was the following:
**genmod** is the program that calculates all the compounds, in this case the VEP annotation was used to check if variants are in the same gene and in that case potential compounds.
VEP calls variants 5000 bases before and after a gene for `upstream_variant` and `downstream_variant` so **genmod** counts these variants as belonging to the gene.
Scout on the other hand use the gene coordinates from HGNC when uploading all variants from a gene so the upstream and downstream variants was not added.
This is now corrected so that we will load all upstream and downstream variants as well.

When we upgrade Scout to 3.3 we will reload the variants in this region for you.

Let us know if there are any other questions.
