### ISSUE TITLE
Support for alternate oAuth severs

### ISSUE THREAD

**Issue by matthdsm** [Clinical-Genomics/scout#561]
Hi,

We're very interested in using Scout for our variant analysis. However, we use a self managed oAuth server for all our authentication needs. What are your views about supporting alternate (or custom) oAuth servers?

Cheers and kudo's for the great work!
M

**Comment by moonso** [comment]
Hi,

glad to hear that you want to try out Scout!
I'll need to pass this question to @robinandeer , guess that you mean web login?

Best,

Måns

**Comment by matthdsm** [comment]
Hi, 

Thanks for your reply! What I'm actually looking for is support for a authentication system analog to the google login. Both use oAuth2, but we have our own server for this. My question is if it would be possible to add support in the config file for alternate severs, besides google.

Thanks
M

**Comment by robinandeer** [comment]
Hey Mat,

thanks for your feature request!

We are using a library called OAuthlib to handle authentication: https://flask-oauthlib.readthedocs.io/en/latest/client.html

I believe it's flexible enough to handle any OAuth server so this should be possible 🙂

If you want to experiment a little by adding support for generic servers we will be more than happy to take a look at your solution! Otherwise, we'll keep this issue open and see when we will have time to look into it ourselves.

**Comment by moonso** [comment]
Any progress here @matthdsm @robinandeer ?
