### ISSUE TITLE
Panel Template uploading new genes

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#595]
Johanna has issues with using the panel template in the user guide  - wrong headers???
(csv file)

"Internal error"

Henrik knows more...

**Comment by henrikstranneheim** [comment]
I have investigated and there is there is a bug in the code. We will try to fix this as soon as possible. And also update the documentation and exampel file to be more clear.

**Comment by johsko** [comment]
Hi
I am just wondering about the progress in uploading the new ID-panel or fixing the bug so I can upload it myself? 
/Johanna

**Comment by moonso** [comment]
Hi @johsko ! It is fixed in the code but we need to update the server. We will do this ASAP and contact you when done.

Måns

**Comment by johsko** [comment]
Hi @moonso !

Is it possible to upload a gene panel yet? I have 100 cases that I am waiting to analyze using the new ID panel. :-)

//Johanna

**Comment by henrikstranneheim** [comment]
Hej Johanna,

Ledsen för att det dröjer. Ändringarna är klara men måste valideras och rullas ut med andra viktiga uppdateringar i Scout. Måns och Robin jobbar för fullt för att uppdatera Scout så snart som möjligt. Scout kommer uppdateras denna vecka (jag vågar dock inte lova dag). 

Mvh
Henrik

**Comment by moonso** [comment]
Hi @johsko , we will try to fix today or tomorrow!

**Comment by moonso** [comment]
Now finally @johsko you should be able to upload the panel. Sorry about the confusion, the headers should follow what is stated in the updated user guide on [gene panels](http://www.clinicalgenomics.se/scout/user-guide/panels.html). I have fixed the file that you created and will email the updated version to you. Then you can upload it in Scout.
Remember it can take some time since there are many genes!

Sorry for the delay,

Måns
