### ISSUE TITLE
BRCA1 not in OMIM-AUTO 😕

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#692]
Seems very odd, right @moonso?

From OMIM dump in Scout:
113705	gene	672	BRCA1	ENSG00000012048,ENST00000357654

**Comment by moonso** [comment]
I don't get it... you show that the gene is in scout?

**Comment by dnil** [comment]
In scout, but not on a clinical panel. Attempting to filter with it gives an error - missing from Clinical panels. Looks to me like only BRCA2 is on any panel. The reason is simple: BRCA1 and several other “pure” cancer risk genes are noted as a { susceptibility to} gene in OMIM. If there is another type of tumor or such, the gene gets upgraded to a Syndrome disease gene - hence BRCA2 in the panel. This is stupid, but will take some thinking to get around without having to hand-pick genes. 
🤔

**Comment by moonso** [comment]
Aha, so we could start with checking how many more genes we would get if we include "susceptibility to"

**Comment by dnil** [comment]
Yes. But a lot of that is going to be noise.
Kicki is submitting a cancer panel now, which will solve the particular issue.

On a side note, perhaps use this as a pretext to update OMIM-auto? 2016-2017 have been productive gene discovery years. I’ll help look at conflicts. Next time the obvious gene will have entered OMIM just after the last OMIM-auto release...

**Comment by moonso** [comment]
When using the current definitions for OMIM-AUTO BRCA1 should not be there. We can discuss this issue in a user meeting
