### ISSUE TITLE
Something wrong with scoring?

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#743]
If we summarize the scores for this variant we and up with 16 - but SCOUT ends up with 10.
Is there something wrong - or something we do not understand?

https://scout.scilifelab.se/cust002/F0016058/27f034804a71d67cdeb01f343dc853ad

**Comment by moonso** [comment]
Hi @KickiLagerstedt the reason for the penalty is that the variant only follows AR_comp and AD and since all compounds are low scoring it get -6. 
This discussion comes back sometimes, the reason is that if the variant had no compounds it would be considered uninteresting. And since all compounds are uninteresting the variant is uninteresting.
Does that make sense?

**Comment by dnil** [comment]
Unfortunately the disorder in question is dominant..

**Comment by moonso** [comment]
I understand, when we decided this rule we where aware of that problem. It is a compromise since if we would not follow this rule the list would be flooded with uninteresting variants. I think the reasoning was that if one is looking for a dominant variant a trio is chosen. It's super hard to find a dominant variant in a single case right?
