### ISSUE TITLE
Document VCF annotation

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#749]
We should document the whole workflow for vcf annotation to get the most out of Scout

**Comment by PeterARBork** [comment]
Upvoting @moonso. Of all the items we care about here at børneonkologisk laboratorium at Rigshospitalet, this would make the biggest difference to us. I think most of the issues that I've raised here on Scout's github arise because we treat the vcf's in slightly different ways after variant calling.

If you can provide the sequence of commands you apply to freshly called vcf-files,* I will quickly try them out and I think there's a good chance we could get Scout going in practice fast that way.

*  (We use gatk haplotypercaller plus VQSR for small variants and MANTA for structural variants).

**Comment by moonso** [comment]
This will be covered in #1330
