### ISSUE TITLE
Ensembl transcripts now in Scout???

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#759]
In a number of recently run samples we are getting hits high up in the rank score that come from ensembl transcripts.  As far as I can remember we have not seen this before.  Is there any explanation?  Here is an example: https://scout.scilifelab.se/cust003/14030/0fc8299e0ce74e90b5077ff35622d153

**Comment by moonso** [comment]
Hmm we have used ensembl transcripts for a long time, what is the problem here? This particular transcript does not have a RefSeq id so we display the Ensembl id instead. Since there are no RefSeq transcripts affected in the gene this transcript is shown in the overview table.
What would you like to see in this case?

**Comment by moonso** [comment]
I'm closing this, please reopen if there are any questions.
