### ISSUE TITLE
Feedback from clinicians

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#764]
Hi guys,
Last week I sat down with a couple of clinicians and we had a look at Scout. What follows is their feedback, intended to help you make Scout as useful as possible (for us). The order of comments is random.

- It's great that comments are visible from the list of variants.
- Entering percentages into the variant filters could be either as % or as decimal and its not clear which is required.
- In the variant list, it would be great with columns for
    - read depth of reference and alternative
    - mutation nucleotide and protein change
    - exac frequency
    - (Inheritance model was less interesting, so this could be replaced with the above).
- In the variant list, they repeatedly used the gene-link when intending to see the variant page and getting used to using the rank-score link took multiple tries. At first sight, they didn't expect the rank-score link to be interesting and so it was surprising that this is the most important one for them.
- They would like to have a page where the coverage across genes in a given gene-panel is shown for a particular case.
- A link to exac was broken (I forgot to log the particular variant, I'll find it if needed).
- What does the clinical filters-button do in the variant list overview?
- They saw variants with high MAF being ranked as important and wondered why.
- Links to clinvar were broken for variants with clinvar annotations (again I blundered and forgot to log the variants, I'll find it if needed).
- In variants list, they would like the filter options and column headings to stay visible even when they scroll down.
- The clinsig confident button gave variants without clinsig annotation
- They would like a link to [COSMIC](http://cancer.sanger.ac.uk/cosmic) when viewing a variant.
- They would like a link to [ProteinPaint](https://pecan.stjude.cloud/proteinpaint/TP53) from Sct. Jude or something similar because it visualizes in what protein-domain the variant is located.
- For analyzing RNA-seq data, they'd like a column in the variants view which shows if the variant is in germline or tumor and one for showing expression level.
- The link to 1000G redirected to GRCh37 instead of 38 (the config.yaml has the line "human_genome_build: 38" at the end).

They are interested in using Scout and we will use it "live" for some of the analyses for an upcoming batch of cases.

We hope this helps you and we're happy to elaborate and discuss.

**Comment by moonso** [comment]
Wow, you've come a long way then! I'm happy to hear that. I think it is important that you mention what kind of analysis we are talking about here. When reading some of your notes it sounds like you have looked at a cancer analysis? We have a basic track for that implemented in Scout, it needs more work and we hope a lot will happen there this year.

**Comment by moonso** [comment]
> - It's great that comments are visible from the list of variants.

👍 

> - Entering percentages into the variant filters could be either as % or as decimal and its not clear which is required.

Aha i see your point, we have always used decimal here anything else would be quite confusing.

> - In the variant list, it would be great with columns for
    - read depth of reference and alternative
    - mutation nucleotide and protein change
    - exac frequency
    - (Inheritance model was less interesting, so this could be replaced with the above).

This is highly dependent on the analysis type, which analysis type did you perform? Frequencies will be replaced by gnomAD(exac) in the next update.
 
> - In the variant list, they repeatedly used the gene-link when intending to see the variant page and getting used to using the rank-score link took multiple tries. At first sight, they didn't expect the rank-score link to be interesting and so it was surprising that this is the most important one for them.

Well it could have been the opposite, some thing you just have to get used to. It is good to have a link to the gene also.

> - They would like to have a page where the coverage across genes in a given gene-panel is shown for a particular case.

This works in our setting when you have a chanjo database connected to the scout instance. @northwestwitch is working on updating the documentation for that part. Are you using chanjo?

> - A link to exac was broken (I forgot to log the particular variant, I'll find it if needed).

Ok that should be an issue then.

> - What does the clinical filters-button do in the variant list overview?

The clinical filter was worked out by our collaborators a while ago, they realised that they used the same setting over and over so we implemented a pre fill solution. One might allow this to be dynamic in the future, each scout instance could have its own clinical filter.
For now if you click that button and then open the filter again you will see how it was filled. 

> - They saw variants with high MAF being ranked as important and wondered why.

What is a high MAF? Also depends on the analysis type, right? This is specified in the rank model you have used earlier, that can easily be modified.

> - Links to clinvar were broken for variants with clinvar annotations (again I blundered and forgot to log the variants, I'll find it if needed).

We are aware of that, clinvar completely changed ids in a update not long ago. We are working on how to cope with that. Discussion in #695 

> - In variants list, they would like the filter options and column headings to stay visible even when they scroll down.

Not sure if that is possible with the solution we are using, we can investigate

> - The clinsig confident button gave variants without clinsig annotation

Hmm that sounds like a bug then. But could also be due to the change described above.

> - They would like a link to [COSMIC](http://cancer.sanger.ac.uk/cosmic) when viewing a variant.

Sure that should be added in the cancer view if not already there, have you checked that?

> - They would like a link to [ProteinPaint](https://pecan.stjude.cloud/proteinpaint/TP53) from Sct. Jude or something similar because it visualizes in what protein-domain the variant is located.

Ok sounds interesting 

> - For analyzing RNA-seq data, they'd like a column in the variants view which shows if the variant is in germline or tumor and one for showing expression level.

Something similar is implemented in the cancer setting. Please have a look at the demo data. There is no support at all for RNA analysis at the moment but it is also in the pipeline. Hope we can work on that together!

> - The link to 1000G redirected to GRCh37 instead of 38 (the config.yaml has the line "human_genome_build: 38" at the end).

Yes this is mentioned in #395 .

**Comment by moonso** [comment]
Closing, reopen or split into smaller issues if this becomes relevant
