### ISSUE TITLE
Way to update HPO terms

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#774]
There are new terms added so we need a way to update the HPO terms in scout

**Comment by moonso** [comment]
There should be a command that says 
```scout update hpo```
It should use requests to fetch the latest version of the HPO terms from http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastStableBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_phenotype_to_genes.txt
There are functions in scout to parse build and load the terms.
https://github.com/Clinical-Genomics/scout/blob/master/scout/load/hpo.py

**Comment by northwestwitch** [comment]
Hi, I think the problem of scout not finding HPO terms when they're in hpoweb is also related to the fact that certain terms don't have associated genes. This is the case of HP:0012335, and I think that the track used for updating scout is the one composed of HPO codes vs genes, so it lacks all those HPO terms with no genes. If it makes sense having in scout HPO terms not associated to genes than we should write an alternative method in the hpo upload file to take care of these cases.. I'll see what it can be done, and I'll remove the "easy" tag, for starters :)

**Comment by moonso** [comment]
Hehe that sounds right. We need to find another source for HPO terms then.

**Comment by northwestwitch** [comment]
We might always use one of the persistent URLs (like https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.obo). It would be quite easy to parse this one actually, but I wonder how this would affect scout. For instance whenever it is called a subroutine that does stuff with a gene list of an HPO terms, and we have those. We have to be careful and test well before, otherwise we might introduce a whole lot of new bugs!
