### ISSUE TITLE
Inheritance pattern (OMIM) wrong in SCOUT

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#776]
https://scout.scilifelab.se/cust002/F0016063/c82efc7cc7d258cccea13b53a9a937b6

According to OMIM this disease is AD but in SCOUT annotated as AR

**Comment by dnil** [comment]
Nice! Any idea what brought this one about in the first place? Error in a particular OMIM morbid snapshot or sth else?

**Comment by northwestwitch** [comment]
I was checking if the entry was modified in OMIM lately but I haven't found any "history" option so far. But I'll let you know if I find out!

**Comment by northwestwitch** [comment]
Naaa it hasn't been modified since 2011, so the error must be by our side!

**Comment by dnil** [comment]
Still, what is on the OMIM pages and what is in their exported files is not 100% identical. Otherwise a parse error on load?

**Comment by northwestwitch** [comment]
I don't know, but I've registered to omim to be able to download all files, not just "mim2gene.txt" from here https://www.omim.org/downloads/. Once they approve me I'll check if there is an error in their files (I really hope so!!)

**Comment by northwestwitch** [comment]
The error is in their file (genemap2), where under phenotypes there is written "autosomal recessive" instead of dominant. This is the line:

chr3 | 111542078 | 111665995 | 3q13.13 | 3q13.1-q13.2 | 606037 | CD96, TACTILE | CD96 antigen | CD96 | 10225 | ENSG00000153283 |   | C syndrome, 211750 (3), Autosomal   recessive | Cd96 (MGI:1934368)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

I'll write them an email so they can fix the error. Thanks @hassanfa for the omim files!

**Comment by henrikstranneheim** [comment]
👍

**Comment by dnil** [comment]
*phew* Ahem, as suspected! Thanks - good job!

**Comment by northwestwitch** [comment]
I just got a reply from OMIM confirming that the new version of genemap2 doesn't have the error, so when we update the OMIM definitions is fine!
