### ISSUE TITLE
SCOUT-STAGE: alignment view does not seem to work for mip 6 cases

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#859]
Here is an example:
https://scout-stage.scilifelab.se/cust000/F0005756-validation/f8bcd0d571c638a0b064b1170044bda3

Clicking View Alignment just shows me this:
![screen shot 2018-06-18 at 3 20 41 pm](https://user-images.githubusercontent.com/12113434/41538282-41b74b26-730b-11e8-90b9-4e0ae0d22a8c.png)

**Comment by emiliaol** [comment]
@moonso @northwestwitch this is something that needs to be working for the validation :(

**Comment by moonso** [comment]
Ok I'll have a look

**Comment by moonso** [comment]
Please continue with validation meanwhile!

**Comment by northwestwitch** [comment]
The files for that case that you gave us the link for are on the server. I'll take a look at this as in the afternoon!

**Comment by northwestwitch** [comment]
Is this solved?

**Comment by moonso** [comment]
No, I can not understand what's the problem. I've updated code [here](https://github.com/Clinical-Genomics/scout/blob/master/scout/server/blueprints/pileup/templates/pileup/pileup.html) so that pileup.js uses a remote genome source instead of a local one. It could be this that causes the problem but I am not sure.

 Before the genome source was a file on disc with hard coded paths... 
Maybe @robinandeer can say something?

**Comment by northwestwitch** [comment]
I don't think there is a problem with the location of the files (bam, bai, vcf). Try to use the scout link @emiliaol gave us without the "-stage" . The visualization works!

**Comment by northwestwitch** [comment]
Guys, it works. The problem is that the browser thinks that the javascript code is unsafe and blocks it. This is the screenshot of the url on my browser: 

![image](https://user-images.githubusercontent.com/28093618/41606287-9b7954c8-73e3-11e8-8886-15e621068a69.png)

If I click on the small icon on the right of the address: 
![image](https://user-images.githubusercontent.com/28093618/41606346-ba38266e-73e3-11e8-9420-43aa173dbc77.png)

And un-block it by clicking on "load unsafe scripts", it actually works: 

![image](https://user-images.githubusercontent.com/28093618/41606409-e663e9a8-73e3-11e8-90c2-04ed0546517c.png)
