### ISSUE TITLE
Update Clinical filter

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#95]
What should be included in the clinical filter?

**Comment by robinandeer** [comment]
Suggestion from CMMS to include splice donor and acceptor sites

**Comment by moonso** [comment]
Was this concluded?

**Comment by nicolelesko** [comment]
Looks like nobody else is interested in commenting.  Maybe if you implement it you will get some reaction!  All of the CMMS users are in favour.

**Comment by dnil** [comment]
I would guess no comments due to agreement? To me, these are of the highest importance among splice variants, and easiest to interpret. This seems the correct setting for a quick filter, with splice site predictors not being exactly what they should be.

Before actually going as far as answering out a sample as without abnormal finding, one may do well in checking also a few more nucleotides into the intron for a potential causative variant. But that is another story.
