### ISSUE TITLE
Problems after update to 4.1.0 - Sanger verification

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#998]
Would appreciate if the pop-up would be not according to site - but according to person that clicked on the Sanger button - We have some cases where Sanger has been verified by CMMS or Clinical immunology...
i.e. shared cases...

**Comment by northwestwitch** [comment]
That's a good suggestion, and quite easy to fix!

**Comment by sofievonlanthen** [comment]
Not sure if this is not working, or if I don't understand it, but I can see a long list of Sanger verifications in cases even if no Sanger has been ordered on any of the variants pinned in that case. I can also see cases where the Sanger has been verified, put still show up on the list. Is the list only suppose to contain cases where Sanger has been ordered, but not validated?
I would prefer to be able to see all the Sanger orders for Clinical Immunology, since I am the one performing them, it would be a good reminder which cases I have on going.

**Comment by northwestwitch** [comment]
Hi Sofie, could you post here an example of the cases you are mentioning? I'm improving the functionality of the Sanger validations on these days so I'll fix any bug of this type. Thanks!

**Comment by sofievonlanthen** [comment]
![sanger_screenshot_list](https://user-images.githubusercontent.com/36202149/46941344-32f81f80-d06b-11e8-94cb-338a0905b65b.PNG)
![sanger_screenshot_nosanger](https://user-images.githubusercontent.com/36202149/46941345-3390b600-d06b-11e8-9b33-f63aebdef3dc.PNG)
![sanger_screenshot_validated](https://user-images.githubusercontent.com/36202149/46941346-3390b600-d06b-11e8-9202-efe6332185da.PNG)

**Comment by sofievonlanthen** [comment]
So the first is the list. The other pic is on an archived case, which has no sanger ordered, and the third pic is a case which is solved and the sanger has been validated. Maybe I am missing something?

**Comment by northwestwitch** [comment]
Hi! I think I understood what is wrong here.

**First case (the archived one):** I checked in the database and the case has actually one variant with sanger ordered and canceled (https://scout.scilifelab.se/cust004/318701400067fam/a90bb8e83968ddce620e5e1a8fdacceb).


**Second case:** Second case has 2 sanger ordered in database:

1. https://scout.scilifelab.se/cust004/318701400042fam/8b9ef5ed8529b556fb9b2c2786f3072e : sanger ordered and validated

2. https://scout.scilifelab.se/cust004/318701400042fam/14fed02301ec5b9c2e7d855291d11a40 : sanger pending. You have no way to know that this variant is still to be evaluated because it's not pinned.

I'll need to fix both things: don't take into account the sanger canceled and add the specific variant IDs to the popup, so you you which ones are pending regardless if they're pinned or not.

Thanks a lot for your input, these examples are really useful to improve the validation functionality!!
